/*
 * $Id$
 *
 * Copyright (c) 1998-2008 John Morrison.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


#define    STR_DLGOPENING_OPTION2  "TCP/IP"
#define    STR_OK                  "OK"
#define    STR_DLGOPENING_BUTTON2  "Quit"
#define   STR_DLGLANG_NAME        "English (Default)"
#define   STR_DLGLANG_AUTHOR_CAPTION "Author: "
#define   STR_DLGLANG_AUTHOR      "John Morrison"
#define   STR_DLGLANG_NOTES_CAPTION "Notes: "
#define   STR_DLGLANG_NOTES       "None."
#define   STR_DLGLANG_DEFAULTNOTE "Note: For incomplete translations the missing items default back to English."
#define   STR_DLGABOUT_TITLE      "About WinBolo"
#define   STR_DLGALLIANCE_TITLE   "Alliance Request"
#define   STR_DLGALLIANCE_ACCEPT  "&Accept"
#define   STR_DLGALLIANCE_DECLINE "&Reject"
#define   STR_DLGALLIANCE_BLURB   " requests alliance. Accept?"
#define   STR_YES                 "Yes"
#define   STR_NO                  "No"
#define   STR_DLGGAMEINFO_TITLE   "WinBolo Game Information"
#define   STR_DLGGAMEINFO_MAPNAME "Map Name: "
#define   STR_DLGGAMEINFO_NUMPLAYERS "Number of Players: "
#define   STR_DLGGAMEINFO_GAMETYPE "Game Type: "
#define   STR_DLGGAMEINFO_HIDDENMINES "Hidden Mines: "
#define   STR_DLGGAMEINFO_TIMELIMIT "Game Time Limit: "
#define   STR_CANCEL              "Cancel"
#define   STR_DLGGAMESETUP_TITLE  "Game Setup"
#define   STR_DLGGAMESETUP_CHOOSEMAP "Choose map"
#define   STR_DLGGAMESETUP_RADIO1 "Open Game (each new tank comes pre-armed)"
#define   STR_DLGGAMESETUP_RADIO2 "Tournament (free ammunition early in the game)"
#define   STR_DLGGAMESETUP_RADIO3 "Strict Tournament (no free ammunition at all)"
#define   STR_DLGGAMESETUP_HIDDENMINES "Allow Hidden Mines"
#define   STR_DLGGAMESETUP_PASSWORD "Game Password"
#define   STR_DLGGAMESETUP_MINUTES "minutes"
#define   STR_DLGGAMESETUP_SECONDS "seconds"
#define   STR_DLGGAMESETUP_STARTDELAY "Game start delay"
#define   STR_DLGGAMESETUP_TIMELIMIT "Game time limit"
#define   STR_DLGGAMEINFO_TIMEREMAINING "About %d minute(s)"
#define   STR_DLGGAMEINFO_OPEN    "Open"
#define   STR_DLGGAMEINFO_TOURN   "Tournament"
#define   STR_DLGGAMEINFO_STRICT  "Strict Tournament"
#define   STR_DLGGAMEINFO_AIADV   "Yes (With an Advantage)"
#define   STR_DLGGAMESETUP_DEFAULTNAME "Me"
#define   STR_DLGKEYSETUP_TITLE   "Choose Key Settings"
 #define  STR_DLGKEYSETUP_DRIVETANK "Drive Tank:"
#define   STR_DLGKEYSETUP_GUNRANGE "Gun Range:"
#define   STR_DLGKEYSETUP_WEAPONS "Weapons:"
#define   STR_DLGKEYSETUP_VIEW    "Change Views:"
#define   STR_DLGKEYSETUP_SCROLL  "Scroll:"
#define   STR_DLGKEYSETUP_AUTOSLOWDOWN "Auto slowdown"
#define   STR_DLGKEYSETUP_AUTOGUNSIGHT "Enable Automatic show and hide of gunsight"
#define   STR_DLGKEYSETUP_FASTER  "Accelerate"
#define   STR_DLGKEYSETUP_SLOWER  "Decelerate"
#define   STR_DLGKEYSETUP_TURNLEFT "Anti-clockwise"
#define   STR_DLGKEYSETUP_TURNRIGHT "Clockwise"
#define   STR_DLGKEYSETUP_INCREASE "Increase"
#define   STR_DLGKEYSETUP_DECREASE "Decrease"
#define   STR_DLGKEYSETUP_SHOOT   "Shoot"
#define   STR_DLGKEYSETUP_LAYMINE "Lay mine"
#define   STR_DLGKEYSETUP_TANKVIEW "Tank view"
#define   STR_DLGKEYSETUP_PILLVIEW "Pillbox"
#define   STR_DLGKEYSETUP_SCROLLUP "Up"
#define   STR_DLGKEYSETUP_SCROLLDOWN "Down"
#define   STR_DLGKEYSETUP_SCROLLLEFT "Left"
#define  STR_DLGKEYSETUP_SCROLLRIGHT "Right"
#define   STR_DLGMSG_BUTTON       "&Send"
#define   STR_DLGMSG_ALLPLAYERS   "All players"
#define   STR_DLGMSG_ALLALLIES    "All allies"
#define   STR_DLGMSG_NEARBY       "All nearby tanks"
#define   STR_DLGMSG_SELECTION    "Selection on the Players menu"
#define   STR_DLGMSG_SENDPLAYER   "Sending message to %d player"
#define   STR_DLGMSG_SENDPLAYERS  "Sending message to %d players"
#define   STR_DLGNETINFO_TITLE    "WinBolo Network Information"
#define   STR_DLGNETINFO_SERVERPING "Server ping (ms):"
#define   STR_DLGNETINFO_STATUS   "Network status:"
#define   STR_DLGNETINFO_ERRORS   "Network errors:"
#define   NETERR_JOININIT         "There was no response from the game you tried to contact.\nThis usually means 1 of 3 things:\n1. You have the address and port fields incorrect.\n2. You are behind some kind of firewall preventing UDP access.\n3. Check that your version of WinBolo is the same as the game"
#define   NETERR_GAMEFULL         "This game is currently full"
#define   NETERR_SERVERCONNECT    "Failed to make a connection with the server. Try a different machine or wait a few seconds and try again."
#define   NETERR_PASSWORDWRONG    "The password is incorrect"
#define   NETERR_PLAYERNAMEINUSE  "Your player name is in use. Select another and try again"
#define   NETERR_NONEWPLAYERS     "Sorry, this game is currently not accepting players"
#define   NETERR_CONNECTNOJOIN    "You were able to connect to the game but you were not allowed to join. This probably means that your player name has been taken. Please try again with a new name"
#define   NET_STATUS_JOINING      "Joining"
#define   NET_STATUS_OK           "OK"
#define   NET_STATUS_FAILED       "Failed"
#define   NETERR_LOSTCONNECTION   "You have lost your connection to the server.\nNow dropping you to single player mode"
#define   STR_DLGMSG_TITLE        "Compose Message"
#define   STRERR_HELPFILE         "Error opening help file."
#define   STR_DLGPASSWORD_TITLE   "Password"
#define   STR_DLGPASSWORD_BLURB   "This game is password protected. Enter the correct password to join:"
#define   STR_DLGSETNAME_BLURB    "Enter the new player name for your tank"
#define   STR_DLGTRACKER_TITLE    "Tracker Config"
#define   STR_DLGTRACKER_USETRACKER "Use Tracker"
#define   STR_DLGTRACKER_TRACKERADDRESS "Tracker Address:"
#define   STR_DLGTRACKER_TRACKERPORT "Tracker Port:"
#define   STR_DLGSYSINFO_TITLE    "WinBolo System Information"
#define   STR_DLGSYSINFO_CPUUSAGE "CPU usage:"
#define   STR_DLGSYSINFO_SIMMODELING "Simulation Modelling:"
#define   STR_DLGSYSINFO_COMPROCESSING "Communications processing:"
#define   STR_DLGSYSINFO_TOTAL    "Total:"
#define   STR_DLGTCP_BLURB        "To join an internet Bolo game, you must give the name (or IP address) of a host machine running Bolo, and the UDP port number of the Bolo process on that machine."
#define   STR_DLGTCP_JOIN         "&Join"
#define   STR_DLGTCP_REJOIN       "&Rejoin"
#define   STR_DLGTCP_NEW          "&New"
#define   STR_DLGTCP_TRACKERSETUP "&Tracker Setup"
#define   STR_DLGTCP_REMEMBER     "Remember player name"
#define   STR_DLGTCP_MACHINENAME  "Machine Name (or IP adrress):"
#define   STR_DLGTCP_THEREUDP     "UDP port of Bolo on the server machine:"
#define   STR_DLGTCP_USUDP        "UDP port for the Bolo on this machine:"
#define   STR_DLGTCP_NAME         "Your player name for the game:"
#define   STR_DLGTCP_NEWBLURB     "Click ""New"" to begin a game"
#define   STR_DLGTCP_JOINBLURB    "Click to ""join"" an existing game"
#define   STR_DLGTCP_REJOINBLURB  "Click ""Rejoin"" to rejoin a game and reclaim your old posessions"
#define   STR_ERR_DLGTCP_PORTS    "Server and own ports are the same!"
#define   STR_ERR_DLGTCP_NOTRIGHT "Something isn't correct here..."
#define   STR_GAMEFRONT_LANFINDER_TITLE "LAN Game Finder"
#define   STR_GAMEFRONT_TRACKERFINDER_TITLE "Tracker Game Finder"
#define   STR_GAMEFRONTERR_JOINGAME "An error occurred trying to join the game"
#define    STR_WBTIMELIMIT_END     "Timelimit has expired. The Game has ended."
#define    STR_WBERR_SAVEMAP       "Error Saving Map (Disk full?)"
#define    STR_TUTORIAL01          "Ahead of you is a short river leading inland. Hold\ndown the ""Q"" to drive your boat to the end of the\nriver.\n\nWhen you get there, keep holding ""Q"". The tank will\ndisembark from the boat and the boat will be left\nmoored at the end of the river"
#define    STR_TUTORIAL02          "You are now on the grass. The tank moves quite\nquickly on grass.\n\n\nKeep pressing ""Q"" to move ahead to the forest."
#define    STR_TUTORIAL03          "You are now in the forest. The tank moves more\nslowly in the forest than it does on grass.\n\n\nKeep pressing ""Q"" to move ahead to the swamp."
#define    STR_TUTORIAL04          "You are now in the swamp. The tank moves very\nslowly in swamp. Fortunately there is a road ahead.\n\n\nKeep pressing ""Q"" to move ahead to the road."
#define    STR_TUTORIAL05          "You are now on the road. The tank can move very\nquickly on road and if you press ""Q"" the tank will\nspeed up.\n\n\nIf you find yourself going too fast you can press ""A"""
#define    STR_TUTORIAL06          "There are some buildings ahead. Buildings are solid\nobstacles that you cannot drive through, so you will\nhave to find your way through the maze to the other\nside.\n\nTo make the tank turn left press ""O""\nTo make the tank turn right press ""P"""
#define    STR_TUTORIAL07          "These round objects with the red guns poking out are\nautomatic pillboxes. They will shoot at any tank\ncomes with within range.\n\n\nFortunately the buildings provide protection from the\nshots, so the pillboxes will not be able to hit you\nunless you wait so long that they manage to\ncompletely shoot their way through the buildings."
#define    STR_TUTORIAL08          "Forest also provides protection from pillboxes, but in\na different way. As well as slowing down the tank a\nlot, driving through forest also limits visibility.\n\n\nWhen you are inside forest you can still clearly see\neverything outside the forest, but pillboxes (and\nother players) cannot see your tank unless you get\nvery close to them."
#define    STR_TUTORIAL09          "Line up your tank with the middle of the strip of\nforest and drive due North. If you go straight\nand don't stray too close to the edges of the forest,\nthe pillboxes will not see you and they will not shoot.\n\n\nDon't drive outside the forest of you'll get blown to pieces.\n"
#define    STR_TUTORIAL10          "There is one other simple way to escape pillboxes -\nspeed.\n\n\nMake sure you are correctly lined up with the centre\nof the road, and hold ""Q"" to go full speed past the\npillboxes."
#define    STR_TUTORIAL11          "When they notice you they will start shooting, but if\nyou keep going straight ahead and don't lose your\nnerve you will be out of range before the shots can\nhit you.\n\n\nDon't run off the road into the marsh or you'll be a\nsitting duck targe for the pillboxes, and you don't be\nable to move quickly enough to escape."
#define    STR_TUTORIAL12          "Ahead of you is a refuelling base. Refuelling bases provide\nshells for you to shoot, mines for you to lay secret traps\nwith, and they also repair your tank's armour back to full\nstrength if it has been damaged.\n\n\nStop on the refuelling base and load up your tank\nwith shells."
#define    STR_TUTORIAL13          "You are on the refuelling base. Your tank will now\nload up with shells and mines, as the indicators on\nthe right will show. Ahead of you, beyond the\nbuildings, is a minefield."
#define    STR_TUTORIAL14          "If you drive your tank into the minefield it will be\ndestroyed. Fortunately you can clear a minefield by\nshooting. Press the space-bar to shoot.\n\nShoot a hole through the building, and then land a\nshell in the middle of the minefield to detonate it.\nWhen you blow up the mines they will make a big\ncrater in the ground, which you can drive through,\nalthough it is as slow as driving through swamp."
#define    STR_TUTORIAL15          "Ahead is another minefield. Do the same trick again:\nDrive onto the refuelling base, shoot through the\nwall, and land a shell in the middle of the minefield to\ndetonate it.\n\nThis time though, the minefield is adjacent to a large\nriver, and water will flood into the craters. You can\ndrive the tank through the water like you can through\ncraters and marsh."
#define    STR_TUTORIAL16          "WinBolo automatically scrolls the window to show you\nthe area around your tank but you can use the arrow keys\non the keyboard to the manually override the view WinBolo\nchooses.\n\nPress the Up-Arrow key on the keyboard now to get a\nbetter view of the river ahead of you."
#define    STR_TUTORIAL17          "As well as being very slow, driving through water has\nanother disadvantage: It will also deplete your tank's\nsupplies of shells and mines.\n\n\nWhen you get to the other side your tank will still be\nin working condition, but you will have lost all\noffensive capability."
#define    STR_TUTORIAL18          "This time we are going to be more subtle about\ncrossing the river. Instead of just driving through the\nwater, we are going to build a bridge.\n\n\nSelect tree farming mode by clicking on the forest\nicon (top left of the window) and click on the forest.\nYour builder will run out of the tank and harvest one\ntree for building materials."
#define    STR_TUTORIAL19          "After farming some tree, select the road/bridge tool\n(the second button from the top) and click the mouse\non the river at the end of the road.\n\n\nYour builder will run out of the tank and build one\nsegment of bridge. Click again to complete the bridge\nand then drive across to the other side."
#define    STR_TUTORIAL20          "This river is wider than the last, and at the centre it is\ntoo deep for you to build a bridge. If you try to just\ndrive through the tank will sink to the bottom and be\ndestroyed."
#define    STR_TUTORIAL21          "To cross this river you will have to build a boat. Boats\ntake five trees, so click on the five trees to farm them.\nThen select the wall/boat tool (the third button from\nthe top) and click on the water to build a boat.\n\nIf you click on the land you will build a wall instead\nand you will have to farm some more trees to build a\nboat. Drive onto the boat and cross the river to the\nother side."
#define    STR_TUTORIAL22          "There is a pillbox ahead, and some refuelling bases to\nprovide you with ammunition. Collect shells from the\nrefuelling base and attack the pillbox.\n\n\nIt will shoot back, but if you tank gets hit you can easily\nreturn to the refuelling base to get your armour repaired\nback to full strength again."
#define    STR_TUTORIAL23          "With patience and caution you should be able to destroy this\npillbox. Use the skills you have learned to make it easier:\n\n\nHide in the forest so that the pillbox can't see you,\nfarm trees, build roads to make your tank move\nfaster, and build buildings to provide cover against\npillbox shots."
#define    STR_TUTORIAL24          "After you manage to defeat this pillbox, your final\nchallenge of the tutorial is to take out the two\npillboxes guarding the exit, build a boat, and escape.\n\n\nTake special care to watch your tank's armour level -\nif you get your tank destroyed you'll have to start\nwith a new tank on a new boat out at sea again."
#define    STR_TUTORIAL25          "Congratulations. You have completed the WinBolo\ntutorial.\n\n\n\nNow organise some friends to play with and find out\nwhat it is like to compete against intelligent human\nopponents instead of stationary unthinking targets."
#define    STR_TUTORIAL_START01    "Welcome to the WinBolo tutorial. This island introduces\nthe basic principles of WinBolo and leads you through\nthem one at a time. Each new principle will be\ndescribed in a window like this one.\n\nAfter reading each message, you can proceed by\nclicking the ""OK"" button on the mouse or simply\nby pressing the <Return> key on the keyboard"
#define    STR_TUTORIAL_START02    "WinBolo is a clone of the classic Macintosh network game Bolo.\nYou can find out strategy hints and other information from the official website:\n\nhttp://www.lgm.com/bolo\n\nor\n\nhttp://www.lgm.com/winbolo\n"
#define    STR_TUTORIAL_START03    "One quick note about Internet play.\n\nIf you join a online game and are a lot of network errors\nthen leave the game straight away before\nyou ruin the game for the other players."
#define    STR_TUTORIAL_START04    "You are in control of a tank, which is currently on a\nboat at sea. Press ""Q"" to make the tank (and boat) go\nforwards, and press ""A"" to make it slow down and\nstop.\n\nDon't tap the keys as if you are typing a letter -\npress and hold them until the tank is going at the speed\nyou want and then let go. Press ""Q"" now to make the\nboat drive forwards towards the land.\n(Press <Return> first to dismiss the window)"
#define    LGM_MAN_DEAD            "You cannot build until your new man parachutes in"
#define    LGM_NO_BUILD            "You cannot build that there"

#define    LGM_INSUFFICIENT_TREES  "You don't have the trees you require to build that"
#define    LGM_NO_PILLS            "You have no pillbox to place"
#define    LGM_INSUFFICIENT_MINES  "You have no mines to place"
#define    LGM_BUILDTANK           "The man cannot build on a tank"
#define    LGM_NO_TREE             "There is no tree to farm there"
#define    LGM_PILL_NO_NEED_REPAIR "That pillbox does not need repairing"
#define    LGM_PILL_NO_BUILD_ON_MINE "The man cannot build on a mine. It would kill him."
#define    LGM_NO_BUILD_UNDER_BOAT "The man cannot build under your boat"
#define   MESSAGE_ASSISTANT       "Online Assistant"
#define   MESSAGE_NEWSWIRE        "Newswire"
#define   MESSAGE_AI              "Brain"
#define   MESSAGE_CHANGENAME      " has handed control over to """
#define   MESSAGE_NETSERVER       "Network Server"
#define   MESSAGE_THIS_COMPUTER   "This Computer"
#define   MESSAGE_CAPTURE_BASE    " captured a Neutral Base"
#define   MESSAGE_CAPTURE_PILL    " captured a Neutral Pillbox"
#define   MESSAGE_STOLE_PILL      " just stole pillbox from "
#define   MESSAGE_STOLE_BASE      " just stole base from "
#define   MESSAGE_LGM_DEAD        " just lost his builder"
#define   MESSAGE_SAVED_MAP       " just saved map file"
#define   MESSAGE_QUIT_GAME       " has quit game"
#define   MESSAGE_TIME_LIMIT_EXPIRED "Time Limit has expired. Game is over. Go in peace"
#define   MESSAGE_TANKSUNK        "Tank Sunk in Deep Sea"
#define   NETERR_TRACKERDNS       "The tracker hostname lookup failed. Tracker notification disabled"
#include "everard_map.h"
