-- Scenario script for tests/base_steal_B.map -- GENERATED by
-- tests/generate_base_steal_map.py, do not edit by hand.
--
-- Four jobs.
--
-- 1. MAKE THE BASES HOSTILE, AFTER the tanks are placed.  starts.c skips any
--    start square within START_BASE_RANGE (9) of a hostile base, and both near
--    bases are three tiles from the spawn -- so the map file writes them NEUTRAL
--    and this flips them in on_setup, which runs once per round with the tanks
--    already placed and no client having seen the world yet.
--
--    The owner is slot 1, which nobody occupies.  playersIsAllie asks the
--    OCCUPIED side of the pair (our bot, slot 0), gets "not in my alliance",
--    and the brain reads the base as hostile -- with no enemy tank driving
--    around the arena to muddy the test.
--
-- 2. HOLD THE NEAR BASES ONE SHELL FROM FALLING.  Armour 12: one
--    shell (DAMAGE 5) puts them at 7, at or below MIN_ARMOUR_CAPTURE (9), which
--    is capturable.  The far base stays at BASE_FULL_ARMOUR so its row must
--    still quote the full markup.
--
-- 3. FILL THE SPAWN POND once the tank has driven off it.  A start square has
--    to be DEEP SEA (starts.c startsIsValidSquare), so the arena has a one-tile
--    pond in the middle of it and the tank spawns afloat.  Once every base is
--    taken the bot has nothing left to do but explore a 33x33 field, and
--    wandering into that pond without a boat is an instant drowning -- noise
--    this test does not want to measure.  Filling it in with grass removes the
--    only water on the map.
--
-- 4. KEEP THE BOT'S ARMOUR READING ALIVE.  A bot only learns a hostile base's
--    armour from EVENT_BASE_STOCK, and the server only emits that when a base's
--    armour/shells/mines actually CHANGE.  An untouched base would go quiet and
--    the reading would age out, so every 150 ticks this re-asserts stock
--    with a mines value that alternates 90/89 -- a real change, so a real event.
--    It NEVER heals: armour is clamped DOWN to the target and left alone once
--    the bot has shot it.

local NEAR   = { { 123, 126 }, { 129, 126 } }
local FAR    = { 126, 138 }
local NEAR_ARMOUR = 12
local FAR_ARMOUR  = 90
local ENEMY  = 1
local PERIOD = 300        -- doubled: this host's tick counts 100 a second, not 50
local SPAWN  = { 126, 126 }
local GRASS  = 7

local flip = 0
local pond_filled = false
local next_stock = PERIOD    -- a due-tick, not a modulo: game.tick() steps by
                             -- 2 and keeps one parity all round, so `% PERIOD`
                             -- would fire on half the periods or on none

local function is_near(b)
  for _, n in ipairs(NEAR) do
    if b.x == n[1] and b.y == n[2] then return true end
  end
  return false
end

-- Re-assert stock on every base.  `flip` alternates the mines value so the
-- write is always a CHANGE and therefore always emits EVENT_BASE_STOCK.
local function assert_stock(g)
  flip = 1 - flip
  local mines = 90 - flip
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      local target = is_near(b) and NEAR_ARMOUR or FAR_ARMOUR
      -- Clamp DOWN only: undo the +1-per-1000-ticks regen, never heal a base
      -- the bot has already shot.
      local arm = b.armour
      if arm > target then arm = target end
      g.set_base_stock(i, arm, 0, mines)
    end
  end
end

function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, ENEMY)
      local target = is_near(b) and NEAR_ARMOUR or FAR_ARMOUR
      g.set_base_stock(i, target, 0, 90)
      g.message(string.format("BASE_STEAL_ARENA base#%d (%d,%d) owner=%d armour=%d",
                              i, b.x, b.y, ENEMY, target))
    end
  end
end

function on_tick(g, tick)
  if tick >= next_stock then
    next_stock = tick + PERIOD
    assert_stock(g)
  end
  -- Fill the spawn pond as soon as the tank is clear of it (see note 3).
  if not pond_filled and tick > 200 then    -- doubled with the clock
    local t = g.tank(0)
    if t and not (t.mx == SPAWN[1] and t.my == SPAWN[2]) and not t.boat then
      pond_filled = true
      g.set_tile(SPAWN[1], SPAWN[2], GRASS)
      g.message("BASE_STEAL_ARENA spawn pond filled at tick " .. tostring(tick))
    end
  end
end

-- ── the verdict ─────────────────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/base_steal_test.py, variant B, assertion 3 --
-- the only half of that driver a scenario can read: the WEST base at
-- (123,126) is ours at the end and the bot did not die taking it. The east
-- base is the guarded one and the driver never required it to fall, so it is
-- not asked about here either.
--
-- LEFT BEHIND, because it is print2 and nothing else: the whole point of this
-- variant -- that the east base's candidate rows read `REJECT covered` on
-- every in-range tick and that it never once armed the steal. Without that
-- half this arena no longer distinguishes itself from variant A; it only
-- says the pillbox did not stop the west base falling.
--
-- GATE: ticks=12000 bots=1 ai=yesfull gametype=open

local WEST = { 123, 126 }

VERDICT_CHECK = function(g)
  local west = nil
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b and b.x == WEST[1] and b.y == WEST[2] then west = b end
  end
  if west == nil then
    return false, "no base at (123,126)"
  end
  local t = g.tank(0)
  local deaths = t and t.deaths or 0
  if west.owner ~= 0 then
    return false, string.format("west base still owner %s", tostring(west.owner))
  end
  if deaths > 0 then
    return false, string.format("west base ours, but %d death(s)", deaths)
  end
  return true, "west base stolen past the guard pill, no deaths"
end
