-- Scenario sidecar for tests/blitz_contested_C.map -- GENERATED by
-- tests/generate_blitz_contested_map.py, do not edit by hand.
--
-- Variant C: the enemy tank is parked at (136,126), 7.0 tiles from the
-- pill at (129,126).  C.BLITZ_CONTESTED_RANGE is 9, so this take is
-- CONTESTED.
--
-- Four jobs.
--
-- 1. THE PILL IS THE ENEMY'S.  attack_pill only bids on a pill whose owner
--    reads "hostile", and a pill never shoots its own owner -- which is what
--    lets variant A park the enemy 7.0 tiles away without the pill deleting
--    it.  Held at full armour so the take stays HARD (>= HARD_TAKE_MIN_HP) and
--    a blitz commander is elected for it; that is the only route to a GO.
--
-- 2. THE BASES ARE THE ATTACKERS'.  One each, full stock, well west of the
--    pill: the bots start full so refuel never wins, but a base gives each of
--    them a real fallback goal instead of wandering.
--
-- 3. PINNED STARTS.  on_choose_start hands every tank its own pond so the
--    attackers cannot swap ends with each other or with the enemy, and a
--    respawn comes back to the same tile.  The last start is the enemy's.
--
-- 4. FILL THE ATTACKERS' PONDS once they are all ashore.  A start square has
--    to be DEEP SEA (starts.c startsIsValidSquare), and a tank that later
--    drives over one without a boat drowns -- noise this test does not want.
--    The ENEMY's pond is deliberately left alone: the idler never moves, so it
--    sits in its boat all round, and filling the water under it is not
--    something this test needs to find out about.
local PILL_XY   = { 129, 126 }
local ALLIES    = { 0, 1 }
local BASES     = { { 110, 116, 0 }, { 110, 136, 1 } }
local ALLY_PONDS = { { 114, 120 }, { 114, 132 } }
local FOE_PLAYER = 2
local FULL      = 90
local PILL_HP   = 15
local GRASS     = 7

local pill_n       = nil
local ponds_filled = false
local said         = false

local function index_pill(g)
  if pill_n then return end
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p and p.x == PILL_XY[1] and p.y == PILL_XY[2] then pill_n = i end
  end
end

-- Re-asserted for the first few ticks as well as in on_setup: the -bots slots
-- are not guaranteed to be filled in by the time on_setup runs, and an owner
-- set to a slot that does not exist yet would silently do nothing.
local function own_everything(g)
  index_pill(g)
  if pill_n then
    g.set_pill_owner(pill_n, FOE_PLAYER)
    local p = g.pill(pill_n)
    if p and not p.in_tank and p.armour < PILL_HP then
      g.set_pill_armour(pill_n, PILL_HP)
    end
  end
  for _, b in ipairs(BASES) do
    for i = 1, g.num_bases() do
      local bb = g.base(i)
      if bb and bb.x == b[1] and bb.y == b[2] then
        g.set_base_owner(i, b[3])
        g.set_base_stock(i, FULL, FULL, 90)
      end
    end
  end
  for _, a in ipairs(ALLIES) do g.set_team(a, 0) end
  g.set_team(FOE_PLAYER, 1)
end

function on_setup(g)
  own_everything(g)
end

-- Starts 1..#ALLIES are the attackers' ponds, in slot order; the one after
-- them is the enemy's.  Anything else the engine may place goes wherever it
-- likes.
function on_choose_start(g, p)
  for i, a in ipairs(ALLIES) do
    if p == a then return i end
  end
  if p == FOE_PLAYER then return #ALLIES + 1 end
  return nil
end

function on_tick(g, tick)
  if tick <= 20 then own_everything(g) end
  if not said and pill_n then
    local p = g.pill(pill_n)
    if p then
      said = true
      g.message(string.format(
        "BLITZ_CONTESTED_ARENA C: pill#%d (%d,%d) owner=%d armour=%d; enemy at (136,126), %s tiles away (CONTESTED)",
        pill_n - 1, p.x, p.y, p.owner, p.armour, "7.0"))
    end
  end
  -- Fill the ATTACKERS' ponds once none of them is afloat any more (job 4).
  if not ponds_filled and tick > 200 then
    local afloat = false
    for _, a in ipairs(ALLIES) do
      local t = g.tank(a)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(ALLY_PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("BLITZ_CONTESTED_ARENA ally spawn ponds filled at tick " .. tostring(tick))
    end
  end
end

-- ── the verdict: there is not one ───────────────────────────────────────
-- NOT PORTED (2026-09-15) from tests/blitz_contested_test.py check_C.
--
-- Every assertion this arena exists for is a statement about the BRAIN'S OWN
-- REASONING, read out of print2: the BLITZ_GO line and its `contested{...}`
-- label, the BLITZ_CONTESTED line with its `party=N -> 1 suicider` and its
-- `designate=[...]` list, the designee's `[role] blitz_suicider=true
-- src=blitz_contested` line, the `bsu ... c` verb that carried it, and the
-- later revert with its expiry reason. A scenario can see none of that, and
-- the engine has no stand-in for it: a designated suicider and an ordinary
-- blitzer drive to the same pill and shoot it, so the world state a verdict
-- could read is identical either way. The driver wrote a -finaljson file and
-- never opened it, which says the same thing.
--
-- WHAT THE ARENA ITSELF WOULD STILL NEED, if the brain's decisions ever become
-- visible to a scenario. Both are now cheap and neither is done here, because
-- an unrunnable arena's set-up cannot be tested:
--   * team 1 and team 2, not the 0 and 1 this file carries. Team 0 is NO team
--     on this host, so the 2 attackers would not be allies, no party would
--     form and no commander would be elected.
--   * a bots=0 gate line and the arena fielding all 3 seats itself, because
--     the runner's -bots hands out no init: each attacker needs
--     `game.init_tokens("blitz=2/4;cfg=BLITZ_CONTESTED_ALL_SUICIDERS=true")`
--     and the enemy needs brain = "../tests/brains/idle.lua".
--
-- GATE: ticks=2700 bots=3 ai=yesfull gametype=open limit=20
-- GATE: skip=C1-C5 are all BLITZ_GO / BLITZ_CONTESTED / [role] print2 lines; the designation count leaves no trace in world state
