-- Scenario script for tests/heat_pill_B.map (auto-loaded as
-- <map>.scenario.lua).  GENERATED by tests/generate_heat_pill_map.py -- edit
-- the generator, not this file.
--
-- Companion to tests/heat_pill_test.py arena B.
--
-- FOUR JOBS.
--
-- 1. OWNERSHIP.  The .map file can only say "owner 0", so the pill and the
--    base are handed to slot 0 (the -bots tank) and re-asserted after the foe
--    joins: a fresh connection can shuffle pill ownership.
--
-- 2. THE ENEMY, AND WHY IT IS PUT ASHORE.  Spawn one scripted IDLE bot
--    (tests/brains/idle.lua) on team 1 at start 2, the pond at
--    (129,126), then fill that pond in under it.  It never moves,
--    never shoots and never picks anything up, so d(P,E) and d(us,E) -- the
--    two numbers heat_pill_select compares -- are constants.
--
--    IT HAS TO BE ON LAND.  Left afloat it dies to the FIRST shell that
--    touches it: tankInGameDamage takes the boat away on any hit
--    (src/bolo/tank.c:1258-1265) and a tank standing on DEEP_SEA without a
--    boat drowns on the next update (tank.c:575).  Our own pill is 4.1 tiles
--    from it and shells it unprompted, so a floating enemy died in the middle
--    of the heat volley on the first run of this arena -- the target vanished
--    at hits 3-of-4, attack_tank went invalid and the volley disappeared
--    without an exit.  On grass the same tank has TANK_FULL_ARMOUR and rides
--    out the whole volley.  Start 3 exists because start 2 is grass by then
--    and a filled-in start is not a valid placement any more.
--
-- 3. FILLING OUR SPAWN POND, AND SPAWNING THE ENEMY ONLY AFTERWARDS.  A start
--    square has to be DEEP SEA at placement time, which leaves a one-tile hole
--    in our room.  It is filled back to GRASS once our tank is ashore AND off
--    it -- filling it underneath the tank leaves the boat state wedged.
--
--    THE ENEMY IS NOT SPAWNED UNTIL THAT HAS HAPPENED.  heat_pill_fire holds
--    the brake (KEY_SLOWER) for as long as a volley runs, and on the first run
--    of this arena the enemy existed from tick 2: the bot opened a volley at
--    brain tick 12 while still sitting in its boat on the spawn pond, braked,
--    and never came ashore at all -- 117 ticks of firing from the water, no
--    hits, and the pond never filled because the tank never left it.  With no
--    enemy on the map the bot simply explores, comes ashore, and the fight
--    starts on dry land.
--
-- 4. THE ENGINE'S OWN ANGER.  Every change of ARMOUR, OWNER, IN_TANK or
--    **SPEED** on our pill used to go to heat_pill_B_trace.log, which the
--    driver then read.  SPEED IS THE ENGINE'S ANGER (scenario.c:262): 100 =
--    PILLBOX_ATTACK_NORMAL, 6 = PILLBOX_MAX_FIRERATE, and it is the
--    engine-authoritative evidence -- the brain's `pill.anger` is only a
--    proxy and never appears here.  There is no io in the scenario sandbox,
--    so the same changes are counted in the watch below and the driver's
--    check_ladder is written out again as this arena's own verdict.
--
--    The pill is watched BY INDEX and never by coordinate: a pill that is
--    picked up rides along with the tank that took it, so a coordinate match
--    would stop finding it at exactly the moment the watch exists to prove
--    nobody took it.
--
-- THIS ARENA ALSO HOLDS THE PILL DOWN AT ITS MAP ARMOUR, because THE BOT
-- REPAIRS IT.  Both hp arenas turn on a pill that is deliberately hurt -- B at
-- 6 armour so the health cap allows nothing, B2 at 10 so it allows
-- exactly two of the engine's four halvings -- and in the first measured run
-- of arena B the builder pool sent the man out and the engine trace read
-- `286 126 125 15` at sim tick 286.  By the time an enemy existed the gate was
-- looking at a 15-hp pill and said ENTER.  A cfg token is the real fix (the
-- test passes BUILDER_POOL_TREES_TOPUP=99, which prices the errand past the
-- tank's whole woodpile); this clamp is the belt to that brace, and it only
-- ever lowers the armour, so it never undoes the volley's own damage.
--
-- Knocking it back down is an armour DROP, so world.lua bumps the anger proxy
-- -- but `hp` is tested BEFORE `already_hot` in heat_pill_select, so the skip
-- reason is unaffected.

-- THE ARENA FIELDS BOTH TANKS, so the GATE line says bots=0.  The measured
-- GoalHunter has to come in with heat_pill_test.py's pins, and the runner
-- fields its -bots N seats with no init at all -- so the only way the tokens
-- reach the brain is for the arena to do the spawn itself.
local OUR_BRAIN  = "../brains/GoalHunter/init.lua"
local OUR_SLOT   = 0
local FOE_SLOT   = 1
-- heat_pill_test.py TOKENS["B"], verbatim.
local OUR_TOKENS = "cfg=HEAT_REQUIRE_ENEMY_RANGE=0;cfg=BUILDER_POOL_TREES_TOPUP=99"
local OURS       = { { 126, 125 } }
local SPAWN      = { 123, 126 }
local FOE_SPAWN  = { 129, 126 }
local FOE_BRAIN  = "../tests/brains/idle.lua"
local GRASS      = 7
-- DOUBLED in the port.  The tick on_tick is handed now goes up by two a frame
-- where the old host's went up by one, so every number here that means a
-- DURATION had to grow by the same factor to mean the same wait.
local FILL_TICK  = 120           -- engine ticks: not before this
local SPAWN_WAIT = 40            -- engine ticks after our pond is filled
local LAND_WAIT  = 40            -- engine ticks after the foe is created
local p0         = 0

-- THE WATCH, which is what the trace file was for.  One sample a tick of the
-- one pill this arena is about, kept only as the handful of numbers the
-- driver's check_ladder asked the file for.
local PILL_CALM  = 100           -- PILLBOX_ATTACK_NORMAL
local PILL_MAXFR = 6             -- PILLBOX_MAX_FIRERATE, where halving stops

local last_sig     = nil         -- armour/owner/in_tank/speed, last seen
local seen         = 0           -- state CHANGES, i.e. rows the file would hold
local first_speed  = nil
local first_armour = nil
local prev_speed   = nil
local min_speed    = nil
local max_armour   = nil
local min_armour   = nil
local drops        = 0           -- downward steps of the reload period
local bad_step     = nil         -- a step that was not a halving
local stolen_at    = nil         -- tick the pill changed hands or was taken
local hot_at       = nil         -- tick the period first left PILL_CALM
local floor_tick   = nil         -- tick it first reached this arena's stop
local floor_armour = nil
local floor_drops  = nil

local function watch(g, idx, tick)
  local p = g.pill(idx)
  if p == nil then return end
  local in_tank = p.in_tank and 1 or 0
  local sig = p.armour .. "/" .. p.owner .. "/" .. in_tank .. "/" .. p.speed
  if sig == last_sig then return end
  last_sig = sig
  seen = seen + 1
  if first_speed == nil then
    first_speed, first_armour = p.speed, p.armour
    min_speed, max_armour, min_armour = p.speed, p.armour, p.armour
  end
  if p.speed < min_speed then min_speed = p.speed end
  if p.armour > max_armour then max_armour = p.armour end
  if p.armour < min_armour then min_armour = p.armour end
  if (p.owner ~= p0 or in_tank == 1) and stolen_at == nil then
    stolen_at = tick
  end
  if p.speed < PILL_CALM and hot_at == nil then hot_at = tick end
  if prev_speed ~= nil and p.speed < prev_speed then
    drops = drops + 1
    local want = math.floor(prev_speed / 2)
    if want < PILL_MAXFR then want = PILL_MAXFR end
    if math.abs(p.speed - want) > 1 and bad_step == nil then
      bad_step = prev_speed .. "->" .. p.speed
    end
  end
  prev_speed = p.speed
  if floor_tick == nil and p.speed <= HEAT_FLOOR then
    floor_tick, floor_armour, floor_drops = tick, p.armour, drops
  end
end

local filled      = false
local traced      = nil          -- { {pill_index, tile_x, tile_y}, ... }
local foe_player  = nil
local foe_tick    = nil
local foe_landed  = false
local spawn_tried = false
local us_tried    = false

local HOLD_HP = 6

local function same(p, t) return p.x == t[1] and p.y == t[2] end

-- Resolve OURS (tile coords) to PILL INDICES, once.  Everything after this
-- reads the pill BY INDEX and never by coordinate: a pill that is picked up
-- moves with the carrier, so a coordinate match would quietly stop finding it
-- at exactly the moment the watch exists to prove nobody took it.
local function resolve(g)
  local out = {}
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      for _, t in ipairs(OURS) do
        if same(p, t) then out[#out + 1] = { i, t[1], t[2] } end
      end
    end
  end
  return out
end

local function own_everything(g)
  for i = 1, g.num_pills() do
    if g.pill(i) then g.set_pill_owner(i, p0) end
  end
  for i = 1, g.num_bases() do
    if g.base(i) then
      g.set_base_owner(i, p0)
      g.set_base_stock(i, 90, 90, 90)
    end
  end
end

-- The roster ops are refused in on_setup on this host, and our own tank is one
-- of them now, so both spawns are in on_tick.  Team 0 is NO team rather than
-- team zero, which is what makes the team-1 foe hostile to us; it is asked for
-- on the spawn itself instead of with a set_team that has no seat to name yet.
function on_setup(g)
  own_everything(g)
end

-- START 1 IS OURS, START 2 IS EVERYBODY ELSE'S -- written that way round, and
-- NOT as `if p == foe_player then return 2 end`, because on_choose_start fires
-- DURING the g.spawn_bot call that creates the foe (scenario.c: the create path
-- runs inside serverSimCreateBot), i.e. before spawn_bot has returned and
-- before foe_player has been assigned.  A `foe_player`-keyed rule therefore
-- returns nil on the one placement that matters and the engine picks for
-- itself: measured on the first run of this arena, the idle bot landed on
-- start 1 -- OUR pond -- and heat_pill_select spent 300 ticks printing
-- d_us_enemy{0.0} SKIP:not_closer at an enemy sitting on our own hull.
function on_choose_start(g, p)
  if p == p0 then return 1 end
  -- Start 2 while the foe's pond is still water, start 3 once it has been
  -- filled in.  A start square is re-validated at every placement, so the
  -- filled tile stops being a legal spawn the moment it turns to grass.
  if foe_landed then return 3 end
  return 2
end

function on_tick(g, tick)
  -- 1. Our spawn pond, back to grass -- but only once the tank is ASHORE and
  --    off it.  Filling the tile while the tank still sits on it leaves the
  --    boat state stuck.
  if not filled and tick >= FILL_TICK then
    local tk = g.tank(p0)
    if tk and not tk.boat and not tk.dead
       and (tk.mx ~= SPAWN[1] or tk.my ~= SPAWN[2]) then
      filled = tick
      g.set_tile(SPAWN[1], SPAWN[2], GRASS)
      g.message(string.format(
        "HEAT_PILL_B filled the spawn pond at (%d,%d) with grass at t=%d",
        SPAWN[1], SPAWN[2], tick))
    end
  end

  -- 1a. OUR OWN TANK, which the runner no longer fields.  A spawn with no
  --     slot answers true rather than a seat, so the seat is named.
  if not us_tried and tick >= 2 then
    us_tried = true
    local u, uerr = g.spawn_bot{ slot = OUR_SLOT, name = "HeatUs",
                                 brain = OUR_BRAIN, team = 0, start = 1,
                                 init = g.init_tokens(OUR_TOKENS) }
    if u == nil then
      g.message("HEAT_PILL_B spawn_bot(us) failed: " .. tostring(uerr))
    end
    own_everything(g)
  end

  -- 2. The enemy tank, once, and only after that: a volley started while we
  --    are still afloat on the pond brakes the tank and it never comes ashore.
  if filled and not spawn_tried and tick >= filled + SPAWN_WAIT then
    spawn_tried = true
    foe_player = FOE_SLOT
    local s, err = g.spawn_bot{ slot = FOE_SLOT, name = "HeatFoe",
                                brain = FOE_BRAIN, team = 1, start = 2 }
    if s == nil then
      foe_player = nil
      g.message("HEAT_PILL_B spawn_bot failed: " .. tostring(err))
    else
      foe_tick = tick
      g.set_team(FOE_SLOT, 1)
      g.message("HEAT_PILL_B foe slot=" .. tostring(FOE_SLOT) .. " team=1 at t="
                .. tostring(tick))
      own_everything(g)
    end
  end

  -- 3. Put the enemy ashore, so one shell from our own pillbox cannot sink it
  --    out from under the volley.
  if foe_tick and not foe_landed and tick >= foe_tick + LAND_WAIT then
    local fk = g.tank(foe_player)
    if fk and fk.mx == FOE_SPAWN[1] and fk.my == FOE_SPAWN[2] then
      foe_landed = true
      g.set_tile(FOE_SPAWN[1], FOE_SPAWN[2], GRASS)
      g.message(string.format(
        "HEAT_PILL_B put the foe ashore at (%d,%d) at t=%d",
        FOE_SPAWN[1], FOE_SPAWN[2], tick))
    end
  end

  if not traced then traced = resolve(g) end

  -- Hold the pill at its staged armour: undo any repair the moment it lands.
  if traced and traced[1] then
    local idx = traced[1][1]
    local p = g.pill(idx)
    if p and not p.in_tank and (p.armour or 0) > HOLD_HP then
      g.set_pill_armour(idx, HOLD_HP)
    end
  end

  if traced[1] then watch(g, traced[1][1], tick) end
end

-- ── the verdict ───────────────────────────────────────────
-- PORTED (2026-09-15) from tests/heat_pill_test.py, check_skip_trace -- step 4
-- of check_skip("B"), the ENGINE half.  The gate is built to refuse this
-- ground every time, so nothing may heat the pill: the engine's reload period
-- holds at PILLBOX_ATTACK_NORMAL for the whole run, and the pill stays ours
-- and out of any tank.
--
-- LEFT BEHIND, all of it print2 from attack.lua and none of it visible to a
-- scenario: steps 0-3, which are the arena's real subject -- that the heat
-- block was REACHED at all, that no decision was an ENTER, that the refusal
-- was `SKIP:hp` and not one of the other seven, and that the line's
-- `los{..}` column tells the truth about which gate did the rejecting.  So a
-- PASS here says nobody heated this pill and says nothing about why the brain
-- declined to.
--
-- GATE: ticks=700 bots=0 ai=yesfull gametype=open

HEAT_FLOOR = 0           -- nothing to reach: this arena's ladder never starts

VERDICT_CHECK = function(g)
  if seen == 0 then
    return false, "no pill watched: OURS and the map's geometry have drifted"
  end
  -- THE ARENA ACTUALLY RAN.  The driver's step 0 asked this of print2 -- a
  -- HEAT_PILL line at all is proof the fight reached the heat block -- and
  -- that cannot move.  What CAN move is the engine-side half of the same
  -- question: an untouched pillbox proves nothing if our tank never came
  -- ashore or the foe was never fielded, and both of those are latched here.
  if not filled then
    return false, "our tank never came ashore, so the pond was never filled"
  end
  if not foe_landed then
    return false, "the foe was never fielded and put ashore"
  end
  if first_speed ~= PILL_CALM then
    return false, string.format("pill opened at period %d, not calm 100",
                                first_speed)
  end
  if hot_at then
    return false, string.format("period fell to %d at t=%d -- something "
                                .. "heated this pill", min_speed, hot_at)
  end
  if stolen_at then
    return false, string.format("pill changed hands or was taken at t=%d",
                                stolen_at)
  end
  return true, string.format("period flat at 100 over %d state(s), armour "
                             .. "%d..%d", seen, min_armour, max_armour)
end
