-- GENERATED by tests/generate_kill_me_map.py, then ported by hand onto the
-- scenario host on main.
-- Scenario script for tests/kill_me_B.map (auto-loaded as <map>.scenario.lua).
-- Companion to tests/kill_me_test.py arena B.
--
-- GATE: ticks=20200 bots=0 ai=yesfull gametype=open limit=20
--
-- WHAT THIS SCRIPT IS FOR: it puts player 0 into the LOADED, BUILDER-LESS
-- state -- three pillboxes aboard and a builder who is never coming home --
-- and it does it with the only tools the scenario API has, set_tile and
-- give_pill.  There is no LGM teleport and the script cannot read the man's
-- position at all, so his whereabouts are inferred from something the engine
-- publishes and the brain cannot fake: OUR PILL'S ARMOUR.  p0's only errand in
-- this arena is a top-up of the pill at (130,127), four armour down; when
-- game.pill() reports it at full the repair has landed, which means the man
-- walked to that tile and did the work there.  He is, at that instant, one
-- tile east of the gate.
--
-- THE GATE (x=128..129, y=126..128) then goes from FOREST to BUILDING, and that
-- is the whole stranding: lgm.c lgmReturn walks a straight line at the tank
-- with a per-axis slide and no re-route, so a full-height column he cannot
-- enter stops him for good.  The brain's own walk sim is that same straight
-- line, returns -1, and goals.lua's loaded_no_lgm reads a return ETA of STUCK.
--
-- WALL, NOT RIVER (which is what tests/stranded_lgm_A.scenario.lua floods
-- with).  River stops the MAN (MAP_MANSPEED_TRIVER 0) but not the TANK
-- (MAP_SPEED_TRIVER 3), and the stranded-LGM arena wants the rescue to stay
-- possible.  Here it must not be: measured on the first draft, the tank parked
-- on the river gate tile at t=1059 and the man simply walked up to it -- the
-- state ended 700 ticks after it started and there was nothing left to
-- measure.  A wall column ends the walk for good, in both directions.
--
-- ON THE SAME TICK the three pillboxes go aboard.  Order matters: give them
-- earlier and the bot places them instead of carrying them, and the errand
-- that walks the man out never happens.
--
-- TWO GUARDS ON THE FLOOD, both of which have to hold on the same tick:
--   * NEITHER tank is on the gate column, so we never drop a river under one;
--   * the pill is at full armour, still ours, and in nobody's tank -- an
--     armour rise on a pill that changed hands is not our repair.
-- AND A RETRY: when the two do not coincide the script knocks the pill back
-- down to TOPUP_ARMOUR, the pool sends the man out again, and the next
-- completion is another chance.
--
-- WHAT THE TRACE BECAME.  This file used to write every change of ARMOUR,
-- OWNER and IN_TANK to kill_me_B_trace.log for the python driver to read back.
-- There is no `io` in the scenario sandbox, and nothing reads a file any more,
-- so the four questions the driver asked of that log are kept as four locals
-- instead: wall_tick, gave_n, p0_died and corpse_to_p1.  They are still ENGINE
-- readings and never the brain's opinion of itself, which was the point.

-- THE DRIVER'S -bot-init PINS, now handed to the bots this arena spawns for
-- itself.  Each is the token string kill_me_test.py's TOKENS table gave the
-- seat, unchanged; game.init_tokens chops it into the 63-byte values the
-- spawn_bot init table takes and the brain splits it back apart.  The runner
-- fields no bots at all for this arena (GATE bots=0) because a bot the runner
-- fields cannot be handed any of this.
local COMMON = "cfg=RESCUE_LGM_SUPPRESS_BY_FIRE_AGE=false"
            .. ";cfg=PILL_REPOSITION_ENABLED=false"
local KEEL   = "preset=keel;cfg=BUILDER_POOL_REPAIR_LINEAR=true"
            .. ";cfg=PILL_REPOSITION_ENABLED=false"
local QUIET_ENEMY       = COMMON .. ";cfg=TANK_COMBAT_ENABLED=false"
local ALLY_BUILDER_HOME = COMMON .. ";cfg=BUILDER_POOL_ENABLED=false"
local ALLY_UNDERGUNNED  = COMMON .. ";cfg=KILL_ME_SHELL_MARGIN=90"
local P0, P1    = 0, 1
local NBOTS     = 2               -- kill_me_test.py NBOTS for this arena
local P0_INIT   = KEEL
local P1_INIT   = QUIET_ENEMY
local HANDOFF   = false     -- arena C: the driver also asked whether p0 died and
                                  -- whether a corpse reached p1
-- Team 0 is NO team on this host rather than "team zero", so two bots left on
-- it are not allies and the hand-off arena has nothing to hand off to.  p0
-- always takes team 1; p1 joins him there when it is meant to be an ally and
-- takes team 2 when it is meant to be a foe.
local P0_TEAM   = 1
local P1_ENEMY  = true      -- arenas A/B: p1 is a hostile tank
local CORPSE_ON = false     -- arena E: pill 2 becomes a 0-armour body
local BUSY_P1   = false       -- arena D1: keep pill 2 damaged so p1's man walks
local NP_ON     = true         -- is the neutral pillbox on the map at all?
local KILL_LGM  = false      -- arenas C/D1/D2: kill p0's builder outright
                                  -- (game.kill_lgm) instead of walling him in
local last_dead0 = false          -- p0's tank alive/dead edge
local wall_tick    = nil          -- the tick the gate was walled, or the man killed
local retries      = 0            -- top-ups that landed with a tank still east
local gave_n       = 0            -- pillboxes that actually went aboard p0
local p0_died      = false        -- arena C: p0 was killed after the hand-off
local corpse_to_p1 = false        -- arena C: a pillbox ended up in p1's tank
local loaded_from  = nil          -- start of the run of ticks now being counted
local loaded_best  = 0            -- longest run of loaded-and-builder-less ticks
-- The driver read the state off the brain's own LOADED_NO_LGM edges, which a
-- scenario cannot see.  The engine half of the same fact is readable: three
-- pillboxes in p0's tank and a builder whose state is anything but in_tank.
-- A run this long is a state rather than a blink -- 100 engine ticks a second,
-- so five seconds of it.
local LOADED_MIN   = 500
local GIVE_N    = 3               -- pills handed to p0 (>= LOADED_NO_LGM_MIN_PILLS)

local OURPILL   = { 130, 127 }
local CORPSE    = { 122, 126 }
local NEUTRAL   = { 124, 133 }
local SPAWN0    = { 126, 127 }
local SPAWN1    = { 122, 128 }
local GATE_X    = { 128, 129 }
local GATE_Y    = { 126, 127, 128 }
local FOREST    = 5
local RIVER     = 1
local WALL      = 0
local FILL_TICK = 120       -- doubled: the hook clock steps by 2 now
local TOPUP_ARMOUR = 11

local filled0, filled1 = false, false
local walled = false
local retry_at = nil
local REDAMAGE_AFTER = 16         -- doubled with the rest
local gave = false
local traced = nil
local idx_our, idx_corpse, idx_neutral = nil, nil, nil
local spares = {}

local function same(p, t) return p.x == t[1] and p.y == t[2] end

-- Resolve tiles to PILL INDICES once. Everything after this reads the pill BY
-- INDEX: a pill that is picked up moves with its carrier, so a coordinate
-- match would stop finding it exactly when the trace exists to prove nobody
-- took it.
local function resolve(g)
  spares = {}
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      if same(p, OURPILL)     then idx_our = i
      elseif same(p, CORPSE)  then idx_corpse = i
      elseif same(p, NEUTRAL) then idx_neutral = i
      else spares[#spares + 1] = i end
    end
  end
  return (idx_our ~= nil)
end

function on_setup(g)
  traced = resolve(g) and true or false
  for i = 1, g.num_pills() do
    if i == idx_neutral then
      g.set_pill_owner(i, g.NEUTRAL)
    else
      g.set_pill_owner(i, P0)
    end
  end
  for i = 1, g.num_bases() do
    g.set_base_owner(i, P0)
    g.set_base_stock(i, 90, 90, 90)
  end
  -- The second friendly pill is scenery in most arenas: a live pill inside the
  -- room invites defend/repair goals that have nothing to do with what is
  -- being measured.  hide_pill takes it off the map entirely.
  -- THE NEUTRAL IS A TRADE, and each arena picks its side of it.
  --   ON  : its PILL_RANGE_MAP(9) danger stamp covers every tank-reachable
  --         tile, which is what keeps rescue_lgm suppressed under the pinned
  --         static gate (perc.under_fire = danger_at(tile) > 0) once the man
  --         is stranded.  The same stamp makes threat.pill_at(tank tile) > 0,
  --         which fires haul_flee_eval's pill_shooting trigger for a tank
  --         carrying pills with its builder out -- so take_cover owns the
  --         pool at HAUL_FLOOR and the ESCAPE half of the feature is exactly
  --         what gets measured.  Arenas A, B, E, EK.
  --   OFF : nothing stamps danger, so haul_flee_eval is quiet and the
  --         kill_me_wait row can actually bid.  Arenas C, D1, D2.
  if not NP_ON and idx_neutral then g.hide_pill(idx_neutral) end
  if idx_corpse then
    if CORPSE_ON then
      -- Arena E's body is HIDDEN until the state starts. Put it on the ground
      -- at setup and the bot drives over it in the first hundred ticks, long
      -- before it is loaded and builder-less, and there is nothing left to
      -- price. show_pill puts a hidden pill back DEAD, which is exactly the
      -- state a capture wants, so the corpse appears on the wall tick.
      g.hide_pill(idx_corpse)
    elseif BUSY_P1 then
      g.set_pill_armour(idx_corpse, TOPUP_ARMOUR)   -- arena D1: p1's errand
    else
      g.hide_pill(idx_corpse)
    end
  end
  -- The spares are carry-slots, not pillboxes: off the map until the flood.
  for _, i in ipairs(spares) do g.hide_pill(i) end
end

-- The two bots are spawned here rather than fielded by the runner, because a
-- bot the runner fields gets no init table and every one of the driver's cfg
-- pins rides in that table.  on_setup's roster ops are queued by the prelude
-- and flushed at the top of on_start, so the seats come up on the round's
-- first tick.
function on_start(g)
  g.spawn_bot{ slot = P0, name = "Loaded", team = P0_TEAM, loadout = "open",
               init = g.init_tokens(P0_INIT) }
  if NBOTS > 1 then
    g.spawn_bot{ slot = P1, name = P1_ENEMY and "Foe" or "Mate",
                 team = P1_ENEMY and 2 or P0_TEAM, loadout = "open",
                 init = g.init_tokens(P1_INIT) }
  end
end

function on_choose_start(g, p)
  if p == P0 then return 1 end
  if p == P1 then return 2 end
  return nil
end

function on_tick(g, tick)
  -- ALLIANCE, APPLIED FROM on_tick.  botManagerSetTeams walks the bots'
  -- OWN ClientSim alliance tables, and at on_setup time no bot exists yet --
  -- so a set_team there reaches the server's roster and nothing else, and the
  -- two bots still read each other as OBJECT_HOSTILE (measured: arena C's
  -- would-be ally opened with `attack_tank #1`).  Re-applied for the first
  -- ALLY_TICKS ticks so it lands whenever the slots actually come up.
  -- 240, not 120: the tick this hook is handed goes up by two per frame on
  -- this host where it went up by one on the old one, so every duration in
  -- this file is doubled to mean the same stretch of game.
  if tick <= 240 then
    g.set_team(P0, P0_TEAM)
    if NBOTS > 1 then g.set_team(P1, P1_ENEMY and 2 or P0_TEAM) end
  end
  -- Fill the spawn ponds once each tank is ASHORE and off its boat. Filling
  -- the tile while the tank still sits on it leaves the boat state stuck and
  -- the LGM never becomes available.
  if tick >= FILL_TICK then
    if not filled0 then
      local tk = g.tank(P0)
      if tk and not tk.boat and not tk.dead
         and (tk.mx ~= SPAWN0[1] or tk.my ~= SPAWN0[2]) then
        filled0 = true
        g.set_tile(SPAWN0[1], SPAWN0[2], FOREST)
      end
    end
    if not filled1 then
      local tk = g.tank(P1)
      if tk and not tk.boat and not tk.dead
         and (tk.mx ~= SPAWN1[1] or tk.my ~= SPAWN1[2]) then
        filled1 = true
        g.set_tile(SPAWN1[1], SPAWN1[2], FOREST)
      end
    end
  end

  -- resolve() ran in on_setup and must not run again: hide_pill is a real
  -- remove_pill on this host, so a second sweep would find the corpse and all
  -- the spares gone and hand out nothing.  The indices taken before the hiding
  -- are the ones that count.
  if not traced then return end

  -- THE FLOOD + THE HAND-OUT.  Full armour on a pill that is still ours and
  -- not in a tank means the man is standing on (130,127), east of the gate.
  -- Both tanks have to be off the gate column on the same tick.
  -- THE FLOOD: ONE COLUMN, THE FAR ONE.
  --
  -- Fired on the exact tick the engine reports the pill full -- the man is
  -- standing on (130,127) at that instant and nowhere else, so this is the
  -- one tick where his side of the gate is known.
  --
  -- The gate is TWO columns wide and only the EAST one (x=129) is walled.
  -- That is the whole trick, and it took three drafts:
  --   * the tank's cheapest reachable tile to the errand pill is always the
  --     tile NEXT to it, so a one-column gate is a column the tank is parked
  --     on at every single completion -- and walling under a tank freezes it
  --     (MAP_SPEED_TBUILDING is 0), so that flood could never fire at all;
  --   * flooding with RIVER instead needs no guard (the tank drives on, the
  --     man cannot enter at all), but it leaves the tank able to sit ONE tile
  --     from the man, and lgm.c lgmReturn boards him from there -- measured,
  --     the man was home 160 ticks after the flood;
  --   * and walling the FAR column does not strand him either: a live pillbox
  --     is MANSPEED 0, so the man never stands ON the errand pill -- he stands
  --     BESIDE it, on the far gate column, and a wall laid under his feet is a
  --     wall he simply steps west out of.
  -- So the NEAR column (x=128) is the one that gets walled, which leaves the
  -- man loose in the four-tile pocket east of it (the far column plus the pill
  -- tile) with no way out and no way for a tank to reach him.
  --
  -- The guard is therefore "neither tank is east of the room", and when it
  -- fails the pill goes back down to TOPUP_ARMOUR so the pool sends the man
  -- out again and the next completion is another attempt.
  -- THE KILL (arenas C/D1/D2). game.kill_lgm puts p0's man through the
  -- engine's own death path (lgm.c lgmDeathCheckAtPosition): he is choppered
  -- in from a start tile and walks home, exactly as a shell would have left
  -- him. Re-applied every tick afterwards so he dies again the moment he
  -- lands: the arena is seven tiles wide and one death would only buy a few
  -- hundred ticks of the state. The first kill flips `walled`, which is the
  -- latch the hand-out below already waits on.
  if KILL_LGM and traced and filled0 and filled1 and tick >= FILL_TICK + 200 then
    local killed = g.kill_lgm(P0)
    if killed and not walled then
      walled = true
      wall_tick = tick
      g.message(string.format("KILL_ME_B: p0's builder killed at t=%d", tick))
    end
  end
  local p = idx_our and g.pill(idx_our)
  if not KILL_LGM and p and not walled and p.armour >= 15 and not p.in_tank and p.owner == P0 then
    local t0 = g.tank(P0)
    local t1 = g.tank(P1)
    local clear0 = (not t0) or t0.dead or t0.mx < GATE_X[1]
    local clear1 = (not t1) or t1.dead or t1.mx < GATE_X[1]
    if clear0 and clear1 then
      walled = true
      for _, gy in ipairs(GATE_Y) do
        g.set_tile(GATE_X[1], gy, WALL)
      end
      wall_tick = tick
      g.message(string.format(
        "KILL_ME_B: gate column x=%d walled at t=%d -- p0's man is cut off",
        GATE_X[1], tick))
    else
      retry_at = retry_at or (tick + REDAMAGE_AFTER)
      if tick >= retry_at then
        g.set_pill_armour(idx_our, TOPUP_ARMOUR)
        retry_at = nil
        retries = retries + 1
      end
    end
  end

  -- KEEP THE WALL UP. A BUILDING tile is not permanent: a shell that misses
  -- chews it to HALFBUILDING and then to RUBBLE, and both tanks spend the run
  -- firing in a seven-tile room. Re-stamping the column every tick costs
  -- nothing and stops a stray round from re-opening the pocket halfway
  -- through the measurement (measured: the man was loose again 400 sim ticks
  -- after the wall went up).
  if walled and not KILL_LGM then
    for _, gy in ipairs(GATE_Y) do
      g.set_tile(GATE_X[1], gy, WALL)
    end
  end

  -- The pills go aboard on the flood tick, never before: hand them over early
  -- and the bot places them instead of carrying them, and the errand that
  -- walks the man out never happens at all.
  if walled and not gave then
    gave = true
    local n = 0
    for _, i in ipairs(spares) do
      if n < GIVE_N then
        -- show_pill puts a hidden pill back where it was hidden, DEAD; that
        -- tile is a walled-in road square nothing can reach, so the pill
        -- exists on the map only for the instant between these two calls.
        g.show_pill(i)
        g.set_pill_owner(i, P0)
        if g.give_pill(P0, i) then n = n + 1 else g.hide_pill(i) end
      end
    end
    -- Arena E: the body appears now, with the state, not at setup.
    if CORPSE_ON and idx_corpse then
      g.show_pill(idx_corpse)
      g.set_pill_owner(idx_corpse, P0)
    end
    gave_n = n
    g.message(string.format("KILL_ME_B: %d pillbox(es) loaded into p0 at t=%d",
                            n, tick))
  end

  -- Arena D1 only: keep p1's errand alive so its builder keeps walking, which
  -- is what makes the responder row read no_lgm.
  if BUSY_P1 and idx_corpse then
    local c = g.pill(idx_corpse)
    if c and c.armour >= 15 and not c.in_tank then
      g.set_pill_armour(idx_corpse, TOPUP_ARMOUR)
    end
  end

  -- WHAT THE ENGINE SAYS ABOUT THE STATE.  The driver read the brain's own
  -- LOADED_NO_LGM edges out of print2 to prove the state was real; a scenario
  -- cannot see print2, so the same fact is taken off the engine -- three
  -- pillboxes aboard and a builder who is not in the tank -- and the longest
  -- unbroken run of it is what the verdict asks for.
  local t0d = g.tank(P0)
  if wall_tick then
    local bd = g.builder(P0)
    if t0d and not t0d.dead and (t0d.pills or 0) >= GIVE_N
       and bd and bd.state ~= "in_tank" then
      loaded_from = loaded_from or tick
      local run = tick - loaded_from
      if run > loaded_best then loaded_best = run end
    else
      loaded_from = nil
    end
  end

  -- p0's alive/dead edge, watched in every arena: it is one of arena C's two
  -- world clauses, and everywhere else it is what a short state is explained
  -- by, so the failing verdict can say which of the two happened.
  if t0d and (t0d.dead and true or false) ~= last_dead0 then
    last_dead0 = t0d.dead and true or false
    if last_dead0 and wall_tick then p0_died = true end
  end
  -- Arena C's other clause: a corpse changed hands.  Everything else the
  -- driver asked of arena C is a line in the brain's log.
  if HANDOFF then
    if not corpse_to_p1 then
      for i = 1, g.num_pills() do
        local q = g.pill(i)
        if q and q.in_tank and q.owner == P1 then corpse_to_p1 = true break end
      end
    end
  end
end

-- ── the verdict ─────────────────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/kill_me_test.py, and only the part of it a
-- scenario can reach.  That driver's step 0 -- `the_state_is_real` -- is the
-- whole of what is asked here: the engine walled the gate (or killed the man),
-- three pillboxes went into p0's tank on the same tick, and p0 then stood
-- loaded and builder-less for a real stretch.  Arena C adds the two world
-- clauses of its own check: p0 died, and a pillbox ended up in p1's tank.
--
-- LEFT BEHIND, because a scenario cannot read the brain's print2 log: every
-- assertion about what the bot PRICED.  Arena A's nobuild=10 term on the
-- attack rows and the rows losing the pick with it; arena A/B's
-- hyst=none:no_lgm waiver, and B's proof that preset=keel has neither;
-- arena C's kill_me_wait bid, KILL_ME_ROW and KILL_ME_STEER; arenas D1/D2's
-- no_lgm and low_shells reject reasons; arenas E/EK's CAPTURE_NO_LGM terms and
-- the E-against-EK price comparison.  Moving those needs the brain to publish
-- its scoring somewhere the engine can be asked about it.
VERDICT_CHECK = function(g)
  if wall_tick == nil then
    return false, string.format(
      "the man was never cut off: %d top-up(s) landed with a tank still east",
      retries)
  end
  if gave_n ~= GIVE_N then
    return false, string.format("cut off at t=%d but %d pill(s) aboard, not %d",
                                wall_tick, gave_n, GIVE_N)
  end
  if loaded_best < LOADED_MIN then
    return false, string.format(
      "cut off t=%d, but loaded+builderless only %d ticks (want %d), p0 died=%s",
      wall_tick, loaded_best, LOADED_MIN, tostring(p0_died))
  end
  if HANDOFF then
    if not p0_died then
      return false, string.format("state held %d ticks but p0 was never killed",
                                  loaded_best)
    end
    if not corpse_to_p1 then
      return false, "p0 died but no corpse ever reached p1's tank"
    end
    return true, string.format("state %d ticks, p0 died, a corpse reached p1",
                               loaded_best)
  end
  return true, string.format("cut off t=%d, %d aboard, state held %d ticks",
                             wall_tick, gave_n, loaded_best)
end
