-- Scenario sidecar for tests/mine_hoard_A.map -- GENERATED by
-- tests/generate_mine_hoard_map.py, do not edit by hand.
--
-- Stages a tank that is PARKED on its own base, still below a target, and
-- carrying 23 mines -- the shape of the 20260905_231835 bot2 incident --
-- then hands it to the variant.
--
-- The engine refuels armour, THEN shells, THEN mines (bases.c basesRefueling),
-- one item per half-tick, and there is no set_tank_stock in the scenario API.
-- So the only way to a mine-heavy tank that is NOT full of shells is to take
-- the PAD's shells away and let the mine branch run.  Phases:
--
--   1 SHELLS  pad (90, 90, 0) until the tank holds 20 shells
--             (20 == SHELLS_LOW, pinned by cfg: fill 0, mult 1.00,
--             deficit bonus 0, so the printed refuel cost is the bare cached
--             cost and the mine surcharge is the only moving part).
--   2 MINES   pad (90, 0, 90); shells held at 0 so the engine's shell
--             branch is skipped and mines flow.  Until the tank holds 23.
--   3 FREEZE  pad (90, 0, 0), held 1000 ticks.  Nothing moves: the
--             tank sits on the pad at armour 40 / shells 20 / mines
--             23.  The pad still has ARMOUR (90 raw = 18 in the
--             engine's brain units, bases.c basesGetBrainBaseItem divides by
--             five) and the bot's armour target is 45 (cfg=TANK_FULL_ARMOUR),
--             so the pad can still supply something the tank is short of.
--   4 TEST    variant A: pad restocked to (90, 90, 0) -- it can still feed the tank
--
-- THE FAR BASE (136,122) IS HELD FULL THROUGHOUT, in every phase.  It is
-- the competing goal: while the tank is parked on the pad it costs
-- travel + REFUEL_BASE_COST + REFUEL_BASE_HOP_PENALTY(500), which loses to a
-- waived pad and beats a mine-charged one.
--
-- The engine regenerates base stock on its own (bases.c basesUpdateStock), so
-- every phase RE-ASSERTS stock whenever it has crept -- only when it actually
-- changed, or the log is one base-stock event per tick.
--
-- NOTE these are ENGINE ticks.  on_tick counts engine ticks and a brain thinks
-- every second one, so everything here is twice the number the brain's own t=
-- shows.  The host on main steps this hook's tick by two per frame where the
-- old one stepped it by one, so every duration in this file was doubled when
-- it was ported: FREEZE 500 -> 1000 and the pond guard 200 -> 400 are the same
-- stretches of game they always were.
--
-- GATE: ticks=2800 bots=0 gametype=tournament ai=yesfull limit=20
--
-- Also: pin the starts (on_choose_start fires for every placement, so player p
-- always gets start p+1), and fill the one-tile spawn ponds once every tank is
-- ashore -- a start square has to be DEEP SEA, and a tank that later drives
-- over one without a boat drowns instantly.
local FULL      = 90
local SHELLS    = 20
local MINES     = 23
local OWNER     = 0
local FREEZE    = 1000      -- doubled: the hook clock steps by 2 on this host
local PADX      = 126
local PADY      = 122
local PONDS     = { { 126, 118 }, { 96, 112 } }
local GRASS     = 7
local VARIANT   = "A"
local ponds_filled = false
local phase        = 1
local freeze_tick  = -1

-- THE DRIVER'S -bot-init PINS.  mine_hoard_test.py's CFG_TOKENS, unchanged,
-- for the run it calls "A" -- the default, the fix.  The keel control it calls
-- "AK" adds cfg=REFUEL_MINE_HOARD_NEEDS_SUPPLY=false and has no arena of its
-- own, so A-against-AK cannot be run from here at all; see the verdict's note.
-- game.init_tokens chops the string into the 63-byte values a spawn_bot init
-- table takes, and the brain splits it back apart.  The runner fields no bots
-- (GATE bots=0) because a bot the runner fields gets no init table.
local CFG_TOKENS = "cfg=REFUEL_BASELINE_SHELLS=40"
                .. ";cfg=SHELLS_LOW=20"
                .. ";cfg=TANK_FULL_ARMOUR=45"
-- The other tank, as the driver fielded it: a scripted patroller, so the pad
-- is priced against a live hostile the way it was in the incident.  The path
-- is relative to the server's working directory, which is the build directory.
local FOE_BRAIN = "../tests/brains/patrol_ns.lua"

-- min(REFUEL_BASELINE_SHELLS 40, TANK_FULL_SHELLS 40), which is also the
-- engine's ceiling, so "reached its shell target" is a full rack.
local SHELL_TARGET = 40
local staged_tick  = nil    -- first tick parked on the pad in the staged state
local left_tick    = nil    -- first tick off the pad after that
local target_tick  = nil    -- first tick on the pad at the shell target
-- Which base is the pad?  Matched on coordinates, not on index, so a change to
-- the map's base order cannot silently point the staging at the wrong one.
local function is_pad(b) return b.x == PADX and b.y == PADY end
-- Set the pad outright.  `mines` may be nil for "leave the pad's mines alone"
-- (phase 2 lets the tank drain them and must not fight it).
local function set_pad(g, armour, shells, mines)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b and is_pad(b) then
      g.set_base_stock(i, armour, shells, mines or (b.mines or 0))
    end
  end
end
-- Re-assert the pad and hold every OTHER base full, but only where the stock
-- has actually drifted -- the server emits EVENT_BASE_STOCK on every write and
-- an unconditional re-assert would be one event per tick.
local function hold(g, armour, shells, mines)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      local wa, ws, wm
      if is_pad(b) then
        wa, ws, wm = armour, shells, mines
      else
        wa, ws, wm = FULL, FULL, 0
      end
      local drift = (b.armour or 0) ~= wa or (b.shells or 0) ~= ws
      if wm ~= nil and (b.mines or 0) ~= wm then drift = true end
      if drift then g.set_base_stock(i, wa, ws, wm or (b.mines or 0)) end
    end
  end
end
function on_choose_start(g, p)
  local n = p + 1
  if n >= 1 and n <= g.num_starts() then return n end
  return nil
end
-- The bot the driver measured is spawned here rather than fielded by the
-- runner: a runner-fielded bot gets no init table, and every cfg pin above
-- rides in that table.  on_setup's roster ops are queued by the prelude and
-- flushed at the top of on_start, so the seats come up on the first tick --
-- after on_setup has taken every base, which is what makes the TOURNAMENT
-- loadout hand out 0 shells and 0 mines (gametype.c gameTypeGetItems draws the
-- shell allowance from the NEUTRAL share of the bases, and there is none).
function on_start(g)
  g.spawn_bot{ slot = 0, name = "Hoarder", loadout = "tournament",
               init = g.init_tokens(CFG_TOKENS) }
  g.spawn_bot{ slot = 1, name = "Patrol", loadout = "tournament",
               brain = FOE_BRAIN }
end

function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      g.set_base_stock(i, FULL, FULL, 0)
      g.message(string.format(
        "MINE_HOARD_ARENA base#%d (%d,%d) owner=%d armour=%d shells=%d mines=0 %s",
        i, b.x, b.y, OWNER, FULL, FULL, is_pad(b) and "PAD" or "FAR"))
    end
  end
  g.message(string.format(
    "MINE_HOARD_ARENA variant=%s pills=%d bases=%d starts=%d stage_shells=%d stage_mines=%d",
    VARIANT, g.num_pills(), g.num_bases(), g.num_starts(), SHELLS, MINES))
end
function on_tick(g, tick)
  local t = g.tank(0)
  if phase == 1 then
    -- Armour is already full (TOURNAMENT spawns at the engine's 40), so the
    -- engine pours shells.  Mines stay 0 in the pad: the tank must not pick
    -- any up before it is holding exactly SHELLS shells.
    hold(g, FULL, FULL, 0)
    if t and (t.shells or 0) >= SHELLS then
      phase = 2
      set_pad(g, FULL, 0, FULL)
      g.message(string.format(
        "MINE_HOARD_ARENA PHASE2_MINES tick=%d tank sh=%d mn=%d",
        tick, t.shells or -1, t.mines or -1))
    end
  elseif phase == 2 then
    -- Shells held at 0 (blocks the engine's shell branch); the pad's mines are
    -- left alone so the tank can actually drain them.
    hold(g, FULL, 0, nil)
    if t and (t.mines or 0) >= MINES then
      phase = 3
      freeze_tick = tick
      set_pad(g, FULL, 0, 0)
      g.message(string.format(
        "MINE_HOARD_ARENA PHASE3_FREEZE tick=%d tank arm=%d sh=%d mn=%d",
        tick, t.armour or -1, t.shells or -1, t.mines or -1))
    end
  elseif phase == 3 then
    hold(g, FULL, 0, 0)
    if tick >= freeze_tick + FREEZE then
      phase = 4
      if VARIANT == "A" then
        -- The pad can supply the shells the tank is short of.
        set_pad(g, FULL, FULL, 0)
        g.message("MINE_HOARD_ARENA PHASE4_RESTOCK tick=" .. tostring(tick))
      else
        -- Nothing left but mines.
        set_pad(g, 0, 0, FULL)
        g.message("MINE_HOARD_ARENA PHASE4_DRY tick=" .. tostring(tick))
      end
    end
  else
    if VARIANT == "A" then
      hold(g, FULL, FULL, 0)
    else
      hold(g, 0, 0, nil)
    end
  end
  -- What the verdict watches.  The pad reading is the tank's own square, so
  -- it costs two comparisons a tick and never sweeps anything.
  if t and not t.dead then
    local on_pad = (t.mx == PADX and t.my == PADY)
    if on_pad and (t.shells or 0) == SHELLS and (t.mines or 0) == MINES then
      staged_tick = staged_tick or tick
    end
    if staged_tick then
      if not on_pad then
        left_tick = left_tick or tick
      elseif (t.shells or 0) >= SHELL_TARGET then
        target_tick = target_tick or tick
      end
    end
  end

  if not ponds_filled and tick > 400 then
    local afloat = false
    for p = 0, g.max_tanks() - 1 do
      local tk = g.tank(p)
      if tk and tk.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("MINE_HOARD_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end

-- ── the verdict ─────────────────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/mine_hoard_test.py check 6, the default half,
-- which is the only check of that driver a scenario can reach: it is the one
-- read off the engine's own position and shell count rather than off a
-- REFUEL_SHAPE line in the brain's debug log.  The tank must stage on the pad
-- at 20 shells and 23 mines, and then, with the pad restocked, fill to its
-- shell target WITHOUT leaving the pad first -- which is what the waived mine
-- surcharge buys and what the incident did not do.
--
-- LEFT BEHIND: checks 1, 3, 4 and 5 are all about the printed mines{} chip --
-- its exponential re-derived from its own numbers, its WAIVED/CHARGED verdict
-- re-decided from its own inputs, and the tick-paired comparison against the
-- keel control.  None of that leaves a mark on the world.  The keel control is
-- doubly out of reach: mine_hoard_test.py's AK run is this same arena with one
-- more cfg token, and an arena file is one configuration, so there is no
-- second arena here to be the control.  Giving this family a real A-against-AK
-- would mean a second arena file, mine_hoard_AK, whose only difference is
-- cfg=REFUEL_MINE_HOARD_NEEDS_SUPPLY=false in CFG_TOKENS.
VERDICT_CHECK = function(g)
  if staged_tick == nil then
    return false, string.format("never staged on the pad at sh=%d mn=%d",
                                SHELLS, MINES)
  end
  if left_tick ~= nil and (target_tick == nil or left_tick < target_tick) then
    return false, string.format("left the pad at t=%d before sh=%d",
                                left_tick, SHELL_TARGET)
  end
  if target_tick == nil then
    return false, string.format("staged t=%d but never reached sh=%d on the pad",
                                staged_tick, SHELL_TARGET)
  end
  return true, string.format("staged t=%d, filled to sh=%d at t=%d, never left",
                             staged_tick, SHELL_TARGET, target_tick)
end
