-- Scenario script for tests/place_pin_far.map -- GENERATED by
-- tests/generate_place_pin_map.py, do not edit by hand.
--
-- Four jobs.
--
-- 1. OWN the base and all three pills, and put our tank on its own team so the
--    scripted opponents are hostile to it.
--
-- 2. PIN THE STARTS.  on_choose_start fires for every placement (spawn AND
--    respawn), so each tank always comes back on the pond this arena designed
--    for it -- start 1 ours, start 2 the patrol.
--
-- 3. HAND OVER THE PILLS at tick 200.  Three aboard is what makes the
--    carry pressure real: place_pill_strategic's cost collapses, and whether
--    it is allowed to WIN with that cost is the whole question.
--
-- 4. FILL THE SPAWN PONDS once nobody is afloat.  A start square has to be
--    deep sea, and a tank that later drives over one without a boat drowns --
--    noise this test does not want.

local OUR_PLAYER = 0
local PILL_IDS   = { 1, 2, 3 }
local PONDS      = { { 138, 126 }, { 126, 112 } }
-- Doubled from the 200 this file carried: the clock the host counts in went
-- from 50 a second to 100, so the old number is half the wait it was written
-- to be. The pond fill below is doubled with it, for the same reason.
local GIVE_TICK  = 400
local POND_TICK  = 400
local GRASS      = 7
local given = false
local ponds_filled = false
local start_tiles = nil          -- where the map's pills stood before the round

function on_setup(g)
  -- Every tile that already had a pillbox on it. A pill standing anywhere else
  -- at the end of the round is one this bot put there, which is what the
  -- verdict at the foot of this file asks for.
  start_tiles = {}
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then start_tiles[p.x * 256 + p.y] = true end
  end
  for i = 1, g.num_pills() do g.set_pill_owner(i, OUR_PLAYER) end
  for i = 1, g.num_bases() do g.set_base_owner(i, OUR_PLAYER) end
  g.set_team(OUR_PLAYER, 0)
  g.message(string.format("PLACE_PIN_ARENA pills=%d give=%d",
                          g.num_pills(), GIVE_TICK))
end

function on_choose_start(g, p)
  if p == 0 then return 1 end      -- ours
  if p == 1 then return 2 end      -- the patrol
  return nil
end

function on_tick(g, tick)
  if not given and tick >= GIVE_TICK then
    given = true
    local n = 0
    for _, i in ipairs(PILL_IDS) do
      local ok, err = g.give_pill(OUR_PLAYER, i)
      if ok then n = n + 1
      else g.message("PLACE_PIN_ARENA give_pill#" .. i .. " failed: "
                     .. tostring(err)) end
    end
    g.message("PLACE_PIN_ARENA gave " .. n .. " pill(s) at tick " .. tick)
  end
  if not ponds_filled and tick > POND_TICK then
    local afloat = false
    for p = 0, 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("PLACE_PIN_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end

-- ── the verdict ───────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/place_pin_range_test.py, the `far` half of
-- check 4 that is world state: a pill really does go into the ground. The
-- driver read it off the final-state JSON the same way -- a pillbox standing,
-- not carried, on a tile that had none when the round began. Under the old rule
-- the far patrol pinned every placement instead and the bot died carrying all
-- of them, which is the incident the whole arena is about.
--
-- LEFT BEHIND: checks 1, 2 and 3, and the other half of 4. The `nopin` verdict
-- itself, the distance it names, and a pinned row totalling the cheapest
-- attack_tank cost plus one are all chips on goals.lua's FINAL_SCORES line,
-- which a scenario cannot see. So this says the placement happened; it does not
-- say the pin was asked and answered no.
--
-- NOTE the foe. The driver ran the second seat on tests/brains/patrol_ns.lua, a
-- scripted patrol that never fires. The gate has no -bot-init, so the second
-- seat is another GoalHunter that hunts. The lane still keeps it well outside
-- the 7-tile pin range of our base, which is what `far` is for.
--
-- GATE: ticks=8000 bots=2 ai=yesfull gametype=open

VERDICT_CHECK = function(g)
  local placed = 0
  local carried = 0
  for n = 1, g.num_pills() do
    local p = g.pill(n)
    if p then
      if p.in_tank then
        carried = carried + 1
      elseif not start_tiles[p.x * 256 + p.y] then
        placed = placed + 1
      end
    end
  end
  if placed > 0 then
    return true, string.format("%d pill(s) put into new ground, %d still aboard",
                               placed, carried)
  end
  return false, string.format("no pill was placed; %d still aboard", carried)
end
