-- Scenario script for tests/refuel_pad_reach_A.map -- GENERATED by
-- tests/generate_refuel_pad_reach_map.py, do not edit by hand.
--
-- Two jobs.
--
-- 1. OWN BOTH BASES AND KEEP THEM FULL.  They are already slot 0's in the
--    map file, but on_setup re-asserts it so the intent lives in one place.
--    Both hold armour 90 / shells 90: neither is ever rejected as low
--    on stock and neither carries a low-stock markup, so travel and the DANGER
--    term are the only things telling the two bases apart -- which is the whole
--    point of the arena.  Re-asserted every 150 ticks with a mines value
--    that alternates 90/89, because the server only emits EVENT_BASE_STOCK when
--    a base's stock actually CHANGES and the bot's observation has to stay
--    fresh (and topped back up while the tank drinks).
--
-- 2. FILL THE SPAWN PONDS once both tanks are ashore.  A start square has to be
--    DEEP SEA (starts.c startsIsValidSquare), so the arena has two one-tile
--    ponds sitting in grass.  A tank that later drives over one without a boat
--    drowns instantly -- noise this test does not want.
-- THE CLOCK DOUBLED. This host counts 100 ticks a second where the one these
-- arenas were written on counted 50, so every number below that means a
-- DURATION is twice what the file used to carry. The re-assert is also off the
-- modulo it used: game.tick() is even for a whole round or odd for a whole
-- round, so `tick % PERIOD == 0` against an even PERIOD fires on every other
-- round and never on the rest.
local FULL   = 90
local OWNER  = 0
local PERIOD = 300               -- doubled: 150 of the old host's ticks
local PONDS  = { { 126, 118 }, { 96, 112 } }
local GRASS  = 7
local flip = 0
local next_assert = PERIOD
local ponds_filled = false
local function assert_stock(g)
  flip = 1 - flip
  local mines = 90 - flip
  for i = 1, g.num_bases() do
    g.set_base_stock(i, FULL, FULL, mines)
  end
end
function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      g.set_base_stock(i, FULL, FULL, 90)
      g.message(string.format(
        "REFUEL_PAD_ARENA base#%d (%d,%d) owner=%d armour=%d shells=%d",
        i, b.x, b.y, OWNER, FULL, FULL))
    end
  end
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      g.message(string.format(
        "REFUEL_PAD_ARENA pill#%d (%d,%d) owner=%s health=%s",
        i, p.x, p.y, tostring(p.owner), tostring(p.armour)))
    end
  end
end
function on_tick(g, tick)
  if tick >= next_assert then
    next_assert = tick + PERIOD
    assert_stock(g)
  end
  if not ponds_filled and tick > 400 then
    local afloat = false
    for p = 0, 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("REFUEL_PAD_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end

-- THE LOADOUT IS THE ARENA. The driver ran this map with `-gametype tournament
-- -ranked`, the only pair of flags that puts 0 shells in the tank, and an empty
-- tank is the whole reason the bot has to go and refuel. The gate passes no
-- -ranked, and a map with a scenario beside it is committed as gameScripted,
-- which hands out a full Open tank. So the same thing is said through the
-- host's own hook instead. Every base here is owned before the tanks are built,
-- so the tournament loadout's neutral share is 0 and so are its shells
-- (gametype.c gameTypeGetItems); mines and trees are 0 in that game too.
function spawn_loadout(g, p)
  return "tournament"
end

-- ── the verdict ─────────────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/refuel_pad_reach_test.py variant A, checks 1
-- and 7: the tank spawns dry and it refuels AT BASE_NEAR -- it stands on that
-- base and its shells rise while it is there. Under the incident's behaviour
-- the pill nine tiles south priced BASE_NEAR out of reach and the tank drove
-- twelve tiles to BASE_FAR instead, so which base it drank at is the outcome
-- the rule decides and the one thing about it the world records.
--
-- The two bases are told apart at run time rather than by coordinate: NEAR is
-- the one the pillbox is nearest to. That is what makes it near.
--
-- LEFT BEHIND, checks 2 to 6, which are the rule: every BASE_NEAR row being
-- padsafe, one of them naming the pill at 9.0 tiles against the 8.71 threshold,
-- a padcut proving there was pill danger to remove, the danger term landing on
-- exactly 0, and BASE_NEAR pricing below BASE_FAR. Those are REFUEL_P1 chips
-- and a scenario cannot see them. So this says the tank drank at the near base;
-- it does not say the pad danger came off the price.
--
-- GATE: ticks=3000 bots=2 ai=yesfull gametype=tournament

local spawn_sh = nil
local last_sh  = nil
local near_b, far_b = nil, nil   -- base tiles, resolved on the first tick
local drank_at = nil             -- "near" or "far"

local function resolve_bases(g)
  local pill = nil
  for n = 1, g.num_pills() do
    local p = g.pill(n)
    if p then pill = p break end
  end
  local best, best_d = nil, nil
  local all = {}
  for n = 1, g.num_bases() do
    local b = g.base(n)
    if b then
      all[#all + 1] = { b.x, b.y }
      if pill then
        local d = math.abs(b.x - pill.x) + math.abs(b.y - pill.y)
        if best_d == nil or d < best_d then best, best_d = #all, d end
      end
    end
  end
  if best == nil or #all < 2 then return end
  near_b = all[best]
  for i = 1, #all do
    if i ~= best then far_b = all[i] break end
  end
end

do
  local arena_tick = on_tick
  on_tick = function(g, tick)
    arena_tick(g, tick)
    if near_b == nil then resolve_bases(g) end
    local t = g.tank(0)
    if t and not t.dead then
      if spawn_sh == nil then spawn_sh = t.shells end
      if drank_at == nil and last_sh ~= nil and t.shells > last_sh and near_b then
        if t.mx == near_b[1] and t.my == near_b[2] then drank_at = "near"
        elseif far_b and t.mx == far_b[1] and t.my == far_b[2] then drank_at = "far" end
      end
      last_sh = t.shells
    end
  end
end

VERDICT_CHECK = function(g)
  if spawn_sh == nil then return false, "the tank never appeared" end
  if spawn_sh ~= 0 then
    return false, string.format("spawned on %d shells, not 0: no tournament loadout",
                                spawn_sh)
  end
  if near_b == nil then return false, "could not tell the two bases apart" end
  if drank_at == nil then return false, "the tank refuelled at neither base" end
  if drank_at ~= "near" then
    return false, string.format("it drank at the far base %d,%d, not the near one",
                                far_b[1], far_b[2])
  end
  return true, string.format("dry spawn, refuelled at the near base %d,%d",
                             near_b[1], near_b[2])
end
