-- Scenario script for tests/refuel_lowstock.map -- GENERATED by
-- tests/generate_refuel_lowstock_map.py, do not edit by hand.
--
-- Three jobs.
--
-- 1. OWN BOTH BASES, and set their stock.  The bases are already written into
--    the map file as slot 0's, but on_setup re-asserts it so the intent is
--    in one place -- and it is the only place the stock lives:
--      BASE_NEAR  armour 4 (below REFUEL_MIN_STOCK -> marked up),
--                 shells 6  (at/above it -> survives the low_stock reject)
--      BASE_FAR   armour 90 shells 90
--
-- 2. KEEP THE STOCK READING FRESH.  The markup only prices a base whose
--    observation is younger than REFUEL_OBS_STALE (500 ticks), and a bot only
--    learns base stock from EVENT_BASE_STOCK, which the server emits ONLY when
--    a base's armour/shells/mines actually CHANGE.  So every 150 ticks this
--    re-asserts the stock with a mines value that alternates 90/89 -- a real
--    change, so a real event.  It also puts the stock back, which is
--    deliberate: the near base has to stay pinned even while the tank drinks.
--
-- 3. FILL THE SPAWN PONDS once both tanks are ashore.  A start square has to
--    be DEEP SEA (starts.c startsIsValidSquare), so the arena has two one-tile
--    ponds sitting in grass.  A tank that later drives over one without a boat
--    drowns instantly -- noise this test does not want -- so once neither tank
--    is afloat the ponds become grass.
-- THE CLOCK DOUBLED. This host counts 100 ticks a second where the one these
-- arenas were written on counted 50, so every number below that means a
-- DURATION is twice what the file used to carry. The re-assert is also off the
-- modulo it used: game.tick() is even for a whole round or odd for a whole
-- round, so `tick % PERIOD == 0` against an even PERIOD fires on every other
-- round and never on the rest.
local NEAR   = { 120, 131 }
local FAR    = { 120, 118 }
local FULL   = 90
local NEAR_SH  = 6
local NEAR_ARM = 4
local OWNER  = 0
local PERIOD = 300               -- doubled: 150 of the old host's ticks
local PONDS  = { { 126, 127 }, { 110, 112 } }
local GRASS  = 7
local flip = 0
local next_assert = PERIOD
local ponds_filled = false
-- armour, shells for one base.  BASE_NEAR is the only one that varies.
local function stock_for(b)
  if b.x == NEAR[1] and b.y == NEAR[2] then return NEAR_ARM, NEAR_SH end
  return FULL, FULL
end
local function assert_stock(g)
  flip = 1 - flip
  local mines = 90 - flip
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      local arm, sh = stock_for(b)
      g.set_base_stock(i, arm, sh, mines)
    end
  end
end
function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      local arm, sh = stock_for(b)
      g.set_base_stock(i, arm, sh, 90)
      g.message(string.format(
        "REFUEL_LOWSTOCK_ARENA base#%d (%d,%d) owner=%d armour=%d shells=%d",
        i, b.x, b.y, OWNER, arm, sh))
    end
  end
end
function on_tick(g, tick)
  if tick >= next_assert then
    next_assert = tick + PERIOD
    assert_stock(g)
  end
  -- Fill the ponds as soon as nobody is afloat any more (see note 3).
  if not ponds_filled and tick > 400 then
    local afloat = false
    for p = 0, 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("REFUEL_LOWSTOCK_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end

-- THE LOADOUT IS THE ARENA. The driver ran this map with `-gametype tournament
-- -ranked`, the only pair of flags that puts 0 shells in the tank, and an empty
-- tank is the whole reason the bot has to go and refuel. The gate passes no
-- -ranked, and a map with a scenario beside it is committed as gameScripted,
-- which hands out a full Open tank. So the same thing is said through the
-- host's own hook instead. Every base here is owned before the tanks are built,
-- so the tournament loadout's neutral share is 0 and so are its shells
-- (gametype.c gameTypeGetItems); mines and trees are 0 in that game too.
function spawn_loadout(g, p)
  return "tournament"
end

-- ── the verdict ─────────────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/refuel_lowstock_test.py, check 1 -- the part
-- of it that is world state -- and the outcome the markup is there to decide.
-- The tank spawns dry, the hidden mine in the gap really does fire and take its
-- armour below full, and it goes and drinks at one of the two bases. Which base
-- it picked is reported, not demanded; the driver did not demand a winner
-- either, since a 10% markup need not beat five tiles.
--
-- LEFT BEHIND, and it is the rule itself: checks 2, 3 and 4. That BASE_NEAR
-- carries exactly one ` lowarm{x1.10}` chip once armour is needed, none before
-- it, none on BASE_FAR, and that the pick follows the two priced costs. All of
-- that is on goals.lua's REFUEL_P1 rows, which a scenario cannot see. A tank
-- that refuels says nothing about what the row it chose cost.
--
-- GATE: ticks=3000 bots=2 ai=yesfull gametype=tournament

local FULL_ARMOUR = 40           -- the engine's own, and what a tank spawns on
local spawn_sh = nil
local min_arm  = nil
local last_sh  = nil
local drank_at = nil             -- "near" or "far"

do
  local arena_tick = on_tick
  on_tick = function(g, tick)
    arena_tick(g, tick)
    local t = g.tank(0)
    if t and not t.dead then
      if spawn_sh == nil then spawn_sh = t.shells end
      if min_arm == nil or t.armour < min_arm then min_arm = t.armour end
      if drank_at == nil and last_sh ~= nil and t.shells > last_sh then
        if t.mx == NEAR[1] and t.my == NEAR[2] then drank_at = "near"
        elseif t.mx == FAR[1] and t.my == FAR[2] then drank_at = "far" end
      end
      last_sh = t.shells
    end
  end
end

VERDICT_CHECK = function(g)
  if spawn_sh == nil then return false, "the tank never appeared" end
  if spawn_sh ~= 0 then
    return false, string.format("spawned on %d shells, not 0: no tournament loadout",
                                spawn_sh)
  end
  if min_arm == nil or min_arm >= FULL_ARMOUR then
    return false, string.format("armour never fell below %d: the mine never fired",
                                FULL_ARMOUR)
  end
  if drank_at == nil then
    return false, string.format("never refuelled at either base (armour fell to %d)",
                                min_arm)
  end
  return true, string.format("dry spawn, mine took it to %d, drank at the %s base",
                             min_arm, drank_at)
end
