-- Scenario sidecar for tests/refuel_pad_reach_B.map -- GENERATED by
-- tests/generate_refuel_pad_reach_map.py, do not edit by hand.
--
-- Two jobs.
--
-- 1. OWN BOTH BASES AND KEEP THEM FULL.  They are already slot 0's in the
--    map file, but on_setup re-asserts it so the intent lives in one place.
--    Both hold armour 90 / shells 90: neither is ever rejected as low
--    on stock and neither carries a low-stock markup, so travel and the DANGER
--    term are the only things telling the two bases apart -- which is the whole
--    point of the arena.  Re-asserted every 150 ticks with a mines value
--    that alternates 90/89, because the server only emits EVENT_BASE_STOCK when
--    a base's stock actually CHANGES and the bot's observation has to stay
--    fresh (and topped back up while the tank drinks).
--
-- 2. FILL THE SPAWN PONDS once both tanks are ashore.  A start square has to be
--    DEEP SEA (starts.c startsIsValidSquare), so the arena has two one-tile
--    ponds sitting in grass.  A tank that later drives over one without a boat
--    drowns instantly -- noise this test does not want.
-- THE CLOCK DOUBLED. This host counts 100 ticks a second where the one these
-- arenas were written on counted 50, so every number below that means a
-- DURATION is twice what the file used to carry. The re-assert is also off the
-- modulo it used: game.tick() is even for a whole round or odd for a whole
-- round, so `tick % PERIOD == 0` against an even PERIOD fires on every other
-- round and never on the rest.
local FULL   = 90
local OWNER  = 0
local PERIOD = 300               -- doubled: 150 of the old host's ticks
local PONDS  = { { 126, 118 }, { 96, 112 } }
local GRASS  = 7
local flip = 0
local next_assert = PERIOD
local ponds_filled = false
local function assert_stock(g)
  flip = 1 - flip
  local mines = 90 - flip
  for i = 1, g.num_bases() do
    g.set_base_stock(i, FULL, FULL, mines)
  end
end
function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      g.set_base_stock(i, FULL, FULL, 90)
      g.message(string.format(
        "REFUEL_PAD_ARENA base#%d (%d,%d) owner=%d armour=%d shells=%d",
        i, b.x, b.y, OWNER, FULL, FULL))
    end
  end
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      g.message(string.format(
        "REFUEL_PAD_ARENA pill#%d (%d,%d) owner=%s health=%s",
        i, p.x, p.y, tostring(p.owner), tostring(p.armour)))
    end
  end
end
function on_tick(g, tick)
  if tick >= next_assert then
    next_assert = tick + PERIOD
    assert_stock(g)
  end
  if not ponds_filled and tick > 400 then
    local afloat = false
    for p = 0, 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("REFUEL_PAD_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end

-- ── the verdict ─────────────────────────────────────────────────────
-- NOT PORTED. tests/refuel_pad_reach_test.py variant B is the pill moved one
-- tile closer, from 9.0 to 8.0, so that it CAN shell a tank docked on the base
-- and the pad danger has to stay on the price. Its five checks are: every
-- BASE_NEAR row is padhit and names the pill at 8.0 against the 8.71 threshold,
-- every padhit row's danger term is above 0, no row carries a padcut, BASE_FAR
-- stays padsafe, and the pick follows the two priced costs. Every one of them
-- is a chip on goals.lua's REFUEL_P1 row.
--
-- Variant A could be ported because it has an outcome -- the tank drinks at the
-- near base -- and B deliberately has none: the test does not demand a winner
-- here, because a base that is genuinely under a pill's guns may lose and the
-- rule is still working. What B measures is that the price kept the danger, and
-- the world records prices nowhere.
--
-- WHAT WOULD REPAY IT: a host op that lets a scenario read a bot's goal pool
-- for the tick -- the candidates and what each was priced at. That is the one
-- reading that would move this whole family of tests.
--
-- GATE: skip=every check is a chip on the brain's REFUEL_P1 row, and B has no outcome to read instead
