-- Scenario script for tests/reserve_gather.map -- GENERATED by
-- tests/generate_reserve_seeded_map.py, do not edit by hand.
--
-- 1. LOADOUT.  This variant wants a tank with no wood at all.  The old arena
--    ran with -bots 0 and spawned its own tank in STRICT mode, because
--    game.spawn_bot's mode argument was the only route to a -bots tank's
--    stocks.  This host has game.set_stocks, so the -bots tank is emptied on
--    its own first tick instead: the same 0/0/0 start, and the round is never
--    empty -- the gate runner passes no -noemptyreset.
--
-- 2. Own everything, so no pill on the map is a capture or attack candidate.
--
-- 3. At tick 400, hand 4 pill(s) to the tank.  That is the whole experiment:
--    what the tank is CARRYING is what the old gather priced its harvest
--    against.  The map's ENTIRE wood supply is two forest tiles -- 8 trees --
--    and the old gather asked for 4 x 4 = 16, more wood than the map holds, so
--    it could never finish and the pill could never be dropped.
local OUR_SLOT   = 0
local GIVE_IDS   = { 1, 2, 3, 4 }  -- pill numbers to load into the tank
local N_GIVE     = 4
-- 200 on the old host, where on_tick counted 50 a second.  This one counts
-- 100, so the same four seconds of play is 400.
local GIVE_TICK  = 400
local given = false
local stocked = false

local home = {}                  -- the tile every pill started on

local function own_everything(g, owner)
  for i = 1, g.num_pills() do g.set_pill_owner(i, owner) end
  for i = 1, g.num_bases() do g.set_base_owner(i, owner) end
end

function on_setup(g)
  own_everything(g, OUR_SLOT)
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then home[p.y * 256 + p.x] = true end
  end
  g.message(string.format("RESERVE_ARENA pills=%d bases=%d give=%d@%d",
                          g.num_pills(), g.num_bases(), N_GIVE, GIVE_TICK))
end

function on_tick(g, tick)
  if not stocked and tick >= 2 then
    local tk = g.tank(OUR_SLOT)
    if tk and not tk.dead then
      stocked = true
      g.set_stocks(OUR_SLOT, { shells = 0, mines = 0, trees = 0 })
    end
  end
  if not given and tick >= GIVE_TICK then
    given = true
    local n = 0
    for _, i in ipairs(GIVE_IDS) do
      local ok, err = g.give_pill(OUR_SLOT, i)
      if ok then n = n + 1
      else g.message("RESERVE_ARENA give_pill#" .. i .. " failed: "
                     .. tostring(err)) end
    end
    g.message("RESERVE_ARENA gave " .. n .. " pill(s) to slot " .. OUR_SLOT
              .. " at tick " .. tick)
  end
end

-- ── the verdict ─────────────────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/reserve_seeded_test.py variant `gather`,
-- check 6: a pill is actually PLACED -- one of the four the tank is carrying
-- ends the round standing on ground that held no pill at the start.  On a map
-- with eight trees in it, that can only happen if the seek-trees gather stops
-- at one placement's worth instead of asking for four.
--
-- What did NOT move: check 5, that every seek_trees tick declares goal
-- need_trees == PILL_PLACE_TREE_COST.  That number is a chip on the brain's
-- own BUILDER_POOL line and a scenario cannot see it.  What is left is the
-- consequence rather than the cause, which for this arena is nearly the whole
-- claim: the old gather could not finish on this map at all.
--
-- GATE: ticks=12000 bots=1 gametype=open ai=yesfull limit=20

VERDICT_CHECK = function(g)
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p and not p.in_tank and not home[p.y * 256 + p.x] then
      return true, string.format("a carried pill was planted at (%d,%d)", p.x, p.y)
    end
  end
  return false, "no pill was ever planted on new ground"
end
