-- Scenario sidecar for tests/reserve_seeded.map -- GENERATED by
-- tests/generate_reserve_seeded_map.py, do not edit by hand.
--
-- 1. LOADOUT.  This variant wants the open loadout's full 40 trees, so it just
--    uses the -bots tank as it spawned.
--
-- 2. Own everything, so no pill on the map is a capture or attack candidate.
--
-- 3. At tick 400, hand 9 pill(s) to the tank.  That is the whole experiment:
--    what the tank is CARRYING is what the old reserve priced against every job
--    it wanted to do.  At nine carried the old reserve was 4 + 36 = 40 against
--    40 trees -- exactly nothing left -- and it charged a SEEDED repair the
--    same 40, so the worn pill beside the tank could never be fixed.

local OUR_SLOT   = 0
local GIVE_IDS   = { 2, 3, 4, 5, 6, 7, 8, 9, 10 }  -- pill numbers to load into the tank
local N_GIVE     = 9
-- 200 on the old host, where on_tick counted 50 a second.  This one counts
-- 100, so the same four seconds of play is 400.
local GIVE_TICK  = 400
local given = false

local worn = nil                 -- { n, armour } the pill the repair is about

local function own_everything(g, owner)
  for i = 1, g.num_pills() do g.set_pill_owner(i, owner) end
  for i = 1, g.num_bases() do g.set_base_owner(i, owner) end
end

-- The worn pill is the one the tank is NOT handed: the least armoured of what
-- is left.  Finding it rather than naming its tile keeps the arena and the map
-- generator from drifting apart.
local function find_worn(g)
  local given_id = {}
  for _, i in ipairs(GIVE_IDS) do given_id[i] = true end
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p and not given_id[i] then
      if worn == nil or p.armour < worn.armour then
        worn = { n = i, armour = p.armour, x = p.x, y = p.y }
      end
    end
  end
end

function on_setup(g)
  own_everything(g, OUR_SLOT)
  find_worn(g)
  g.message(string.format("RESERVE_ARENA pills=%d bases=%d give=%d@%d worn=%s",
                          g.num_pills(), g.num_bases(), N_GIVE, GIVE_TICK,
                          worn and (worn.n .. "@" .. worn.armour) or "none"))
end

function on_tick(g, tick)
  if not given and tick >= GIVE_TICK then
    given = true
    local n = 0
    for _, i in ipairs(GIVE_IDS) do
      local ok, err = g.give_pill(OUR_SLOT, i)
      if ok then n = n + 1
      else g.message("RESERVE_ARENA give_pill#" .. i .. " failed: "
                     .. tostring(err)) end
    end
    g.message("RESERVE_ARENA gave " .. n .. " pill(s) to slot " .. OUR_SLOT
              .. " at tick " .. tick)
  end
end

-- ── the verdict ─────────────────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/reserve_seeded_test.py variant `seeded`,
-- check 4 and only check 4: the worn pill really comes back up, so the repair
-- the frozen reserve used to refuse was dispatched AND finished while the tank
-- was carrying nine pills.
--
-- What did NOT move, all three of it read off the brain's BUILDER_POOL and
-- BP_DISPATCH / BP_DENY lines:
--   1. the `pills` chip of the reserve is ONE placement's worth whenever
--      anything is aboard, never 4 x carried;
--   2. the repair is DISPATCHED while all nine are aboard (the armour rise
--      says it landed, not when it was decided);
--   3. no BP_DENY on that pill ever names tree_reserve.
-- The number the arena is really about is a reserve inside the brain; the only
-- mark it leaves on the world is this repair happening at all.
--
-- GATE: ticks=8000 bots=1 gametype=open ai=yesfull limit=20

VERDICT_CHECK = function(g)
  if worn == nil then return false, "no worn pill on the map to repair" end
  local p = g.pill(worn.n)
  if p == nil then return false, "the worn pill is gone" end
  if p.armour > worn.armour then
    return true, string.format("worn pill %d to %d armour with 9 aboard",
                               worn.armour, p.armour)
  end
  return false, string.format("worn pill still at %d armour, never repaired",
                              p.armour)
end
