-- Scenario sidecar for tests/sea_release_release.map -- GENERATED by
-- tests/generate_sea_release_map.py, do not edit by hand.
--
-- Three jobs.
--
-- 1. mapRead puts ROAD under every map-file pillbox (bolo_map.c), so the dead
--    raft would sit on one-tile road pedestals in the middle of the sea -- a
--    boat driving onto one BEACHES and the tank drowns stepping off.
--    on_setup runs before the first snapshot, so put the deep sea back under
--    them there.  Same trick as tests/sea_pills_*.scenario.lua.
--
-- 2. Own the raft and the base.
--
-- 3. At tick 800 hand the WHOLE RAFT to the tank.  The pills are in a tank
--    now, so filter_capture_pill drops them, the committed capture goal is
--    invalidated, and the goal changes on that tick with the harvest chain
--    half-run and its plan live.  Nothing else in the arena touches the
--    harvest.

local T_DEEP_SEA = 0xFF
local OUR_PLAYER = 0
local RAFT       = { { 138, 124 }, { 139, 126 }, { 138, 128 } }
local GIVE       = true
-- 400 on the old host, where on_tick counted 50 a second.  This one counts
-- 100, so the same four seconds of play is 800.
local GIVE_TICK  = 800
local given      = false

function on_setup(g)
  for _, p in ipairs(RAFT) do
    g.set_tile(p[1], p[2], T_DEEP_SEA)
  end
  for i = 1, g.num_pills() do
    g.set_pill_owner(i, OUR_PLAYER)
  end
  for i = 1, g.num_bases() do
    g.set_base_owner(i, OUR_PLAYER)
  end
  g.message(string.format("SEA_RELEASE_ARENA raft of %d, give=%s@%d",
                          g.num_pills(), tostring(GIVE), GIVE_TICK))
end

function on_tick(g, tick)
  if GIVE and not given and tick >= GIVE_TICK then
    given = true
    local n = 0
    for i = 1, g.num_pills() do
      local ok, err = g.give_pill(OUR_PLAYER, i)
      if ok then n = n + 1
      else g.message("SEA_RELEASE_ARENA give_pill#" .. i .. " failed: "
                     .. tostring(err)) end
    end
    g.message("SEA_RELEASE_ARENA gave " .. n .. " raft pill(s) at tick " .. tick)
  end
end

-- ── the verdict ─────────────────────────────────────────────────────────
-- NOT PORTED (2026-09-15).  All four of tests/sea_plan_release_test.py's
-- `release` checks read the brain's own print2 log and nothing else:
--
--   1. the sea plan went live -- the `sea` term of the BUILDER_POOL reserve
--      line read the plan's 21 trees for a stretch of ticks;
--   2. a SEA_RELEASE line with reason=goal_changed exists, and it lands on the
--      FIRST tick the BUILDER_POOL owner stopped being capture_pill;
--   3. from that tick on the `sea` term is 0 -- that tick, not the next;
--   4. the printed reserve still adds up from its own chips, base + pills +
--      goal + sea == res.
--
-- The thing under test is a number inside the brain that is released on a
-- particular tick.  It leaves no mark on the world: the wood it was holding
-- back goes to a repair the reserve used to refuse, and that repair is
-- tests/reserve_seeded_test.py's arena, not this one.  Nothing here can be
-- asked of game.*.  Expressing it would need the host to expose a brain's
-- debug lines to a scenario, which it does not and should not.
--
-- The arena is left intact -- it still hands the raft over at GIVE_TICK -- so
-- that it is ready the day the run is measured some other way.
--
-- GATE: skip=every check reads brain debug lines (SEA_RELEASE, BUILDER_POOL reserve chips); the release leaves no mark on the world
