-- Scenario script for tests/sea_release_control.map -- GENERATED by
-- tests/generate_sea_release_map.py, do not edit by hand.
--
-- Two jobs.
--
-- 1. mapRead puts ROAD under every map-file pillbox (bolo_map.c), so the dead
--    raft would sit on one-tile road pedestals in the middle of the sea -- a
--    boat driving onto one BEACHES and the tank drowns stepping off.
--    on_setup runs before the first snapshot, so put the deep sea back under
--    them there.  Same trick as tests/sea_pills_*.scenario.lua.
--
-- 2. Own the raft and the base.
--
-- This is the CONTROL: nothing is ever handed to the tank, so its goal never
-- changes and the harvest it starts is the harvest it finishes.  The `release`
-- arena is the one that takes the raft away mid-chain.

local T_DEEP_SEA = 0xFF
local OUR_PLAYER = 0
local RAFT       = { { 138, 124 }, { 139, 126 }, { 138, 128 } }

local raft = {}                  -- { n, x, y } per raft pill, resolved once

-- By SLOT, not by coordinate: a pill that is picked up moves with its carrier,
-- so a coordinate match would stop finding it at the moment the verdict wants
-- to know whether it was fetched.
local function resolve(g)
  for _, d in ipairs(RAFT) do
    for i = 1, g.num_pills() do
      local p = g.pill(i)
      if p and p.x == d[1] and p.y == d[2] then
        raft[#raft + 1] = { n = i, x = d[1], y = d[2] }
      end
    end
  end
end

-- What the old driver called collected: the pill is no longer lying dead on
-- its own square.
local function collected(g, e)
  local p = g.pill(e.n)
  if p == nil or p.in_tank then return true end
  if p.x ~= e.x or p.y ~= e.y then return true end
  return (p.armour or 0) > 0
end

function on_setup(g)
  for _, p in ipairs(RAFT) do
    g.set_tile(p[1], p[2], T_DEEP_SEA)
  end
  for i = 1, g.num_pills() do
    g.set_pill_owner(i, OUR_PLAYER)
  end
  for i = 1, g.num_bases() do
    g.set_base_owner(i, OUR_PLAYER)
  end
  resolve(g)
  g.message(string.format("SEA_RELEASE_ARENA raft of %d", #raft))
end

-- ── the verdict ─────────────────────────────────────────────────────────
-- PORTED (2026-09-15) from tests/sea_plan_release_test.py check 5, the whole
-- of the control's assertion: the tank that is never asked to change goal
-- still takes all three raft pills, so releasing the sea plan on a goal change
-- costs the harvest that never changes goal nothing.
--
-- Nothing was left behind: the control had no other check.  The four checks
-- about the plan's release itself (the SEA_RELEASE line, the tick the reserve's
-- `sea` term drops to 0, and the chips adding up) are the `release` arena's,
-- and they are brain debug.
--
-- GATE: ticks=12000 bots=1 gametype=open ai=yesfull limit=20

VERDICT_CHECK = function(g)
  local got = 0
  for _, e in ipairs(raft) do
    if collected(g, e) then got = got + 1 end
  end
  if got < #raft then
    return false, string.format("only %d of %d raft pills taken", got, #raft)
  end
  return true, string.format("the untouched tank still took all %d", got)
end
