-- GENERATED by tests/generate_capture_lgm_priority_map.py -- do not edit by hand.
-- Scenario sidecar for tests/capture_lgm_priority_P1.map (auto-loaded as
-- <map>.scenario.lua).  Companion to tests/capture_lgm_priority_test.py arena P1.
--
-- Rows in capture_lgm_priority_P1_trace.log are `tick x y armour owner in_tank`,
-- one per CHANGE of the LIVE corpse, so "the pill was dead while the hunt ran"
-- and "the armour came back down" are asked of the ENGINE and never of the
-- brain's opinion of itself.  Lines starting # are events.

local TRACE   = "capture_lgm_priority_P1_trace.log"
local P0, P1  = 0, 1
local NBOTS   = 2
local PULSE   = 0         -- H2: armour an invisible "repair" reaches
local PMODE   = false      -- H2: an armour rise is the POINT, not a spent corpse
local HOLD    = 0          -- H2: sim ticks the pulse is held
local PERIOD  = 0        -- H2: sim ticks between pulses
local AWAY    = 6          -- tiles p0 must be clear before a spare pops
local MAXWAIT = 400       -- ...or this many sim ticks, whichever first
local CORPSE  = { 122, 126 }
local ROADT   = { 128, 126 }
local FARMT   = { 128, 125 }
local SPAWN0  = { 110, 126 }
local SPAWN1  = { 128, 116 }
local SPARES  = { { 108, 118 }, { 108, 122 }, { 108, 126 }, { 108, 130 }, { 108, 134 }, { 144, 118 }, { 144, 122 }, { 144, 126 }, { 144, 130 }, { 144, 134 }, { 112, 118 }, { 112, 134 }, { 140, 118 }, { 140, 134 } }
local GRASS, FOREST = 7, 5
local FILL_TICK = 60

local idx_live   = nil            -- pill index currently playing the corpse
local spare_idx  = {}             -- resolved indices of the hidden spares
local next_spare = 1
local taken_at   = nil            -- sim tick the live corpse went into a tank
local grabs      = 0
local last_sig   = nil
local filled0, filled1 = false, false
local pulse_at, pulse_off = nil, nil
local pulses = 0
local resolved = false

local function note(line)
  local f = io.open(TRACE, "a")
  if f then f:write(line .. "\n") f:close() end
end

local function same(p, t) return p.x == t[1] and p.y == t[2] end

-- Resolve tiles to pill INDICES once.  Everything after this reads the pill BY
-- INDEX: a pill that is picked up moves with its carrier, so a coordinate
-- match would stop finding it exactly when the trace exists to prove somebody
-- took it.
local function resolve(g)
  spare_idx = {}
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      if same(p, CORPSE) then
        idx_live = i
      else
        for s = 1, #SPARES do
          if same(p, SPARES[s]) then spare_idx[#spare_idx + 1] = i end
        end
      end
    end
  end
  return idx_live ~= nil
end

function on_setup(g)
  resolved = resolve(g)
  -- The corpse belongs to p0 and is DEAD: a free pill lying on the ground,
  -- which is exactly what capture_pill is for.
  if idx_live then
    g.set_pill_owner(idx_live, P0)
    g.set_pill_armour(idx_live, 0)
  end
  -- The spares are refills, not pillboxes: off the map until they are needed.
  -- NEUTRAL FIRST, AND THAT IS NOT COSMETIC.  hide_pill is pillsSetPillInTank
  -- (scenario.c), so a hidden pill still OWNED BY p0 reads to the engine and
  -- to the brain as a pillbox p0 is CARRYING.  Measured on the first draft:
  -- five hidden spares gave p0 five phantom pillboxes, it spent the whole run
  -- on place_pill_strategic (2056 goal changes) instead of the capture, and
  -- the arena measured nothing.  Ownership goes back to p0 in the refill.
  for i = 1, #spare_idx do
    g.set_pill_owner(spare_idx[i], g.NEUTRAL)
    g.hide_pill(spare_idx[i])
  end
  for i = 1, g.num_bases() do
    g.set_base_stock(i, 90, 90, 90)
  end
  local f = io.open(TRACE, "w")
  if f then f:write("# tick x y armour owner in_tank\n") f:close() end
end

function on_choose_start(g, p)
  if p == P0 then return 1 end
  if p == P1 and NBOTS > 1 then return 2 end
  return nil
end

function on_tick(g, tick)
  -- ALLIANCE, APPLIED FROM on_tick.  botManagerSetTeams walks the bots' OWN
  -- ClientSim alliance tables and at on_setup time no bot exists yet, so a
  -- set_team there reaches the server roster and nothing else and the two
  -- tanks still read each other as OBJECT_HOSTILE.  Re-applied for the first
  -- 120 ticks so it lands whenever the slots actually come up.
  if NBOTS > 1 and tick <= 120 then
    g.set_team(P0, 0)
    g.set_team(P1, 1)
  end

  -- Fill the spawn ponds once each tank is ASHORE and off its boat.  Filling
  -- the tile while the tank still sits on it leaves the boat state stuck and
  -- the LGM never becomes available.
  if tick >= FILL_TICK then
    if not filled0 then
      local tk = g.tank(P0)
      if tk and not tk.boat and not tk.dead
         and (tk.mx ~= SPAWN0[1] or tk.my ~= SPAWN0[2]) then
        filled0 = true
        g.set_tile(SPAWN0[1], SPAWN0[2], GRASS)
        note(string.format("# pondfill0 %d", tick))
      end
    end
    if NBOTS > 1 and not filled1 then
      local tk = g.tank(P1)
      if tk and not tk.boat and not tk.dead
         and (tk.mx ~= SPAWN1[1] or tk.my ~= SPAWN1[2]) then
        filled1 = true
        g.set_tile(SPAWN1[1], SPAWN1[2], GRASS)
        note(string.format("# pondfill1 %d", tick))
      end
    end
  end

  -- KEEP THE ERRANDS ALIVE.  A paved road is not a road job any more and a
  -- chopped tree is gone for good, so without this the enemy's man stops being
  -- sent halfway through the measurement.  Re-stamping both tiles every tick
  -- costs nothing and also repairs a stray shell's damage.
  g.set_tile(ROADT[1], ROADT[2], GRASS)
  g.set_tile(FARMT[1], FARMT[2], FOREST)

  if not resolved then
    resolved = resolve(g)
    if not resolved then return end
  end

  -- ── ONE PILL ON THE MAP, ALWAYS THE CORPSE ──────────────────────────
  -- Anything lying on the ground that is not the live corpse gets taken off
  -- the map.  That is almost always the pill p0 just captured and then PLACED
  -- (measured: it planted it at (126,127), one tile from the corpse tile),
  -- and a LIVE pill next to the target is the worst possible scenery here --
  -- init.lua's kill-LGM LOS check treats any live pillbox in the shell's lane
  -- as a block, so the fire half of the feature could never open.
  for i = 1, g.num_pills() do
    if i ~= idx_live then
      local p = g.pill(i)
      if p and not p.in_tank
         and not (p.x == CORPSE[1] and p.y == CORPSE[2]) then
        g.set_pill_owner(i, g.NEUTRAL)
        if g.hide_pill(i) then
          note(string.format("# sweep %d pill=%d at(%d,%d) armour=%d",
                             tick, i, p.x, p.y, p.armour))
        end
      end
    end
  end

  -- ── THE REFILLING CORPSE ────────────────────────────────────────────
  -- Grabbing a dead pill is one tick of driving over it, so one corpse buys
  -- ONE approach.  The corpse is SPENT the moment it stops being "dead, on the
  -- ground, on the corpse tile" -- taken into a tank, or replanted elsewhere.
  -- Once it is spent, wait until p0 has driven AWAY tiles clear (or MAXWAIT
  -- ticks, whichever comes first, so a bot that parks on the tile cannot wedge
  -- the arena) and pop the next spare back onto the corpse tile.
  -- show_pill(n, x, y) lands it DEAD and on the ground, which is exactly the
  -- state a capture wants.
  -- PMODE (arena H2) is the exception to "armour > 0 means somebody rebuilt
  -- it, so this corpse is finished": there the pulse IS the measurement, and
  -- treating it as spent refilled a SECOND pill onto the same tile two ticks
  -- into every pulse.  world.pill_at keys a LIST per tile, the brain reads the
  -- first entry, and the armour watch then saw whichever of the two it
  -- happened to get -- the hunt engaged once and never again.
  local live = idx_live and g.pill(idx_live)
  local spent = (live == nil) or live.in_tank
                or (not PMODE and live.armour > 0)
                or live.x ~= CORPSE[1] or live.y ~= CORPSE[2]
  if spent then
    if not taken_at then
      taken_at = tick
      grabs = grabs + 1
      note(string.format("# spent %d n=%d in_tank=%s armour=%s", tick, grabs,
                         tostring(live and live.in_tank),
                         tostring(live and live.armour)))
    end
    local t0 = g.tank(P0)
    local away = 99
    if t0 and not t0.dead then
      local dx = t0.mx - CORPSE[1]; if dx < 0 then dx = -dx end
      local dy = t0.my - CORPSE[2]; if dy < 0 then dy = -dy end
      away = (dx > dy) and dx or dy
    end
    if next_spare <= #spare_idx
       and (away >= AWAY or (tick - taken_at) >= MAXWAIT) then
      local n = spare_idx[next_spare]
      next_spare = next_spare + 1
      if g.show_pill(n, CORPSE[1], CORPSE[2]) then
        g.set_pill_owner(n, P0)
        g.set_pill_armour(n, 0)
        idx_live = n
        taken_at = nil
        last_sig = nil
        note(string.format("# refill %d pill=%d away=%d", tick, n, away))
      end
    end
  else
    taken_at = nil
  end

  -- ENGINE-SIDE TRACE of the live corpse: every change of armour, owner or
  -- in_tank, in SIM ticks.
  local q = idx_live and g.pill(idx_live)
  if q then
    local in_tank = q.in_tank and 1 or 0
    local sig = q.armour .. "/" .. q.owner .. "/" .. in_tank .. "/" .. q.x .. "," .. q.y
    if last_sig ~= sig then
      note(string.format("%d %d %d %d %d %d", tick, q.x, q.y,
                         q.armour, q.owner, in_tank))
      last_sig = sig
    end
  end
end
