-- Scenario sidecar for tests/farm_sectors_B.map (auto-loaded as
-- <map>.scenario.lua). Companion to tests/farm_sectors_test.py arena B.
-- GENERATED by tests/generate_farm_sectors_map.py -- edit that, not this.
--
-- ARENA B: a tank DRIVING east along a road to scoop a dead pill twenty tiles
-- away -- which is what gives it the committed route the return-leg prediction
-- walks. The moment it enters column PLANT_X the sidecar plants two forests,
-- one PLANT_DX tiles behind and one PLANT_DX ahead, both PLANT_DY rows south
-- of the drive row. Equal outbound legs by construction; only the walk HOME
-- can tell them apart.
--
-- They are planted rather than baked in because "the same distance away" is
-- true for exactly one tick of a moving tank, and game.set_tile is the only
-- way to make that tick the arena's to choose.

local TRACE = "farm_sectors_B_trace.log"
local SPAWN = { 116, 126 }
local TARGET = { 139, 126 }
local PLANT_X, PLANT_DX, PLANT_DY = 126, 3, 1
local FILL_TICK = 40
local FOREST, GRASS = 5, 7
local p0 = 0

local filled = false
local planted = false
local last_tile = nil

local function log(fmt, ...)
  local f = io.open(TRACE, "a")
  if f then f:write(string.format(fmt, ...) .. "\n") f:close() end
end

local function same(p, t) return p.x == t[1] and p.y == t[2] end

function on_setup(g)
  -- The drive target is a NEUTRAL base: capture_base is what makes the tank
  -- cross the map, and (unlike capture_pill, which sets builder mode
  -- "gather") it leaves the builder pool eligible the whole way.
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b and same(b, TARGET) then g.set_base_owner(i, g.NEUTRAL) end
  end
  g.set_team(p0, 0)
  local f = io.open(TRACE, "w")
  if f then f:write("# TANK tick mx my | PLANT tick mx my bx by ax ay\n") f:close() end
end

function on_choose_start(g, p)
  if p == p0 then return 1 end
  return nil
end

function on_tick(g, tick)
  local tk = g.tank(p0)
  if not tk then return end
  if not tk.dead then
    local key = tk.mx .. "," .. tk.my
    if last_tile ~= key then
      last_tile = key
      log("TANK %d %d %d", tick, tk.mx, tk.my)
    end
  end

  if not filled and tick >= FILL_TICK then
    if not tk.boat and not tk.dead
       and (tk.mx ~= SPAWN[1] or tk.my ~= SPAWN[2]) then
      filled = true
      g.set_tile(SPAWN[1], SPAWN[2], GRASS)
    end
  end

  if filled and not planted and not tk.dead and not tk.boat
     and tk.mx >= PLANT_X then
    planted = true
    local my = tk.my + PLANT_DY
    local bx, ax = PLANT_X - PLANT_DX, PLANT_X + PLANT_DX
    g.set_tile(bx, my, FOREST)
    g.set_tile(ax, my, FOREST)
    log("PLANT %d %d %d %d %d %d %d", tick, tk.mx, tk.my, bx, my, ax, my)
    g.message(string.format(
      "FARM_SECTORS_B planted: behind (%d,%d), ahead (%d,%d),"
      .. " tank (%d,%d) at t=%d", bx, my, ax, my, tk.mx, tk.my, tick))
  end
end
