-- Scenario sidecar for tests/farm_sectors_A.map (auto-loaded as
-- <map>.scenario.lua). Companion to tests/farm_sectors_test.py arena A.
-- GENERATED by tests/generate_farm_sectors_map.py -- edit that, not this.
--
-- ARENA A: a tank with nothing to do, a forest behind a wall, and a clear
-- forest further away on the other side. The whole geometry is planted HERE,
-- relative to the tile the tank comes to rest on, because "the walled forest
-- is the nearest one" is a claim about the tank's position and baking it into
-- the map file would make it a claim about where the tank happened to stop.
--
-- The tank stops because it has nothing to do: no pills, no bases, and
-- EXPLORE_BASE_COST priced past the unaffordable line by the -bot-init tokens.
-- TANK lines in the trace record every tile it stands on, so the test can
-- prove it stayed put rather than assuming it.
--
-- FILLING THE SPAWN POND. A start square has to be DEEP SEA at map load
-- (starts.c startsIsValidSquare), and the LGM walk sim walks a STRAIGHT LINE
-- with a crude slide, so a hole anywhere on the line makes the target read
-- `unreachable`. The pond is filled back to grass once the tank is ashore and
-- OFF it -- filling it under the tank leaves the boat state stuck and the LGM
-- never becomes available at all.

local TRACE = "farm_sectors_A_trace.log"
local SPAWN = { 126, 126 }
local FIELD = { 120, 132, 124, 128 }   -- x0, x1, y0, y1
local WALL_DX, BLOCKED_DX, OPEN_DX = -1, -2, 3
local FILL_TICK, PLANT_TICK = 60, 400
local MOAT, FOREST, GRASS = 0xFF, 5, 7   -- 0xFF = DEEP SEA (scenario.c l_set_tile)
local p0 = 0

local filled = false
local planted = false
local last_tile = nil

local function log(fmt, ...)
  local f = io.open(TRACE, "a")
  if f then f:write(string.format(fmt, ...) .. "\n") f:close() end
end

function on_setup(g)
  g.set_team(p0, 0)
  local f = io.open(TRACE, "w")
  if f then f:write("# TANK tick mx my | PLANT tick mx my wallx blx bly opx opy\n") f:close() end
end

function on_choose_start(g, p)
  if p == p0 then return 1 end
  return nil
end

function on_tick(g, tick)
  local tk = g.tank(p0)
  if not tk then return end
  if not tk.dead then
    local key = tk.mx .. "," .. tk.my
    if last_tile ~= key then
      last_tile = key
      log("TANK %d %d %d", tick, tk.mx, tk.my)
    end
  end

  if not filled and tick >= FILL_TICK then
    if not tk.boat and not tk.dead
       and (tk.mx ~= SPAWN[1] or tk.my ~= SPAWN[2]) then
      filled = true
      g.set_tile(SPAWN[1], SPAWN[2], GRASS)
      g.message(string.format(
        "FARM_SECTORS_A filled the spawn pond at (%d,%d) at t=%d",
        SPAWN[1], SPAWN[2], tick))
    end
  end

  -- Plant only once the tank has settled AND the geometry fits inside the
  -- field from where it is standing. If it never fits the test says so; it
  -- must never plant a half-arena and let the run look like a real result.
  if filled and not planted and tick >= PLANT_TICK and not tk.dead
     and not tk.boat then
    local mx, my = tk.mx, tk.my
    local ok = (mx + BLOCKED_DX >= FIELD[1]) and (mx + OPEN_DX <= FIELD[2])
    if ok then
      planted = true
      -- A MOAT OF DEEP SEA, not a wall of buildings, and it spans the WHOLE
      -- field height. Two measured failures are behind both halves of that:
      --   * a three-tile BUILDING wall beside the tank was walked around --
      --     the walk sim runs a straight line from wherever the tank IS, and a
      --     two-row drift clears the end of a short wall (arena A dispatched
      --     to the "walled" forest at t=526 on the first attempt);
      --   * a FULL-HEIGHT building wall was SHOT DOWN. The bot prices walls
      --     into its own paths (wall_shoot_cost) and cleared the column in
      --     ~270 sim ticks, then drove through the gap.
      -- Deep sea is the one barrier the man can never cross
      -- (brain_pathfinder.c lgm_man_speed[10] = 0) and the tank can never
      -- remove -- the same moat tests/generate_repair_priority_map.py uses to
      -- keep its neutral island unreachable.
      for wy = FIELD[3], FIELD[4] do
        g.set_tile(mx + WALL_DX, wy, MOAT)
      end
      g.set_tile(mx + BLOCKED_DX, my, FOREST)
      g.set_tile(mx + OPEN_DX, my, FOREST)
      log("PLANT %d %d %d %d %d %d %d %d", tick, mx, my,
          mx + WALL_DX, mx + BLOCKED_DX, my, mx + OPEN_DX, my)
      g.message(string.format(
        "FARM_SECTORS_A planted: wall x=%d, walled forest (%d,%d),"
        .. " open forest (%d,%d), tank (%d,%d) at t=%d",
        mx + WALL_DX, mx + BLOCKED_DX, my, mx + OPEN_DX, my, mx, my, tick))
    end
  end
end
