#!/usr/bin/env python3
"""
Generate the sea-plan-release arena (companion to tests/sea_plan_release_test.py).

Field incident 20260903_105448 bot2, ticks 15000..36670.  A deep-sea harvest
was planned at ~t=15000 and its LGM died at t=28997.  Nothing retired
`state._sea_live`, so for the rest of the game builder_pool.tree_reserve kept
adding the plan's 21 trees (base 4 + pills 16 + sea 21 = 41 against 21 trees)
and builder.decide kept bailing `sea_trees_reserved` before it could reach a
spending rung.  The bot stood beside three damaged friendly pills with four
pills aboard and repaired nothing.

The brain change this arena exercises (author, 2026-09-03): the sea plan --
and therefore its tree reserve -- ends the tick the tank's goal stops being
that harvest.  T = 0, no grace window.

THE ARENA is the sea_pills variant-A canvas, imported wholesale and unchanged:
a land peninsula with a forest strip and a grass shore column, NO river
anywhere, three DEAD friendly pills 1-2 tiles off the shore in deep sea, our
base one tile from the spawn pocket.  Nothing is added to the map at all --
the sea_pills suite already proves this canvas runs the whole chain
(mine -> crater -> river -> boat -> sail -> 3 pills) inside a game minute, and
an arena that changes it would be measuring its own noise.  A worn friendly
pill WAS tried here and had to be taken out again: with the open loadout's 40
trees the pool sent the man to fix it at t=66, before any plan existed, and
that errand left the tank unable to get back onto its firing tile for the rest
of the run.  What the reserve does to the tank's own jobs has its own arena
(tests/reserve_seeded_test.py); this one is about WHEN the plan dies.

The only difference between the two variants is the sidecar:

  release   at sim tick GIVE_TICK the sidecar hands the WHOLE RAFT to the tank
            with game.give_pill -- "somebody else got there first" -- with the
            chain half-run and the plan live.  The goal has to change: the
            pills are in a tank now, so filter_capture_pill drops them and the
            committed capture goal is invalidated.  It has to be that lever: a
            goal this brain is COMMITTED to is not moved by a merely cheaper
            rival (measured here: a place_pill_strategic row priced 2.5
            against the harvest's 5.0 still lost by 230 once the switch flat
            of 30 and the commitment of 200 were added).  Handing the raft
            over touches nothing else -- there is no enemy tank in the arena,
            so none of the plan's own safety gates can be what retires it, and
            the only remaining candidate is the rule under test.

  control   nothing is handed over.  The tank runs the harvest itself, exactly
            as sea_pills variant A runs it, and takes all three.

Usage:
    python3 tests/generate_sea_release_map.py [--variant release|control|ALL]
    Writes tests/sea_release_<variant>.map and .scenario.lua
"""

import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_sea_pills_map import (          # noqa: E402
    DEEP_SEA, SEA_PILLS, BASE_OURS, SPAWN,
    encode_map_runs, make_map, recenter_shift)

GIVE_TICK = 400                # SIM ticks (brain tick 200). sea_pills A is at
                               # approach_F/lay_mine by brain tick ~177, so the
                               # plan is live and mid-chain here.
OUR_PLAYER = 0
VARIANTS = ("release", "control")


def pills_for():
    """(x, y, owner, armour, speed) -- the dead raft, ours, numbered 1..3."""
    return [(x, y, OUR_PLAYER, 0, 50) for (x, y) in SEA_PILLS]


SIDECAR = r'''
-- Scenario sidecar for tests/sea_release_{V}.map -- GENERATED by
-- tests/generate_sea_release_map.py, do not edit by hand.
--
-- Three jobs.
--
-- 1. mapRead puts ROAD under every map-file pillbox (bolo_map.c), so the dead
--    raft would sit on one-tile road pedestals in the middle of the sea -- a
--    boat driving onto one BEACHES and the tank drowns stepping off.
--    on_setup runs before the first snapshot, so put the deep sea back under
--    them there.  Same trick as tests/sea_pills_*.scenario.lua.
--
-- 2. Own the raft and the base.
--
-- 3. variant `release` only: at tick {GIVE_TICK} hand the WHOLE RAFT to the
--    tank.  The pills are in a tank now, so filter_capture_pill drops them,
--    the committed capture goal is invalidated, and the goal changes on that
--    tick with the harvest chain half-run and its plan live.  Nothing else in
--    the arena touches the harvest.

local T_DEEP_SEA = 0xFF
local OUR_PLAYER = {OWNER}
local RAFT       = {RAFT}
local GIVE       = {GIVE}
local GIVE_TICK  = {GIVE_TICK}
local given      = false

function on_setup(g)
  for _, p in ipairs(RAFT) do
    g.set_tile(p[1], p[2], T_DEEP_SEA)
  end
  for i = 1, g.num_pills() do
    g.set_pill_owner(i, OUR_PLAYER)
  end
  for i = 1, g.num_bases() do
    g.set_base_owner(i, OUR_PLAYER)
  end
  g.message(string.format("SEA_RELEASE_ARENA raft of %d, give=%s@%d",
                          g.num_pills(), tostring(GIVE), GIVE_TICK))
end

function on_tick(g, tick)
  if GIVE and not given and tick >= GIVE_TICK then
    given = true
    local n = 0
    for i = 1, g.num_pills() do
      local ok, err = g.give_pill(OUR_PLAYER, i)
      if ok then n = n + 1
      else g.message("SEA_RELEASE_ARENA give_pill#" .. i .. " failed: "
                     .. tostring(err)) end
    end
    g.message("SEA_RELEASE_ARENA gave " .. n .. " raft pill(s) at tick " .. tick)
  end
end
'''


def write_sidecar(variant, path):
    text = (SIDECAR
            .replace("{V}", variant)
            .replace("{OWNER}", str(OUR_PLAYER))
            .replace("{RAFT}",
                     "{ " + ", ".join("{ %d, %d }" % p for p in SEA_PILLS) + " }")
            .replace("{GIVE}", "true" if variant == "release" else "false")
            .replace("{GIVE_TICK}", str(GIVE_TICK)))
    Path(path).write_text(text.lstrip("\n"), encoding="utf-8", newline="\n")


def build(variant, output):
    terrain = make_map("A")            # the proven variant-A canvas, verbatim
    pills = pills_for()
    bases = [(BASE_OURS[0], BASE_OURS[1], OUR_PLAYER, 90, 90, 90)]
    starts = [(SPAWN[0], SPAWN[1], 4)]          # dir 4 = east, toward the shore

    for (x, y) in SEA_PILLS:
        assert terrain[y][x] is DEEP_SEA, f"pill ({x},{y}) must be in deep sea"
    assert terrain[SPAWN[1]][SPAWN[0]] is DEEP_SEA, "the spawn must be water"
    # Every pill here is FRIENDLY and DEAD, so none of them shoots and none can
    # reject the plan for a reason that has nothing to do with this test.
    assert all(p[2] == OUR_PLAYER and p[3] == 0 for p in pills)

    add_x, add_y = recenter_shift(terrain, pills, bases, starts)
    assert add_x == 0 or add_y == 0, (
        f"addX={add_x} addY={add_y} -- the map would be recentered and file "
        f"coords would stop matching game coords")

    with open(output, 'wb') as f:
        f.write(b'BMAPBOLO')
        f.write(struct.pack('B', 1))
        f.write(struct.pack('B', len(pills)))
        f.write(struct.pack('B', len(bases)))
        f.write(struct.pack('B', len(starts)))
        for x, y, owner, armour, speed in pills:
            f.write(struct.pack('BBBBB', x, y, owner, armour, speed))
        for x, y, owner, armour, shells, mines in bases:
            f.write(struct.pack('BBBBBB', x, y, owner, armour, shells, mines))
        for x, y, d in starts:
            f.write(struct.pack('BBB', x, y, d))
        f.write(encode_map_runs(terrain))
    return add_x, add_y


def main_one(variant):
    here = Path(__file__).parent
    out = here / f"sea_release_{variant}.map"
    add_x, add_y = build(variant, out)
    write_sidecar(variant, here / f"sea_release_{variant}.scenario.lua")
    print(f"Wrote {out} ({out.stat().st_size} bytes) variant={variant} "
          f"addX={add_x} addY={add_y}")
    print(f"  dead raft {SEA_PILLS}, base {BASE_OURS}, spawn {SPAWN}")
    print("  the raft is handed to the tank at sim tick " + str(GIVE_TICK)
          if variant == "release"
          else "  the raft is never handed over (control): the tank fetches it")


def main():
    args = sys.argv[1:]
    variant = "ALL"
    i = 0
    while i < len(args):
        if args[i] == "--variant":
            variant = args[i + 1]
            i += 2
        else:
            i += 1
    todo = VARIANTS if variant == "ALL" else (variant,)
    for v in todo:
        assert v in VARIANTS, f"unknown variant {v}"
        main_one(v)


if __name__ == '__main__':
    main()
