-- Scenario sidecar for tests/heat_pill_B2.map (auto-loaded as
-- <map>.scenario.lua).  GENERATED by tests/generate_heat_pill_map.py -- edit
-- the generator, not this file.
--
-- Companion to tests/heat_pill_test.py arena B2.
--
-- FOUR JOBS.
--
-- 1. OWNERSHIP.  The .map file can only say "owner 0", so the pill and the
--    base are handed to slot 0 (the -bots tank) and re-asserted after the foe
--    joins: a fresh connection can shuffle pill ownership.
--
-- 2. THE ENEMY, AND WHY IT IS PUT ASHORE.  Spawn one scripted IDLE bot
--    (tests/brains/idle.lua) on team 1 at start 2, the pond at
--    (129,126), then fill that pond in under it.  It never moves,
--    never shoots and never picks anything up, so d(P,E) and d(us,E) -- the
--    two numbers heat_pill_select compares -- are constants.
--
--    IT HAS TO BE ON LAND.  Left afloat it dies to the FIRST shell that
--    touches it: tankInGameDamage takes the boat away on any hit
--    (src/bolo/tank.c:1258-1265) and a tank standing on DEEP_SEA without a
--    boat drowns on the next update (tank.c:575).  Our own pill is 4.1 tiles
--    from it and shells it unprompted, so a floating enemy died in the middle
--    of the heat volley on the first run of this arena -- the target vanished
--    at hits 3-of-4, attack_tank went invalid and the volley disappeared
--    without an exit.  On grass the same tank has TANK_FULL_ARMOUR and rides
--    out the whole volley.  Start 3 exists because start 2 is grass by then
--    and a filled-in start is not a valid placement any more.
--
-- 3. FILLING OUR SPAWN POND, AND SPAWNING THE ENEMY ONLY AFTERWARDS.  A start
--    square has to be DEEP SEA at placement time, which leaves a one-tile hole
--    in our room.  It is filled back to GRASS once our tank is ashore AND off
--    it -- filling it underneath the tank leaves the boat state wedged.
--
--    THE ENEMY IS NOT SPAWNED UNTIL THAT HAS HAPPENED.  heat_pill_fire holds
--    the brake (KEY_SLOWER) for as long as a volley runs, and on the first run
--    of this arena the enemy existed from tick 2: the bot opened a volley at
--    brain tick 12 while still sitting in its boat on the spawn pond, braked,
--    and never came ashore at all -- 117 ticks of firing from the water, no
--    hits, and the pond never filled because the tank never left it.  With no
--    enemy on the map the bot simply explores, comes ashore, and the fight
--    starts on dry land.
--
-- 4. THE TRACE.  Every change of ARMOUR, OWNER, IN_TANK or **SPEED** on our
--    pill is written to heat_pill_B2_trace.log in SIM ticks, one row per
--    change.  SPEED IS THE ENGINE'S ANGER (scenario.c:262): 100 =
--    PILLBOX_ATTACK_NORMAL, 6 = PILLBOX_MAX_FIRERATE.  That column is the
--    engine-authoritative evidence the test asserts on -- the brain's
--    `pill.anger` is only a proxy and never appears here.
--
-- Rows are `tick x y armour owner in_tank speed`.  x/y are the pill's ORIGINAL
-- tile -- its identity in this file -- not its live position, because a pill
-- that is picked up rides along with the tank that took it.
--
-- THIS ARENA ALSO HOLDS THE PILL DOWN AT ITS MAP ARMOUR, because THE BOT
-- REPAIRS IT.  Both hp arenas turn on a pill that is deliberately hurt -- B at
-- 10 armour so the health cap allows nothing, B2 at 10 so it allows
-- exactly two of the engine's four halvings -- and in the first measured run
-- of arena B the builder pool sent the man out and the engine trace read
-- `286 126 125 15` at sim tick 286.  By the time an enemy existed the gate was
-- looking at a 15-hp pill and said ENTER.  A cfg token is the real fix (the
-- test passes BUILDER_POOL_TREES_TOPUP=99, which prices the errand past the
-- tank's whole woodpile); this clamp is the belt to that brace, and it only
-- ever lowers the armour, so it never undoes the volley's own damage.
--
-- Knocking it back down is an armour DROP, so world.lua bumps the anger proxy
-- -- but `hp` is tested BEFORE `already_hot` in heat_pill_select, so the skip
-- reason is unaffected.
local TRACE      = "heat_pill_B2_trace.log"
local OURS       = { { 126, 125 } }
local SPAWN      = { 123, 126 }
local FOE_SPAWN  = { 129, 126 }
local FOE_BRAIN  = "../tests/brains/idle.lua"
local GRASS      = 7
local FILL_TICK  = 60            -- engine ticks: not before this
local SPAWN_WAIT = 20            -- engine ticks after our pond is filled
local LAND_WAIT  = 20            -- engine ticks after the foe is created
local p0         = 0

local last        = {}
local filled      = false
local traced      = nil          -- { {pill_index, tile_x, tile_y}, ... }
local foe_player  = nil
local foe_tick    = nil
local foe_landed  = false
local spawn_tried = false

local HOLD_HP = 10

local function same(p, t) return p.x == t[1] and p.y == t[2] end

-- Resolve OURS (tile coords) to PILL INDICES, once.  Everything after this
-- reads the pill BY INDEX and never by coordinate: a pill that is picked up
-- moves with the carrier, so a coordinate match would quietly stop finding it
-- at exactly the moment the trace exists to prove nobody took it.
local function resolve(g)
  local out = {}
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      for _, t in ipairs(OURS) do
        if same(p, t) then out[#out + 1] = { i, t[1], t[2] } end
      end
    end
  end
  return out
end

local function own_everything(g)
  for i = 1, g.num_pills() do
    if g.pill(i) then g.set_pill_owner(i, p0) end
  end
  for i = 1, g.num_bases() do
    if g.base(i) then
      g.set_base_owner(i, p0)
      g.set_base_stock(i, 90, 90, 90)
    end
  end
end

function on_setup(g)
  own_everything(g)
  g.set_team(p0, 0)
  local f = io.open(TRACE, "w")
  if f then f:write("# tick x y armour owner in_tank speed\n") f:close() end
end

-- START 1 IS OURS, START 2 IS EVERYBODY ELSE'S -- written that way round, and
-- NOT as `if p == foe_player then return 2 end`, because on_choose_start fires
-- DURING the g.spawn_bot call that creates the foe (scenario.c: the create path
-- runs inside serverSimCreateBot), i.e. before spawn_bot has returned and
-- before foe_player has been assigned.  A `foe_player`-keyed rule therefore
-- returns nil on the one placement that matters and the engine picks for
-- itself: measured on the first run of this arena, the idle bot landed on
-- start 1 -- OUR pond -- and heat_pill_select spent 300 ticks printing
-- d_us_enemy{0.0} SKIP:not_closer at an enemy sitting on our own hull.
function on_choose_start(g, p)
  if p == p0 then return 1 end
  -- Start 2 while the foe's pond is still water, start 3 once it has been
  -- filled in.  A start square is re-validated at every placement, so the
  -- filled tile stops being a legal spawn the moment it turns to grass.
  if foe_landed then return 3 end
  return 2
end

function on_tick(g, tick)
  -- 1. Our spawn pond, back to grass -- but only once the tank is ASHORE and
  --    off it.  Filling the tile while the tank still sits on it leaves the
  --    boat state stuck.
  if not filled and tick >= FILL_TICK then
    local tk = g.tank(p0)
    if tk and not tk.boat and not tk.dead
       and (tk.mx ~= SPAWN[1] or tk.my ~= SPAWN[2]) then
      filled = tick
      g.set_tile(SPAWN[1], SPAWN[2], GRASS)
      g.message(string.format(
        "HEAT_PILL_B2 filled the spawn pond at (%d,%d) with grass at t=%d",
        SPAWN[1], SPAWN[2], tick))
    end
  end

  -- 2. The enemy tank, once, and only after that: a volley started while we
  --    are still afloat on the pond brakes the tank and it never comes ashore.
  if filled and not spawn_tried and tick >= filled + SPAWN_WAIT then
    spawn_tried = true
    local s, err = g.spawn_bot("HeatFoe", FOE_BRAIN, 1, nil)
    if s == nil then
      g.message("HEAT_PILL_B2 spawn_bot failed: " .. tostring(err))
    else
      foe_player = s
      foe_tick = tick
      g.set_team(s, 1)
      g.message("HEAT_PILL_B2 foe slot=" .. tostring(s) .. " team=1 at t="
                .. tostring(tick))
      own_everything(g)
    end
  end

  -- 3. Put the enemy ashore, so one shell from our own pillbox cannot sink it
  --    out from under the volley.
  if foe_tick and not foe_landed and tick >= foe_tick + LAND_WAIT then
    local fk = g.tank(foe_player)
    if fk and fk.mx == FOE_SPAWN[1] and fk.my == FOE_SPAWN[2] then
      foe_landed = true
      g.set_tile(FOE_SPAWN[1], FOE_SPAWN[2], GRASS)
      g.message(string.format(
        "HEAT_PILL_B2 put the foe ashore at (%d,%d) at t=%d",
        FOE_SPAWN[1], FOE_SPAWN[2], tick))
    end
  end

  if not traced then traced = resolve(g) end

  -- Hold the pill at its staged armour: undo any repair the moment it lands.
  if traced and traced[1] then
    local idx = traced[1][1]
    local p = g.pill(idx)
    if p and not p.in_tank and (p.armour or 0) > HOLD_HP then
      g.set_pill_armour(idx, HOLD_HP)
    end
  end

  for _, e in ipairs(traced) do
    local p = g.pill(e[1])
    if p then
      local in_tank = p.in_tank and 1 or 0
      local sig = p.armour .. "/" .. p.owner .. "/" .. in_tank .. "/" .. p.speed
      if last[e[1]] ~= sig then
        local f = io.open(TRACE, "a")
        if f then
          f:write(string.format("%d %d %d %d %d %d %d\n",
                                tick, e[2], e[3], p.armour, p.owner, in_tank,
                                p.speed))
          f:close()
        end
        last[e[1]] = sig
      end
    end
  end
end
