-- GENERATED by tests/generate_kill_me_map.py -- do not edit by hand.
-- Scenario sidecar for tests/kill_me_D2.map (auto-loaded as <map>.scenario.lua).
-- Companion to tests/kill_me_test.py arena D2.
--
-- WHAT THIS SIDECAR IS FOR: it puts player 0 into the LOADED, BUILDER-LESS
-- state -- three pillboxes aboard and a builder who is never coming home --
-- and it does it with the only tools the scenario API has, set_tile and
-- give_pill.  There is no LGM teleport and the sidecar cannot read the man's
-- position at all, so his whereabouts are inferred from something the engine
-- publishes and the brain cannot fake: OUR PILL'S ARMOUR.  p0's only errand in
-- this arena is a top-up of the pill at (130,127), four armour down; when
-- game.pill() reports it at full the repair has landed, which means the man
-- walked to that tile and did the work there.  He is, at that instant, one
-- tile east of the gate.
--
-- THE GATE (x=128..129, y=126..128) then goes from FOREST to BUILDING, and that
-- is the whole stranding: lgm.c lgmReturn walks a straight line at the tank
-- with a per-axis slide and no re-route, so a full-height column he cannot
-- enter stops him for good.  The brain's own walk sim is that same straight
-- line, returns -1, and goals.lua's loaded_no_lgm reads a return ETA of STUCK.
--
-- WALL, NOT RIVER (which is what tests/stranded_lgm_A.scenario.lua floods
-- with).  River stops the MAN (MAP_MANSPEED_TRIVER 0) but not the TANK
-- (MAP_SPEED_TRIVER 3), and the stranded-LGM arena wants the rescue to stay
-- possible.  Here it must not be: measured on the first draft, the tank parked
-- on the river gate tile at t=1059 and the man simply walked up to it -- the
-- state ended 700 ticks after it started and there was nothing left to
-- measure.  A wall column ends the walk for good, in both directions.
--
-- ON THE SAME TICK the three pillboxes go aboard.  Order matters: give them
-- earlier and the bot places them instead of carrying them, and the errand
-- that walks the man out never happens.
--
-- TWO GUARDS ON THE FLOOD, both of which have to hold on the same tick:
--   * NEITHER tank is on the gate column, so we never drop a river under one;
--   * the pill is at full armour, still ours, and in nobody's tank -- an
--     armour rise on a pill that changed hands is not our repair.
-- AND A RETRY: when the two do not coincide the sidecar knocks the pill back
-- down to TOPUP_ARMOUR, the pool sends the man out again, and the next
-- completion is another chance.
--
-- TRACE.  Every change of ARMOUR, OWNER or IN_TANK on either of our pills,
-- plus the flood and every pill hand-out, is written to kill_me_D2_trace.log
-- in SIM ticks, so "the state was real" and "the corpses were taken" are asked
-- of the ENGINE and never of the brain's opinion of itself.
-- Rows are `tick x y armour owner in_tank`, one per CHANGE.

local TRACE     = "kill_me_D2_trace.log"
local P0, P1    = 0, 1
local P1_ENEMY  = false      -- arenas A/B: p1 is a hostile tank
local CORPSE_ON = false     -- arena E: pill 2 becomes a 0-armour body
local BUSY_P1   = false       -- arena D1: keep pill 2 damaged so p1's man walks
local NP_ON     = false         -- is the neutral pillbox on the map at all?
local KILL_LGM  = true      -- arenas C/D1/D2: kill p0's builder outright
                                  -- (game.kill_lgm) instead of walling him in
local last_dead0 = false          -- trace: p0's tank alive/dead edge
local GIVE_N    = 3               -- pills handed to p0 (>= LOADED_NO_LGM_MIN_PILLS)

local OURPILL   = { 130, 127 }
local CORPSE    = { 124, 129 }
local NEUTRAL   = { 124, 133 }
local SPAWN0    = { 126, 127 }
local SPAWN1    = { 122, 128 }
local GATE_X    = { 128, 129 }
local GATE_Y    = { 126, 127, 128 }
local FOREST    = 5
local RIVER     = 1
local WALL      = 0
local FILL_TICK = 60
local TOPUP_ARMOUR = 11

local last = {}
local filled0, filled1 = false, false
local walled = false
local retry_at = nil
local REDAMAGE_AFTER = 8
local gave = false
local traced = nil
local idx_our, idx_corpse, idx_neutral = nil, nil, nil
local spares = {}

local function same(p, t) return p.x == t[1] and p.y == t[2] end

local function note(line)
  local f = io.open(TRACE, "a")
  if f then f:write(line .. "\n") f:close() end
end

-- Resolve tiles to PILL INDICES once. Everything after this reads the pill BY
-- INDEX: a pill that is picked up moves with its carrier, so a coordinate
-- match would stop finding it exactly when the trace exists to prove nobody
-- took it.
local function resolve(g)
  spares = {}
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      if same(p, OURPILL)     then idx_our = i
      elseif same(p, CORPSE)  then idx_corpse = i
      elseif same(p, NEUTRAL) then idx_neutral = i
      else spares[#spares + 1] = i end
    end
  end
  return (idx_our ~= nil)
end

function on_setup(g)
  resolve(g)
  for i = 1, g.num_pills() do
    if i == idx_neutral then
      g.set_pill_owner(i, g.NEUTRAL)
    else
      g.set_pill_owner(i, P0)
    end
  end
  for i = 1, g.num_bases() do
    g.set_base_owner(i, P0)
    g.set_base_stock(i, 90, 90, 90)
  end
  -- The second friendly pill is scenery in most arenas: a live pill inside the
  -- room invites defend/repair goals that have nothing to do with what is
  -- being measured.  hide_pill takes it off the map entirely.
  -- THE NEUTRAL IS A TRADE, and each arena picks its side of it.
  --   ON  : its PILL_RANGE_MAP(9) danger stamp covers every tank-reachable
  --         tile, which is what keeps rescue_lgm suppressed under the pinned
  --         static gate (perc.under_fire = danger_at(tile) > 0) once the man
  --         is stranded.  The same stamp makes threat.pill_at(tank tile) > 0,
  --         which fires haul_flee_eval's pill_shooting trigger for a tank
  --         carrying pills with its builder out -- so take_cover owns the
  --         pool at HAUL_FLOOR and the ESCAPE half of the feature is exactly
  --         what gets measured.  Arenas A, B, E, EK.
  --   OFF : nothing stamps danger, so haul_flee_eval is quiet and the
  --         kill_me_wait row can actually bid.  Arenas C, D1, D2.
  if not NP_ON and idx_neutral then g.hide_pill(idx_neutral) end
  if idx_corpse then
    if CORPSE_ON then
      -- Arena E's body is HIDDEN until the state starts. Put it on the ground
      -- at setup and the bot drives over it in the first hundred ticks, long
      -- before it is loaded and builder-less, and there is nothing left to
      -- price. show_pill puts a hidden pill back DEAD, which is exactly the
      -- state a capture wants, so the corpse appears on the wall tick.
      g.hide_pill(idx_corpse)
    elseif BUSY_P1 then
      g.set_pill_armour(idx_corpse, TOPUP_ARMOUR)   -- arena D1: p1's errand
    else
      g.hide_pill(idx_corpse)
    end
  end
  -- The spares are carry-slots, not pillboxes: off the map until the flood.
  for _, i in ipairs(spares) do g.hide_pill(i) end
  local f = io.open(TRACE, "w")
  if f then f:write("# tick x y armour owner in_tank\n") f:close() end
end

function on_choose_start(g, p)
  if p == P0 then return 1 end
  if p == P1 then return 2 end
  return nil
end

function on_tick(g, tick)
  -- ALLIANCE, APPLIED FROM on_tick.  botManagerSetTeams walks the bots'
  -- OWN ClientSim alliance tables, and at on_setup time no bot exists yet --
  -- so a set_team there reaches the server's roster and nothing else, and the
  -- two bots still read each other as OBJECT_HOSTILE (measured: arena C's
  -- would-be ally opened with `attack_tank #1`).  Re-applied for the first
  -- ALLY_TICKS ticks so it lands whenever the slots actually come up.
  if tick <= 120 then
    g.set_team(P0, 0)
    g.set_team(P1, P1_ENEMY and 1 or 0)
  end
  -- Fill the spawn ponds once each tank is ASHORE and off its boat. Filling
  -- the tile while the tank still sits on it leaves the boat state stuck and
  -- the LGM never becomes available.
  if tick >= FILL_TICK then
    if not filled0 then
      local tk = g.tank(P0)
      if tk and not tk.boat and not tk.dead
         and (tk.mx ~= SPAWN0[1] or tk.my ~= SPAWN0[2]) then
        filled0 = true
        g.set_tile(SPAWN0[1], SPAWN0[2], FOREST)
        note(string.format("# pondfill0 %d", tick))
      end
    end
    if not filled1 then
      local tk = g.tank(P1)
      if tk and not tk.boat and not tk.dead
         and (tk.mx ~= SPAWN1[1] or tk.my ~= SPAWN1[2]) then
        filled1 = true
        g.set_tile(SPAWN1[1], SPAWN1[2], FOREST)
        note(string.format("# pondfill1 %d", tick))
      end
    end
  end

  if not traced then
    traced = resolve(g) and true or false
    if not traced then return end
  end

  -- THE FLOOD + THE HAND-OUT.  Full armour on a pill that is still ours and
  -- not in a tank means the man is standing on (130,127), east of the gate.
  -- Both tanks have to be off the gate column on the same tick.
  -- THE FLOOD: ONE COLUMN, THE FAR ONE.
  --
  -- Fired on the exact tick the engine reports the pill full -- the man is
  -- standing on (130,127) at that instant and nowhere else, so this is the
  -- one tick where his side of the gate is known.
  --
  -- The gate is TWO columns wide and only the EAST one (x=129) is walled.
  -- That is the whole trick, and it took three drafts:
  --   * the tank's cheapest reachable tile to the errand pill is always the
  --     tile NEXT to it, so a one-column gate is a column the tank is parked
  --     on at every single completion -- and walling under a tank freezes it
  --     (MAP_SPEED_TBUILDING is 0), so that flood could never fire at all;
  --   * flooding with RIVER instead needs no guard (the tank drives on, the
  --     man cannot enter at all), but it leaves the tank able to sit ONE tile
  --     from the man, and lgm.c lgmReturn boards him from there -- measured,
  --     the man was home 160 ticks after the flood;
  --   * and walling the FAR column does not strand him either: a live pillbox
  --     is MANSPEED 0, so the man never stands ON the errand pill -- he stands
  --     BESIDE it, on the far gate column, and a wall laid under his feet is a
  --     wall he simply steps west out of.
  -- So the NEAR column (x=128) is the one that gets walled, which leaves the
  -- man loose in the four-tile pocket east of it (the far column plus the pill
  -- tile) with no way out and no way for a tank to reach him.
  --
  -- The guard is therefore "neither tank is east of the room", and when it
  -- fails the pill goes back down to TOPUP_ARMOUR so the pool sends the man
  -- out again and the next completion is another attempt.
  -- THE KILL (arenas C/D1/D2). game.kill_lgm puts p0's man through the
  -- engine's own death path (lgm.c lgmDeathCheckAtPosition): he is choppered
  -- in from a start tile and walks home, exactly as a shell would have left
  -- him. Re-applied every tick afterwards so he dies again the moment he
  -- lands: the arena is seven tiles wide and one death would only buy a few
  -- hundred ticks of the state. The first kill flips `walled`, which is the
  -- latch the hand-out below already waits on.
  if KILL_LGM and traced and filled0 and filled1 and tick >= FILL_TICK + 100 then
    local killed = g.kill_lgm(P0)
    if killed and not walled then
      walled = true
      note(string.format("# kill %d", tick))
      g.message(string.format("KILL_ME_D2: p0's builder killed at t=%d", tick))
    end
  end
  local p = idx_our and g.pill(idx_our)
  if not KILL_LGM and p and not walled and p.armour >= 15 and not p.in_tank and p.owner == P0 then
    local t0 = g.tank(P0)
    local t1 = g.tank(P1)
    local clear0 = (not t0) or t0.dead or t0.mx < GATE_X[1]
    local clear1 = (not t1) or t1.dead or t1.mx < GATE_X[1]
    if clear0 and clear1 then
      walled = true
      for _, gy in ipairs(GATE_Y) do
        g.set_tile(GATE_X[1], gy, WALL)
      end
      note(string.format("# wall %d tank0=(%s,%s)", tick,
                         t0 and tostring(t0.mx) or "?", t0 and tostring(t0.my) or "?"))
      g.message(string.format(
        "KILL_ME_D2: gate column x=%d walled at t=%d -- p0's man is cut off",
        GATE_X[1], tick))
    else
      retry_at = retry_at or (tick + REDAMAGE_AFTER)
      if tick >= retry_at then
        g.set_pill_armour(idx_our, TOPUP_ARMOUR)
        retry_at = nil
        note(string.format("# retry %d tank0=(%s,%s)", tick,
                           t0 and tostring(t0.mx) or "?", t0 and tostring(t0.my) or "?"))
      end
    end
  end

  -- KEEP THE WALL UP. A BUILDING tile is not permanent: a shell that misses
  -- chews it to HALFBUILDING and then to RUBBLE, and both tanks spend the run
  -- firing in a seven-tile room. Re-stamping the column every tick costs
  -- nothing and stops a stray round from re-opening the pocket halfway
  -- through the measurement (measured: the man was loose again 400 sim ticks
  -- after the wall went up).
  if walled and not KILL_LGM then
    for _, gy in ipairs(GATE_Y) do
      g.set_tile(GATE_X[1], gy, WALL)
    end
  end

  -- The pills go aboard on the flood tick, never before: hand them over early
  -- and the bot places them instead of carrying them, and the errand that
  -- walks the man out never happens at all.
  if walled and not gave then
    gave = true
    local n = 0
    for _, i in ipairs(spares) do
      if n < GIVE_N then
        -- show_pill puts a hidden pill back where it was hidden, DEAD; that
        -- tile is a walled-in road square nothing can reach, so the pill
        -- exists on the map only for the instant between these two calls.
        g.show_pill(i)
        g.set_pill_owner(i, P0)
        if g.give_pill(P0, i) then n = n + 1 else g.hide_pill(i) end
      end
    end
    -- Arena E: the body appears now, with the state, not at setup.
    if CORPSE_ON and idx_corpse then
      g.show_pill(idx_corpse)
      g.set_pill_owner(idx_corpse, P0)
      note(string.format("# corpse %d", tick))
    end
    note(string.format("# gave %d n=%d", tick, n))
    g.message(string.format("KILL_ME_D2: %d pillbox(es) loaded into p0 at t=%d",
                            n, tick))
  end

  -- Arena D1 only: keep p1's errand alive so its builder keeps walking, which
  -- is what makes the responder row read no_lgm.
  if BUSY_P1 and idx_corpse then
    local c = g.pill(idx_corpse)
    if c and c.armour >= 15 and not c.in_tank then
      g.set_pill_armour(idx_corpse, TOPUP_ARMOUR)
    end
  end

  -- ENGINE-SIDE TRACE of both our pills plus every pill that ends up on the
  -- ground: arena C proves the hand-off by watching corpses appear with p0's
  -- ownership and then go in_tank under p1.
  -- p0's tank alive/dead edge: arena C proves the hand-off landed by seeing
  -- p0 die while the request was live.
  local t0d = g.tank(P0)
  if t0d and (t0d.dead and true or false) ~= last_dead0 then
    last_dead0 = t0d.dead and true or false
    note(string.format("# p0dead %d %s", tick, tostring(last_dead0)))
  end
  for i = 1, g.num_pills() do
    if i ~= idx_neutral then
      local q = g.pill(i)
      if q then
        local in_tank = q.in_tank and 1 or 0
        local sig = q.armour .. "/" .. q.owner .. "/" .. in_tank .. "/" .. q.x .. "," .. q.y
        if last[i] ~= sig then
          note(string.format("%d %d %d %d %d %d", tick, q.x, q.y,
                             q.armour, q.owner, in_tank))
          last[i] = sig
        end
      end
    end
  end
end
