-- Scenario sidecar for tests/mine_hoard_B.map -- GENERATED by
-- tests/generate_mine_hoard_map.py, do not edit by hand.
--
-- Stages a tank that is PARKED on its own base, still below a target, and
-- carrying 23 mines -- the shape of the 20260905_231835 bot2 incident --
-- then hands it to the variant.
--
-- The engine refuels armour, THEN shells, THEN mines (bases.c basesRefueling),
-- one item per half-tick, and there is no set_tank_stock in the scenario API.
-- So the only way to a mine-heavy tank that is NOT full of shells is to take
-- the PAD's shells away and let the mine branch run.  Phases:
--
--   1 SHELLS  pad (90, 90, 0) until the tank holds 20 shells
--             (20 == SHELLS_LOW, pinned by cfg: fill 0, mult 1.00,
--             deficit bonus 0, so the printed refuel cost is the bare cached
--             cost and the mine surcharge is the only moving part).
--   2 MINES   pad (90, 0, 90); shells held at 0 so the engine's shell
--             branch is skipped and mines flow.  Until the tank holds 23.
--   3 FREEZE  pad (90, 0, 0), held 500 ticks.  Nothing moves: the
--             tank sits on the pad at armour 40 / shells 20 / mines
--             23.  The pad still has ARMOUR (90 raw = 18 in the
--             engine's brain units, bases.c basesGetBrainBaseItem divides by
--             five) and the bot's armour target is 45 (cfg=TANK_FULL_ARMOUR),
--             so the pad can still supply something the tank is short of.
--   4 TEST    variant B: pad held at (0, 0, 90) -- nothing left but mines
--
-- THE FAR BASE (136,122) IS HELD FULL THROUGHOUT, in every phase.  It is
-- the competing goal: while the tank is parked on the pad it costs
-- travel + REFUEL_BASE_COST + REFUEL_BASE_HOP_PENALTY(500), which loses to a
-- waived pad and beats a mine-charged one.
--
-- The engine regenerates base stock on its own (bases.c basesUpdateStock), so
-- every phase RE-ASSERTS stock whenever it has crept -- only when it actually
-- changed, or the log is one base-stock event per tick.
--
-- NOTE these are ENGINE ticks.  on_tick counts engine ticks and a brain thinks
-- every second one, so everything here is twice the number the brain's own t=
-- shows.
--
-- Also: pin the starts (on_choose_start fires for every placement, so player p
-- always gets start p+1), and fill the one-tile spawn ponds once every tank is
-- ashore -- a start square has to be DEEP SEA, and a tank that later drives
-- over one without a boat drowns instantly.
local FULL      = 90
local SHELLS    = 20
local MINES     = 23
local OWNER     = 0
local FREEZE    = 500
local PADX      = 126
local PADY      = 122
local PONDS     = { { 126, 118 }, { 96, 112 } }
local GRASS     = 7
local VARIANT   = "B"
local ponds_filled = false
local phase        = 1
local freeze_tick  = -1
-- Which base is the pad?  Matched on coordinates, not on index, so a change to
-- the map's base order cannot silently point the staging at the wrong one.
local function is_pad(b) return b.x == PADX and b.y == PADY end
-- Set the pad outright.  `mines` may be nil for "leave the pad's mines alone"
-- (phase 2 lets the tank drain them and must not fight it).
local function set_pad(g, armour, shells, mines)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b and is_pad(b) then
      g.set_base_stock(i, armour, shells, mines or (b.mines or 0))
    end
  end
end
-- Re-assert the pad and hold every OTHER base full, but only where the stock
-- has actually drifted -- the server emits EVENT_BASE_STOCK on every write and
-- an unconditional re-assert would be one event per tick.
local function hold(g, armour, shells, mines)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      local wa, ws, wm
      if is_pad(b) then
        wa, ws, wm = armour, shells, mines
      else
        wa, ws, wm = FULL, FULL, 0
      end
      local drift = (b.armour or 0) ~= wa or (b.shells or 0) ~= ws
      if wm ~= nil and (b.mines or 0) ~= wm then drift = true end
      if drift then g.set_base_stock(i, wa, ws, wm or (b.mines or 0)) end
    end
  end
end
function on_choose_start(g, p)
  local n = p + 1
  if n >= 1 and n <= g.num_starts() then return n end
  return nil
end
function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      g.set_base_stock(i, FULL, FULL, 0)
      g.message(string.format(
        "MINE_HOARD_ARENA base#%d (%d,%d) owner=%d armour=%d shells=%d mines=0 %s",
        i, b.x, b.y, OWNER, FULL, FULL, is_pad(b) and "PAD" or "FAR"))
    end
  end
  g.message(string.format(
    "MINE_HOARD_ARENA variant=%s pills=%d bases=%d starts=%d stage_shells=%d stage_mines=%d",
    VARIANT, g.num_pills(), g.num_bases(), g.num_starts(), SHELLS, MINES))
end
function on_tick(g, tick)
  local t = g.tank(0)
  if phase == 1 then
    -- Armour is already full (TOURNAMENT spawns at the engine's 40), so the
    -- engine pours shells.  Mines stay 0 in the pad: the tank must not pick
    -- any up before it is holding exactly SHELLS shells.
    hold(g, FULL, FULL, 0)
    if t and (t.shells or 0) >= SHELLS then
      phase = 2
      set_pad(g, FULL, 0, FULL)
      g.message(string.format(
        "MINE_HOARD_ARENA PHASE2_MINES tick=%d tank sh=%d mn=%d",
        tick, t.shells or -1, t.mines or -1))
    end
  elseif phase == 2 then
    -- Shells held at 0 (blocks the engine's shell branch); the pad's mines are
    -- left alone so the tank can actually drain them.
    hold(g, FULL, 0, nil)
    if t and (t.mines or 0) >= MINES then
      phase = 3
      freeze_tick = tick
      set_pad(g, FULL, 0, 0)
      g.message(string.format(
        "MINE_HOARD_ARENA PHASE3_FREEZE tick=%d tank arm=%d sh=%d mn=%d",
        tick, t.armour or -1, t.shells or -1, t.mines or -1))
    end
  elseif phase == 3 then
    hold(g, FULL, 0, 0)
    if tick >= freeze_tick + FREEZE then
      phase = 4
      if VARIANT == "A" then
        -- The pad can supply the shells the tank is short of.
        set_pad(g, FULL, FULL, 0)
        g.message("MINE_HOARD_ARENA PHASE4_RESTOCK tick=" .. tostring(tick))
      else
        -- Nothing left but mines.
        set_pad(g, 0, 0, FULL)
        g.message("MINE_HOARD_ARENA PHASE4_DRY tick=" .. tostring(tick))
      end
    end
  else
    if VARIANT == "A" then
      hold(g, FULL, FULL, 0)
    else
      hold(g, 0, 0, nil)
    end
  end
  if not ponds_filled and tick > 200 then
    local afloat = false
    for p = 0, g.max_tanks() - 1 do
      local tk = g.tank(p)
      if tk and tk.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("MINE_HOARD_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end
