-- Scenario sidecar for tests/place_pin_near.map -- GENERATED by
-- tests/generate_place_pin_map.py, do not edit by hand.
--
-- Four jobs.
--
-- 1. OWN the base and all three pills, and put our tank on its own team so the
--    scripted opponents are hostile to it.
--
-- 2. PIN THE STARTS.  on_choose_start fires for every placement (spawn AND
--    respawn), so each tank always comes back on the pond this arena designed
--    for it -- start 1 ours, start 2 the patrol.
--
-- 3. HAND OVER THE PILLS at tick 200.  Three aboard is what makes the
--    carry pressure real: place_pill_strategic's cost collapses, and whether
--    it is allowed to WIN with that cost is the whole question.
--
-- 4. FILL THE SPAWN PONDS once nobody is afloat.  A start square has to be
--    deep sea, and a tank that later drives over one without a boat drowns --
--    noise this test does not want.

local OUR_PLAYER = 0
local PILL_IDS   = { 1, 2, 3 }
local PONDS      = { { 138, 126 }, { 133, 112 } }
local GIVE_TICK  = 200
local GRASS      = 7
local given = false
local ponds_filled = false

function on_setup(g)
  for i = 1, g.num_pills() do g.set_pill_owner(i, OUR_PLAYER) end
  for i = 1, g.num_bases() do g.set_base_owner(i, OUR_PLAYER) end
  g.set_team(OUR_PLAYER, 0)
  g.message(string.format("PLACE_PIN_ARENA pills=%d give=%d",
                          g.num_pills(), GIVE_TICK))
end

function on_choose_start(g, p)
  if p == 0 then return 1 end      -- ours
  if p == 1 then return 2 end      -- the patrol
  return nil
end

function on_tick(g, tick)
  if not given and tick >= GIVE_TICK then
    given = true
    local n = 0
    for _, i in ipairs(PILL_IDS) do
      local ok, err = g.give_pill(OUR_PLAYER, i)
      if ok then n = n + 1
      else g.message("PLACE_PIN_ARENA give_pill#" .. i .. " failed: "
                     .. tostring(err)) end
    end
    g.message("PLACE_PIN_ARENA gave " .. n .. " pill(s) at tick " .. tick)
  end
  if not ponds_filled and tick > 200 then
    local afloat = false
    for p = 0, 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("PLACE_PIN_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end
