-- Scenario sidecar for tests/refuel_lowstock.map -- GENERATED by
-- tests/generate_refuel_lowstock_map.py, do not edit by hand.
--
-- Three jobs.
--
-- 1. OWN BOTH BASES, and set their stock.  The bases are already written into
--    the map file as slot 0's, but on_setup re-asserts it so the intent is
--    in one place -- and it is the only place the stock lives:
--      BASE_NEAR  armour 4 (below REFUEL_MIN_STOCK -> marked up),
--                 shells 6  (at/above it -> survives the low_stock reject)
--      BASE_FAR   armour 90 shells 90
--
-- 2. KEEP THE STOCK READING FRESH.  The markup only prices a base whose
--    observation is younger than REFUEL_OBS_STALE (500 ticks), and a bot only
--    learns base stock from EVENT_BASE_STOCK, which the server emits ONLY when
--    a base's armour/shells/mines actually CHANGE.  So every 150 ticks this
--    re-asserts the stock with a mines value that alternates 90/89 -- a real
--    change, so a real event.  It also puts the stock back, which is
--    deliberate: the near base has to stay pinned even while the tank drinks.
--
-- 3. FILL THE SPAWN PONDS once both tanks are ashore.  A start square has to
--    be DEEP SEA (starts.c startsIsValidSquare), so the arena has two one-tile
--    ponds sitting in grass.  A tank that later drives over one without a boat
--    drowns instantly -- noise this test does not want -- so once neither tank
--    is afloat the ponds become grass.
local NEAR   = { 120, 131 }
local FAR    = { 120, 118 }
local FULL   = 90
local NEAR_SH  = 6
local NEAR_ARM = 4
local OWNER  = 0
local PERIOD = 150
local PONDS  = { { 126, 127 }, { 110, 112 } }
local GRASS  = 7
local flip = 0
local ponds_filled = false
-- armour, shells for one base.  BASE_NEAR is the only one that varies.
local function stock_for(b)
  if b.x == NEAR[1] and b.y == NEAR[2] then return NEAR_ARM, NEAR_SH end
  return FULL, FULL
end
local function assert_stock(g)
  flip = 1 - flip
  local mines = 90 - flip
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      local arm, sh = stock_for(b)
      g.set_base_stock(i, arm, sh, mines)
    end
  end
end
function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      local arm, sh = stock_for(b)
      g.set_base_stock(i, arm, sh, 90)
      g.message(string.format(
        "REFUEL_LOWSTOCK_ARENA base#%d (%d,%d) owner=%d armour=%d shells=%d",
        i, b.x, b.y, OWNER, arm, sh))
    end
  end
end
function on_tick(g, tick)
  if tick > 0 and tick % PERIOD == 0 then assert_stock(g) end
  -- Fill the ponds as soon as nobody is afloat any more (see note 3).
  if not ponds_filled and tick > 200 then
    local afloat = false
    for p = 0, 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("REFUEL_LOWSTOCK_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end
