-- Scenario sidecar for tests/refuel_topoff_B.map -- GENERATED by
-- tests/generate_refuel_topoff_map.py, do not edit by hand.
--
-- Four jobs.
--
-- 0. ALLY ONLY THE SLOTS THAT SHOULD BE ALLIED (variant B's idle teammate),
--    from on_tick rather than on_setup because the bots are still joining at
--    setup time.  The scripted opponent must stay hostile or refuel_shape
--    counts it in the team size and prices variant A like variant B.
--
-- 1. PIN THE STARTS.  on_choose_start fires for every placement, so player p
--    always gets start p+1: the bot at (126,118) beside the base, the
--    unreachable opponent on the island, and (variant B) the idle teammate in
--    the far corner.  Without it startsGetStartTournament is free to hand the
--    bot any start with an own base within 9 tiles.
--
-- 2. PHASE 1 -- stop the drink at exactly 30 shells.  The tank spawns with
--    0 (TOURNAMENT + -ranked; -ranked is required because
--    serverSimApplyScenarioCommit otherwise stamps gameScripted over the game
--    type of any map with a sidecar, and gameScripted hands out a full tank).
--    The moment it reaches 30 the base's shells go to 0 and are HELD there
--    until the restock: the engine regenerates base stock by itself
--    (bases.c basesUpdateStock), so seeding the base with 30 and walking
--    away is not enough -- the tank just keeps drinking to 40.  Held at 0,
--    the base can supply nothing the tank needs (its armour is already full),
--    so the brain blocks it as base_useless and the tank leaves with 30
--    shells: above SHELLS_LOW (20), below the shell target (40).
--
-- 3. PHASE 2 -- 600 ticks after the drain the base is refilled to
--    90/90 and re-asserted every 150 ticks, with the ARMOUR value
--    alternating
--    90/89 because the server only emits EVENT_BASE_STOCK when a
--    base's stock actually CHANGES and the bot's observation has to stay
--    fresh.  NOTE these are ENGINE ticks -- on_tick counts engine ticks and a
--    brain thinks every second one, so everything here is twice the number the
--    brain's own t= shows.  Mines are held at 0 throughout: the tank must never pick any up,
--    or refuel_shape's exponential mine-hoard surcharge joins the cost and the
--    multiplier stops being hand-computable.
--
-- 4. FILL THE SPAWN PONDS once every tank is ashore.  A start square has to be
--    DEEP SEA, so the arena digs one-tile ponds in the grass; a tank that
--    later drives over one without a boat drowns instantly.
local FULL     = 90
local P1SH     = 30
local OWNER    = 0
local TEAM     = 0
local ALLIED   = { 0, 2 }   -- player slots put on one team (empty in A)
local DRY      = 600
local PERIOD   = 150
local PONDS    = { { 126, 118 }, { 96, 112 }, { 152, 138 } }
local GRASS    = 7
local flip = 0
local allied_done = (#ALLIED == 0)
local ponds_filled = false
local drained = false
local drain_tick = -1
local restocked = false
local function set_all(g, armour, shells)
  for i = 1, g.num_bases() do g.set_base_stock(i, armour, shells, 0) end
end
function on_choose_start(g, p)
  local n = p + 1
  if n >= 1 and n <= g.num_starts() then return n end
  return nil
end
function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      g.set_base_stock(i, FULL, FULL, 0)
      g.message(string.format(
        "REFUEL_TOPOFF_ARENA base#%d (%d,%d) owner=%d armour=%d shells=%d mines=0",
        i, b.x, b.y, OWNER, FULL, FULL))
    end
  end
  g.message(string.format(
    "REFUEL_TOPOFF_ARENA pills=%d starts=%d phase1_shells=%d dry_ticks=%d",
    g.num_pills(), g.num_starts(), P1SH, DRY))
end
function on_tick(g, tick)
  -- ONLY the listed slots are allied, and NOT from on_setup: the bots are
  -- still joining there and g.tank(2) is nil, so the ally silently stayed on
  -- its own team and variant B priced exactly like variant A.  Retried from
  -- on_tick until every listed slot has a tank.
  if not allied_done then
    local all = true
    for _, p in ipairs(ALLIED) do
      if g.tank(p) then g.set_team(p, TEAM) else all = false end
    end
    if all then
      allied_done = true
      if #ALLIED > 0 then
        g.message("REFUEL_TOPOFF_ARENA allied slots on team " .. tostring(TEAM)
                  .. " at tick " .. tostring(tick))
      end
    end
  end
  if not drained then
    local t = g.tank(0)
    if t and (t.shells or 0) >= P1SH then
      drained = true
      drain_tick = tick
      set_all(g, FULL, 0)
      g.message(string.format("REFUEL_TOPOFF_ARENA DRAINED tick=%d tank_shells=%d",
                              tick, t.shells or -1))
    end
  elseif not restocked then
    if tick >= drain_tick + DRY then
      restocked = true
      set_all(g, FULL, FULL)
      g.message("REFUEL_TOPOFF_ARENA RESTOCK tick=" .. tostring(tick))
    else
      -- Beat the engine's own stock regeneration back down.  Only when it has
      -- actually crept up, so the log is not one base-stock event per tick.
      for i = 1, g.num_bases() do
        local b = g.base(i)
        if b and (b.shells or 0) > 0 then g.set_base_stock(i, FULL, 0, 0) end
      end
    end
  else
    if tick % PERIOD == 0 then
      flip = 1 - flip
      set_all(g, FULL - flip, FULL)
    end
  end
  if not ponds_filled and tick > 200 then
    local afloat = false
    for p = 0, g.max_tanks() - 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("REFUEL_TOPOFF_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end
