-- Scenario sidecar for tests/refuel_pad_reach_A.map -- GENERATED by
-- tests/generate_refuel_pad_reach_map.py, do not edit by hand.
--
-- Two jobs.
--
-- 1. OWN BOTH BASES AND KEEP THEM FULL.  They are already slot 0's in the
--    map file, but on_setup re-asserts it so the intent lives in one place.
--    Both hold armour 90 / shells 90: neither is ever rejected as low
--    on stock and neither carries a low-stock markup, so travel and the DANGER
--    term are the only things telling the two bases apart -- which is the whole
--    point of the arena.  Re-asserted every 150 ticks with a mines value
--    that alternates 90/89, because the server only emits EVENT_BASE_STOCK when
--    a base's stock actually CHANGES and the bot's observation has to stay
--    fresh (and topped back up while the tank drinks).
--
-- 2. FILL THE SPAWN PONDS once both tanks are ashore.  A start square has to be
--    DEEP SEA (starts.c startsIsValidSquare), so the arena has two one-tile
--    ponds sitting in grass.  A tank that later drives over one without a boat
--    drowns instantly -- noise this test does not want.
local FULL   = 90
local OWNER  = 0
local PERIOD = 150
local PONDS  = { { 126, 118 }, { 96, 112 } }
local GRASS  = 7
local flip = 0
local ponds_filled = false
local function assert_stock(g)
  flip = 1 - flip
  local mines = 90 - flip
  for i = 1, g.num_bases() do
    g.set_base_stock(i, FULL, FULL, mines)
  end
end
function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      g.set_base_stock(i, FULL, FULL, 90)
      g.message(string.format(
        "REFUEL_PAD_ARENA base#%d (%d,%d) owner=%d armour=%d shells=%d",
        i, b.x, b.y, OWNER, FULL, FULL))
    end
  end
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      g.message(string.format(
        "REFUEL_PAD_ARENA pill#%d (%d,%d) owner=%s health=%s",
        i, p.x, p.y, tostring(p.owner), tostring(p.armour)))
    end
  end
end
function on_tick(g, tick)
  if tick > 0 and tick % PERIOD == 0 then assert_stock(g) end
  if not ponds_filled and tick > 200 then
    local afloat = false
    for p = 0, 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("REFUEL_PAD_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end
