-- Scenario sidecar for tests/reserve_seeded.map -- GENERATED by
-- tests/generate_reserve_seeded_map.py, do not edit by hand.
--
-- 1. LOADOUT.  A map with a sidecar boots as gameScripted, and
--    gameTypeGetItems treats gameScripted exactly like OPEN (40 shells / 40
--    mines / 40 trees) -- neither -gametype nor scenario.game reaches a -bots
--    tank.  game.spawn_bot's mode argument is the one thing that does
--    (scenario.c arms sim->spawnLoadout for the slot before tankCreate runs),
--    so the `gather` variant runs with -bots 0 and spawns its own tank in
--    STRICT mode to get a tank with no wood at all.  `seeded` wants the full
--    40 trees, so it just uses the -bots tank.
--
-- 2. Own everything, so no pill on the map is a capture or attack candidate.
--
-- 3. At tick 200, hand 9 pill(s) to the tank.  That is the whole
--    experiment: what the tank is CARRYING is what the old reserve priced
--    against every job it wanted to do.

local OUR_SLOT   = 0     -- -1 until spawn_bot answers, in `gather`
local SPAWN_MODE = nil     -- nil = use the -bots tank as it spawned
local GIVE_IDS   = { 2, 3, 4, 5, 6, 7, 8, 9, 10 }  -- pill numbers to load into the tank
local N_GIVE     = 9    -- how many to make up in `gather` (no map pills)
local GIVE_TICK  = 200
local slot = OUR_SLOT
local spawn_tried = false
local given = false

local function own_everything(g, owner)
  for i = 1, g.num_pills() do g.set_pill_owner(i, owner) end
  for i = 1, g.num_bases() do g.set_base_owner(i, owner) end
end

function on_setup(g)
  own_everything(g, OUR_SLOT >= 0 and OUR_SLOT or 0)
  g.message(string.format("RESERVE_ARENA pills=%d bases=%d give=%d@%d mode=%s",
                          g.num_pills(), g.num_bases(), N_GIVE, GIVE_TICK,
                          tostring(SPAWN_MODE)))
end

function on_tick(g, tick)
  if SPAWN_MODE and not spawn_tried and tick >= 2 then
    spawn_tried = true
    local s, err = g.spawn_bot("Reserve", nil, 0, SPAWN_MODE)
    if s == nil then
      g.message("RESERVE_ARENA spawn_bot failed: " .. tostring(err))
    else
      slot = s
      g.message("RESERVE_ARENA spawned slot=" .. tostring(s)
                .. " mode=" .. SPAWN_MODE)
      own_everything(g, s)
    end
  end
  if not given and slot >= 0 and tick >= GIVE_TICK then
    given = true
    local n = 0
    for _, i in ipairs(GIVE_IDS) do
      local ok, err = g.give_pill(slot, i)
      if ok then n = n + 1
      else g.message("RESERVE_ARENA give_pill#" .. i .. " failed: "
                     .. tostring(err)) end
    end
    g.message("RESERVE_ARENA gave " .. n .. " pill(s) to slot " .. slot
              .. " at tick " .. tick)
  end
end
