#!/usr/bin/env python3
"""
Every bot gets a FRESH Lua brain at each round start (bot_manager.c
botManagerOnGameStart -> botManagerReloadBrain).

WHY
    The old round-start path kept the lua_State and only flagged isFirst,
    which GoalHunter treats as a RESPAWN: its whole `state` table survived
    the round boundary -- tick counter, goal, last-known base/pill owners,
    influence -- so a game opened with the bot chasing a base from the
    previous map at brain tick ~1000 (debug session 20260903_030637 bot2,
    t=1087, goal refuel_at_base #8 (109,137) on a map whose base #8 is at
    (114,140)).

HOW THE TEST DRIVES TWO ROUNDS HEADLESSLY
    -maprotate -mapdir <dir> is the no-lobby round-rotation mode: a win drives
    the round to game-over and the lifecycle starts the next round on the
    next map in the dir instead of quitting.  The dir holds ONE map with a
    scenario script whose on_tick calls game.end_round() at ROUND_TICKS, so
    the round ends on a timer and the server rotates onto the same map.
    -ticks caps the whole run.

    The bot runs tests/brains/round_reset_count.lua, whose think counter is a
    module-level local: it prints "think=1" only when the file has been run
    in a NEW lua_State.  print() from a brain goes to wb_log ("lua" category,
    debug level), so WINBOLO_LOG="lua=debug,sim=info" puts both the brain's
    lines and bot_manager's "reloaded with brain" lines on the console.

CHECKS
    1. At least two rounds ran (two "on_setup"-era markers: the script
       prints ROUND_RESET_SCENARIO round=N via game.message... which goes to
       players, not the console -- so the round count is taken from the
       brain instead: "ROUND_RESET_BRAIN open" appears >= 2 times).
    2. bot_manager logged "bot 0 reloaded with brain" at least once.
    3. The brain's think counter restarted: "think=1" appears >= 2 times, and
       the sequence of think= values is not monotonic (it drops back).
    4. The old state was closed properly: "close after N thinks" appears
       before the second "open".

Usage: python round_reset_test.py [--build DIR] [--no-asap]
Exit 0 on pass.
"""
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, ValueError):        # pragma: no cover
    pass

from asap import asap_args, pacing_line, take_asap_flag  # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
DEFAULT_BUILD = REPO / "build"
BRAIN = HERE / "brains" / "round_reset_count.lua"
SRC_MAP = REPO / "data" / "maps" / "Everard Island.map"
PORT = 50131
ROUND_TICKS = 400          # server ticks per round before end_round()
RUN_SECONDS = 8            # wall clock; -asap turns ~400 ticks in < 1 s
LABEL = "round_reset_test"

SCRIPT = """\
-- GENERATED by tests/round_reset_test.py: end every round after a fixed
-- number of ticks so -maprotate starts the next one.
local ROUND_TICKS = %d
function on_tick(g, tick)
  if tick == ROUND_TICKS then g.end_round("round_reset_test: round over") end
end
"""

OPEN_RE = re.compile(r"ROUND_RESET_BRAIN open player=(\d+)")
THINK_RE = re.compile(r"ROUND_RESET_BRAIN think=(\d+)")
CLOSE_RE = re.compile(r"ROUND_RESET_BRAIN close after (\d+) thinks")
RELOAD_RE = re.compile(r"bot (\d+) reloaded with brain")


def find_ds(build_dir):
    for c in (build_dir / "WinBoloDS.exe", build_dir / "WinBoloDS",
              build_dir / "Release" / "WinBoloDS.exe"):
        if c.exists():
            return c
    return None


def main():
    args = sys.argv[1:]
    take_asap_flag(args)
    build_dir = DEFAULT_BUILD
    i = 0
    while i < len(args):
        if args[i] == "--build" and i + 1 < len(args):
            build_dir = Path(args[i + 1]); i += 2
        else:
            i += 1
    print(pacing_line())
    print(f"=== round reset: fresh Lua brain per round ({ROUND_TICKS}-tick "
          f"rounds, {RUN_SECONDS} s of wall clock)")
    ds = find_ds(build_dir)
    if not ds:
        print(f"FAIL: WinBoloDS not found under {build_dir}")
        return 1
    if not SRC_MAP.exists():
        print(f"FAIL: {SRC_MAP} missing")
        return 1

    mapdir = HERE / "round_reset_mapdir"
    if mapdir.exists():
        shutil.rmtree(mapdir)
    mapdir.mkdir()
    shutil.copyfile(SRC_MAP, mapdir / "round_reset.map")
    (mapdir / "round_reset.scenario.lua").write_text(SCRIPT % ROUND_TICKS,
                                                     encoding="utf-8")
    out = HERE / "round_reset_stderr.txt"
    probe = HERE / "brains" / "round_reset_count.out"
    if probe.exists():
        probe.unlink()
    env = dict(os.environ, WINBOLO_LOG="sim=info", WINBOLO_BRAINDBG_LABEL=LABEL)
    # -ticks does not end a -maprotate server (the round counter restarts with
    # every rotation), so the run is bounded by wall clock instead: under
    # -asap a 400-tick round takes well under a second, so RUN_SECONDS gives
    # many rounds; the process is then terminated.
    cmd = [str(ds), "-mapdir", str(mapdir), "-maprotate", "-port", str(PORT),
           "-gametype", "open", "-bots", "1", "-brain", str(BRAIN),
           "-allow-unsafe-brains", "-ai", "yes",
           "-seed", "7",
           "-nowinbolonet", "-notracker", "-quiet", "-threads", "1"] + asap_args()
    with open(out, "wb") as errf:
        proc = subprocess.Popen(cmd, cwd=str(build_dir), env=env,
                                stdout=errf, stderr=subprocess.STDOUT)
        try:
            proc.wait(timeout=RUN_SECONDS)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
    text = out.read_text(encoding="utf-8", errors="replace")
    shutil.rmtree(mapdir, ignore_errors=True)
    brain_text = probe.read_text(encoding="utf-8", errors="replace") if probe.exists() else ""
    if probe.exists():
        probe.unlink()

    opens = OPEN_RE.findall(brain_text)
    thinks = [int(x) for x in THINK_RE.findall(brain_text)]
    closes = CLOSE_RE.findall(brain_text)
    reloads = RELOAD_RE.findall(text)
    text = brain_text   # the ordering check below reads the brain's own log
    print(f"  brain opens: {len(opens)}; closes: {len(closes)}; reloads logged: "
          f"{len(reloads)}; think samples: {thinks[:12]}{'...' if len(thinks) > 12 else ''}")
    if not opens:
        print("FAIL: the probe brain never printed its open line -- is "
              "WINBOLO_LOG reaching the console? First lines of the output:")
        print("\n".join(text.splitlines()[:20]))
        return 1
    if len(opens) < 2:
        print("FAIL: the brain was opened only once -- either only one round "
              "ran (no rotation?) or the round start did not rebuild the brain")
        return 1
    if not reloads:
        print("FAIL: bot_manager never logged 'reloaded with brain' -- "
              "botManagerOnGameStart did not rebuild the brain")
        return 1
    restarts = sum(1 for t in thinks if t == 1)
    if restarts < 2:
        print(f"FAIL: think=1 printed {restarts} time(s); the think counter did "
              "not restart, so the old lua_State survived the round boundary")
        return 1
    drops = sum(1 for a, b in zip(thinks, thinks[1:]) if b < a)
    if drops < 1:
        print("FAIL: the think counter never dropped back")
        return 1
    if not closes:
        print("FAIL: the old brain was never closed (no 'close after N thinks')")
        return 1
    # order: a close must come before the second open
    first_close = text.find("ROUND_RESET_BRAIN close")
    second_open = [m.start() for m in OPEN_RE.finditer(text)][1]
    if first_close < 0 or first_close > second_open:
        print("FAIL: the second open happened before the first close -- the "
              "old state was not torn down first")
        return 1
    print(f"PASS: {len(opens)} rounds, each on a fresh lua_State (counter "
          f"restarted {restarts}x, {len(reloads)} reload line(s), close before "
          "re-open).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
