-- Scenario sidecar for tests/sea_release_release.map -- GENERATED by
-- tests/generate_sea_release_map.py, do not edit by hand.
--
-- Three jobs.
--
-- 1. mapRead puts ROAD under every map-file pillbox (bolo_map.c), so the dead
--    raft would sit on one-tile road pedestals in the middle of the sea -- a
--    boat driving onto one BEACHES and the tank drowns stepping off.
--    on_setup runs before the first snapshot, so put the deep sea back under
--    them there.  Same trick as tests/sea_pills_*.scenario.lua.
--
-- 2. Own the raft and the base.
--
-- 3. variant `release` only: at tick 400 hand the WHOLE RAFT to the
--    tank.  The pills are in a tank now, so filter_capture_pill drops them,
--    the committed capture goal is invalidated, and the goal changes on that
--    tick with the harvest chain half-run and its plan live.  Nothing else in
--    the arena touches the harvest.

local T_DEEP_SEA = 0xFF
local OUR_PLAYER = 0
local RAFT       = { { 138, 124 }, { 139, 126 }, { 138, 128 } }
local GIVE       = true
local GIVE_TICK  = 400
local given      = false

function on_setup(g)
  for _, p in ipairs(RAFT) do
    g.set_tile(p[1], p[2], T_DEEP_SEA)
  end
  for i = 1, g.num_pills() do
    g.set_pill_owner(i, OUR_PLAYER)
  end
  for i = 1, g.num_bases() do
    g.set_base_owner(i, OUR_PLAYER)
  end
  g.message(string.format("SEA_RELEASE_ARENA raft of %d, give=%s@%d",
                          g.num_pills(), tostring(GIVE), GIVE_TICK))
end

function on_tick(g, tick)
  if GIVE and not given and tick >= GIVE_TICK then
    given = true
    local n = 0
    for i = 1, g.num_pills() do
      local ok, err = g.give_pill(OUR_PLAYER, i)
      if ok then n = n + 1
      else g.message("SEA_RELEASE_ARENA give_pill#" .. i .. " failed: "
                     .. tostring(err)) end
    end
    g.message("SEA_RELEASE_ARENA gave " .. n .. " raft pill(s) at tick " .. tick)
  end
end
