-- Scenario sidecar for tests/spawn_escape_B.map -- GENERATED by
-- tests/generate_spawn_escape_map.py, do not edit by hand.
--
-- Two jobs.
--
-- 1. OPEN THE CHANNEL ONCE THE TANK HAS DIED IN IT.  The map seals the start
--    square into a one-tile-wide water pocket whose only opening faces the
--    pillbox seven tiles away, with nothing but water in between.  The tank
--    cannot leave it and, on 0 shells, cannot shoot the walls down: the pill
--    sinks its boat where it floats and deep sea does the rest.  It respawns
--    ONE TILE from where it died, which is the whole point of this variant --
--    a jump that small is invisible to init.lua's RESPAWN_DETECTED (which
--    needs more than RESPAWN_CACHE_WIPE_DIST = 12 tiles), so only
--    info.newtank can arm the escape, and for a while nothing did.
--
--    The instant the tank reads dead, this turns the pocket's south wall
--    ((125,128), (126,128), (127,128)) into deep sea.  TANK_DEATH_WAIT is 255 frames, so
--    the way out is open long before the tank comes back -- and life 2, on the
--    same start square under the same coverage, is the life the test is about.
--
--    Only the FIRST death opens it; after that the map stops changing, so a
--    later death (which the test treats as a failure) cannot be papered over.
--
-- 2. KEEP THE BASE'S STOCK READING FRESH.  A bot learns base stock from
--    EVENT_BASE_STOCK, which the server emits ONLY when a base's
--    armour/shells/mines actually CHANGE.  An untouched base goes quiet and
--    the reading ages out past REFUEL_OBS_STALE; then se_nearest_stocked_base
--    can no longer tell this base is worth biasing the escape toward, and the
--    post-escape refuel has nothing fresh to aim at.  So every 150 ticks
--    this re-asserts the stock with a mines value that alternates 90/89 -- a
--    real change, so a real event.

local SPAWN     = { 126, 127 }
local BASE      = { 126, 141 }
local OWNER     = 0
local PERIOD    = 150
local DEEP      = 255
local GRASS     = 7

local flip = 0
local deaths = 0
local was_dead = false

local function assert_stock(g)
  flip = 1 - flip
  for i = 1, g.num_bases() do
    g.set_base_stock(i, 90, 90, 90 - flip)
  end
end

function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      g.set_base_stock(i, 90, 90, 90)
      g.message(string.format(
        "SPAWN_ESCAPE_ARENA base#%d (%d,%d) owner=%d armour=90 shells=90",
        i, b.x, b.y, OWNER))
    end
  end
end

-- One death report per dead/alive edge, with the distance the respawn will
-- have to jump -- the number the whole A/B split is about.
local function note_deaths(g, tick, t)
  if t.dead and not was_dead then
    deaths = deaths + 1
    g.message(string.format(
      "SPAWN_ESCAPE_ARENA tank death #%d at tick %d pos=(%d,%d) dist_from_spawn=%d",
      deaths, tick, t.mx, t.my,
      math.abs(t.mx - SPAWN[1]) + math.abs(t.my - SPAWN[2])))
  end
  was_dead = t.dead and true or false
end
local GATE = { { 125, 128 }, { 126, 128 }, { 127, 128 } }

local gate_open = false

function on_tick(g, tick)
  if tick > 0 and tick % PERIOD == 0 then assert_stock(g) end

  local t = g.tank(0)
  if not t then return end
  note_deaths(g, tick, t)

  if t.dead and not gate_open then
    gate_open = true
    for _, q in ipairs(GATE) do g.set_tile(q[1], q[2], DEEP) end
    g.message("SPAWN_ESCAPE_ARENA channel opened at tick " .. tostring(tick))
  end
end
