-- Scenario sidecar for tests/spawn_escape_A.map -- GENERATED by
-- tests/generate_spawn_escape_map.py, do not edit by hand.
--
-- Two jobs.
--
-- 1. KILL THE TANK ONCE, FAR FROM ITS START.  The escape cannot fire on a
--    tank's FIRST life -- there is nothing to respawn from -- so the tank has
--    to die once before the thing under test can happen.  Variant A wants that
--    death a LONG way from the start, so the respawn is a big position jump
--    and init.lua's RESPAWN_DETECTED path is the one that arms the escape.
--    (Variant B covers the opposite shape: dying ON the start square, where
--    the jump is 1 and only info.newtank can arm it.)
--
--    So the FIRST time the tank is standing on dry land at least 13 tiles
--    from the start -- which on this map means walking up to its base -- this
--    turns the tile under its tracks into deep sea.  tank.c drowns any tank
--    that is not on a boat over DEEP_SEA, so it dies on the spot; the ground
--    is put straight back a few ticks later, leaving the map exactly as it
--    was.  One death, at a known place, at a known moment, and no second
--    hazard anywhere near the escape route.
--
--    It never fires twice: every later death is the bot's own doing, which is
--    what the test is measuring.
--
-- 2. KEEP THE BASE'S STOCK READING FRESH.  A bot learns base stock from
--    EVENT_BASE_STOCK, which the server emits ONLY when a base's
--    armour/shells/mines actually CHANGE.  An untouched base goes quiet and
--    the reading ages out past REFUEL_OBS_STALE; then se_nearest_stocked_base
--    can no longer tell this base is worth biasing the escape toward, and the
--    post-escape refuel has nothing fresh to aim at.  So every 150 ticks
--    this re-asserts the stock with a mines value that alternates 90/89 -- a
--    real change, so a real event.

local SPAWN     = { 126, 127 }
local BASE      = { 126, 141 }
local OWNER     = 0
local PERIOD    = 150
local DEEP      = 255
local GRASS     = 7

local flip = 0
local deaths = 0
local was_dead = false

local function assert_stock(g)
  flip = 1 - flip
  for i = 1, g.num_bases() do
    g.set_base_stock(i, 90, 90, 90 - flip)
  end
end

function on_setup(g)
  for i = 1, g.num_bases() do
    local b = g.base(i)
    if b then
      g.set_base_owner(i, OWNER)
      g.set_base_stock(i, 90, 90, 90)
      g.message(string.format(
        "SPAWN_ESCAPE_ARENA base#%d (%d,%d) owner=%d armour=90 shells=90",
        i, b.x, b.y, OWNER))
    end
  end
end

-- One death report per dead/alive edge, with the distance the respawn will
-- have to jump -- the number the whole A/B split is about.
local function note_deaths(g, tick, t)
  if t.dead and not was_dead then
    deaths = deaths + 1
    g.message(string.format(
      "SPAWN_ESCAPE_ARENA tank death #%d at tick %d pos=(%d,%d) dist_from_spawn=%d",
      deaths, tick, t.mx, t.my,
      math.abs(t.mx - SPAWN[1]) + math.abs(t.my - SPAWN[2])))
  end
  was_dead = t.dead and true or false
end
local KILL_DIST = 13

local scripted_kill_done = false
local restore = nil

function on_tick(g, tick)
  if tick > 0 and tick % PERIOD == 0 then assert_stock(g) end

  -- Put the ground back a few ticks after the scripted drowning.
  if restore and tick >= restore[3] + 5 then
    g.set_tile(restore[1], restore[2], GRASS)
    g.message(string.format("SPAWN_ESCAPE_ARENA restored land at (%d,%d) tick %d",
                            restore[1], restore[2], tick))
    restore = nil
  end

  local t = g.tank(0)
  if not t then return end
  note_deaths(g, tick, t)

  if not scripted_kill_done and not t.dead and not t.boat then
    local d = math.abs(t.mx - SPAWN[1]) + math.abs(t.my - SPAWN[2])
    -- Never dig out the base's own tile: mapRead forces ROAD under a base and
    -- putting sea there, even briefly, is a change this arena does not want.
    if d >= KILL_DIST and not (t.mx == BASE[1] and t.my == BASE[2]) then
      scripted_kill_done = true
      restore = { t.mx, t.my, tick }
      g.set_tile(t.mx, t.my, DEEP)
      g.message(string.format(
        "SPAWN_ESCAPE_ARENA scripted drowning at (%d,%d) tick %d (%d tiles from spawn)",
        t.mx, t.my, tick, d))
    end
  end
end
