-- Scenario sidecar for tests/steal_handshake_duel.map -- GENERATED by
-- tests/generate_steal_handshake_map.py, do not edit by hand.
--
-- Two jobs.  The PILLS are deliberately not touched: they are NEUTRAL in the
-- map file and stay that way (see the generator's header for why an "allied"
-- pill is not buildable here).
--
-- 1. OWN THE BASES.  They are already slot 0's and slot 1's in the map file,
--    but on_setup re-asserts owner and full stock so the intent is in one
--    place.  The bots start full, so refuel never wins; what the bases are for
--    is being a real fallback goal WITH A TARGET ID, which is what a released
--    steal-yield reads off the stealer's advert.
--
-- 2. FILL THE SPAWN PONDS once every tank is ashore.  A start square has to be
--    DEEP SEA (starts.c startsIsValidSquare), so the arena has three one-tile
--    ponds sitting in grass.  A tank that later drives over one without a boat
--    drowns instantly -- noise this test does not want -- so once nobody is
--    afloat the ponds become grass.
local BASES  = { { 114, 140, 0 }, { 138, 112, 1 } }
local FULL   = 90
local PONDS  = { { 113, 126 }, { 139, 126 }, { 107, 110 } }
local GRASS  = 7
local ponds_filled = false

function on_setup(g)
  for _, b in ipairs(BASES) do
    for i = 1, g.num_bases() do
      local bb = g.base(i)
      if bb and bb.x == b[1] and bb.y == b[2] then
        g.set_base_owner(i, b[3])
        g.set_base_stock(i, FULL, FULL, 90)
      end
    end
  end
  for i = 1, g.num_pills() do
    local p = g.pill(i)
    if p then
      -- 1-based here, 0-based in the brain: scenario pill i is brain pill i-1.
      g.message(string.format("STEAL_ARENA pill#%d (%d,%d) owner=%d armour=%d",
                              i - 1, p.x, p.y, p.owner, p.armour))
    end
  end
end

function on_tick(g, tick)
  -- Fill the ponds as soon as nobody is afloat any more (see note 2).
  if not ponds_filled and tick > 200 then
    local afloat = false
    for p = 0, g.max_tanks() - 1 do
      local t = g.tank(p)
      if t and t.boat then afloat = true end
    end
    if not afloat then
      ponds_filled = true
      for _, q in ipairs(PONDS) do g.set_tile(q[1], q[2], GRASS) end
      g.message("STEAL_ARENA spawn ponds filled at tick " .. tostring(tick))
    end
  end
end
