#ifndef GH_SHIELD_STAMP_H
#define GH_SHIELD_STAMP_H

#include <lua.h>

/*
 * gh_shield_stamp — precomputed shield-scan shot-path lookup table.
 *
 * Data is loaded once from shield_stamp_cache.bin (generated by
 * BrainTest --run-script generate_shield_stamps.lua).
 *
 * Lua API (registered as global table "gh_shield"):
 *   gh_shield.load(path)                         -> true/false
 *   gh_shield.is_loaded()                        -> true/false
 *   gh_shield.stamp_hit(deg, nudge_wu, aim_idx)  -> true/false/nil
 *   gh_shield.stamp_tiles(pmx,pmy,deg,nudge_wu,aim_idx) -> list or nil
 *
 * stamp_hit returns nil when the stamp is not loaded or the nudge_wu
 * value is outside the precomputed range — callers fall back to
 * cpf.simulate_shot / ensure_nudge_ring in that case.
 */

void naShieldStampRegister(lua_State *L);

#endif /* GH_SHIELD_STAMP_H */
