#!/usr/bin/env python3
# embed_lua.py
#
# Turns a Lua source file into a C include holding its bytes, so a script
# the binary has to carry can stay a real .lua file that an editor
# highlights and a diff reads.
#
# The output is a byte array and a length, never a string literal: MSVC caps
# a literal at 65535 bytes, and a byte array has no such ceiling and no
# escaping rules to get wrong.
#
# Like tools/dump_lang_en.py, this is run by hand and its output is
# committed. The build does not invoke it, so nothing here becomes a build
# dependency. Re-run it after editing the .lua and commit both files
# together; the unit case scenario_hooks_router_matches_source fails if the
# two ever drift.
#
# Both the output and the run are deterministic and idempotent: re-running
# with no source change rewrites nothing.
#
# Usage:
#   python3 tools/embed_lua.py src/scenario/scenario_triggers.lua \
#       src/scenario/scenario_triggers.inc --symbol kScnTriggersLua
#
#   python3 tools/embed_lua.py <input.lua> <output.inc> [--symbol NAME] --check
#       (exit 1 if the output would change instead of writing it)

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# How many bytes go on one line of the array. Twelve at six columns apiece
# plus the indent sits inside 80.
BYTES_PER_LINE = 12


def c_symbol(name):
    """The length macro that goes with an array symbol: kScnTriggersLua ->
    SCN_TRIGGERS_LUA_LEN."""
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.upper())
    text = "".join(out)
    if text.startswith("K_"):
        text = text[2:]
    return text + "_LEN"


def render(data, symbol, src_rel, out_rel):
    lines = []
    lines.append(f"/* {out_rel} -- generated by tools/embed_lua.py.")
    lines.append(" * Do not hand-edit; re-run the generator after changing")
    lines.append(f" * {src_rel} and commit both files together.")
    lines.append(" *")
    lines.append(f" * {len(data)} bytes of Lua source, verbatim. The bytes are")
    lines.append(" * loaded as text, so the file's own line numbers are what an")
    lines.append(" * error in it reports.")
    lines.append(" */")
    lines.append("")
    lines.append(f"static const unsigned char {symbol}[] = {{")

    for start in range(0, len(data), BYTES_PER_LINE):
        chunk = data[start:start + BYTES_PER_LINE]
        body = " ".join(f"0x{b:02x}," for b in chunk)
        lines.append(f"    {body}")

    lines.append("};")
    lines.append("")
    lines.append(f"#define {c_symbol(symbol)} (sizeof {symbol})")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", help="the .lua file to embed")
    parser.add_argument("output", help="the C include to write")
    parser.add_argument("--symbol", default="kScnTriggersLua",
                        help="the array symbol to declare (default: "
                             "kScnTriggersLua)")
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if the output would change instead of "
                             "writing it.")
    args = parser.parse_args()

    src = Path(args.input)
    out = Path(args.output)

    # Read and write bytes, never text: the array has to be what the loader
    # will be handed, and a newline translated on the way through would make
    # the embedded copy differ from the file on disk.
    data = src.read_bytes()
    if b"\r" in data:
        print(f"error: {args.input} has CR bytes in it. The embedded copy is "
              f"compared against the file on disk, so it has to be checked "
              f"out LF; see .gitattributes.", file=sys.stderr)
        return 1

    def rel(path):
        try:
            return str(path.resolve().relative_to(REPO_ROOT)).replace("\\", "/")
        except ValueError:
            return path.name

    content = render(data, args.symbol, rel(src), rel(out))

    existing = out.read_text(encoding="utf-8") if out.exists() else None
    if existing == content:
        print(f"unchanged: {rel(out)}", file=sys.stderr)
        return 0

    if args.check:
        print(f"would update: {rel(out)}", file=sys.stderr)
        return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"wrote: {rel(out)} ({len(data)} bytes of Lua)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
