#!/usr/bin/env python3
# gen_countries.py
#
# One-shot generator for the STR_COUNTRY_* localization strings keyed by the
# two-letter flag basenames in data/flags/. From data/flags/countries.csv it
# rewrites three regions of generated content:
#
#   * src/gui/lang.h        — #define STR_COUNTRY_<CC> <id> lines, inside the
#                             marked "generated country name IDs" region.
#   * src/gui/sdl3/lang.c   — { <id>, "<Name>" } langTable rows, inside the
#                             marked "generated country names" region.
#   * src/gui/sdl3/countries.inc — a full-file sorted code -> langid lookup
#                             table for bsearch at render time.
#
# This is write-once data committed for reproducibility; it is intentionally
# not wired into the build. After running it, re-run tools/dump_lang_en.py to
# refresh data/lang/en.txt and src/gui/sdl3/lang_names.inc.
#
# The output is deterministic and idempotent: re-running with no source change
# produces byte-identical files. The marked regions are replaced in place, so
# the generator never appends on re-run.
#
# Usage:
#   python3 tools/gen_countries.py        (run from repo root)

import csv
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = REPO_ROOT / "data" / "flags" / "countries.csv"
LANG_H_PATH = REPO_ROOT / "src" / "gui" / "lang.h"
LANG_C_PATH = REPO_ROOT / "src" / "gui" / "sdl3" / "lang.c"
COUNTRIES_INC_PATH = REPO_ROOT / "src" / "gui" / "sdl3" / "countries.inc"

# First STR_COUNTRY_* enum value. 1531 (STR_PLAYER_TIP_STEAM_BUILD) is the
# highest id currently used in lang.h, so the country block starts here.
START_ID = 1532

# Marker comments delimiting the generated regions (added once by hand).
LANG_H_BEGIN = "/* BEGIN generated country name IDs — tools/gen_countries.py; do not hand-edit. */"
LANG_H_END = "/* END generated country name IDs */"
LANG_C_BEGIN = "/* BEGIN generated country names — tools/gen_countries.py; do not hand-edit. */"
LANG_C_END = "/* END generated country names */"


def read_countries():
    """Return [(code, name), ...] from countries.csv in file (sorted) order.

    Skips '#' comment lines and the 'code,name' header. Names use RFC-4180
    quoting for the comma-containing entries (BQ, SH); csv handles that.
    """
    rows = []
    with CSV_PATH.open(encoding="utf-8", newline="") as f:
        data_lines = [ln for ln in f if not ln.lstrip().startswith("#")]
    reader = csv.reader(data_lines)
    header = next(reader)
    if header != ["code", "name"]:
        sys.exit(f"unexpected CSV header: {header!r}")
    for row in reader:
        if not row:
            continue
        code, name = row[0].strip(), row[1]
        rows.append((code, name))
    return rows


def c_escape(s):
    """Escape a Python string for use inside a C double-quoted literal.

    Only a literal backslash or double quote need escaping; all other bytes
    (including UTF-8) are emitted verbatim.
    """
    return s.replace("\\", "\\\\").replace("\"", "\\\"")


def replace_region(text, begin, end, body, path):
    """Return text with the lines between the begin/end marker lines replaced
    by body (a list of lines). The marker lines themselves are preserved.
    """
    pattern = re.compile(
        re.escape(begin) + r"\n.*?" + re.escape(end),
        re.DOTALL,
    )
    if not pattern.search(text):
        sys.exit(f"markers not found in {path}: add the BEGIN/END pair first")
    replacement = begin + "\n" + "\n".join(body) + "\n" + end
    return pattern.sub(lambda _m: replacement, text, count=1)


def main():
    countries = read_countries()
    entries = [(code, name, START_ID + i) for i, (code, name) in enumerate(countries)]
    last_id = entries[-1][2]
    print(f"{len(entries)} countries, ids {START_ID}-{last_id}", file=sys.stderr)

    name_w = max(len(f"STR_COUNTRY_{code}") for code, _, _ in entries)

    # lang.h: #define STR_COUNTRY_<CC> <id>, led by the en.txt section header.
    h_body = ["/* Country names */"]
    for code, _name, num in entries:
        sym = f"STR_COUNTRY_{code}"
        h_body.append(f"#define {sym:<{name_w}} {num}")

    # lang.c: { <id>, "<Name>" } rows for langTable[].
    c_body = []
    for _code, name, num in entries:
        c_body.append(f"    {{{num}, \"{c_escape(name)}\"}},")

    h_text = replace_region(LANG_H_PATH.read_text(encoding="utf-8"),
                            LANG_H_BEGIN, LANG_H_END, h_body, LANG_H_PATH)
    c_text = replace_region(LANG_C_PATH.read_text(encoding="utf-8"),
                            LANG_C_BEGIN, LANG_C_END, c_body, LANG_C_PATH)

    # countries.inc: full-file sorted code -> langid table for bsearch.
    inc = []
    inc.append("/* countries.inc — generated by tools/gen_countries.py.")
    inc.append(" * Do not hand-edit; re-run the generator after changing")
    inc.append(" * data/flags/countries.csv.")
    inc.append(" *")
    inc.append(" * Sorted ascending by code so the renderer can bsearch a flag")
    inc.append(" * basename to its localized STR_COUNTRY_* name id.")
    inc.append(" */")
    inc.append("")
    inc.append("typedef struct { char code[3]; langid id; } CountryNameEntry;")
    inc.append("")
    inc.append("static const CountryNameEntry kCountryNames[] = {")
    for code, _name, _num in entries:
        inc.append(f"    {{ \"{code}\", STR_COUNTRY_{code} }},")
    inc.append("};")
    inc.append("")
    inc.append(f"#define K_COUNTRY_NAMES_SIZE {len(entries)}")
    inc.append("")
    inc_text = "\n".join(inc)

    LANG_H_PATH.write_text(h_text, encoding="utf-8")
    LANG_C_PATH.write_text(c_text, encoding="utf-8")
    COUNTRIES_INC_PATH.write_text(inc_text, encoding="utf-8")
    print(f"wrote: {LANG_H_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
    print(f"wrote: {LANG_C_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
    print(f"wrote: {COUNTRIES_INC_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
