/*
 * Golden regression coverage for the generated flat-leaf-snapshot codecs.
 *
 * For each flat leaf message (Shell / TkExplosion / Base / Pill) this checks the
 * linked production pack/unpack pair from transport_udp_common.c, generated by
 * DEFINE_WIRE_CODEC over the field lists in wire_messages.h, against two sources
 * of vectors:
 *
 *   - committed golden fixtures in tests/fixtures/wire/<label>.hex (captured
 *     from a real loopback session by test_wire_corpus_capture; the second
 *     tank_snapshot vector is hand-composed instead, because no loopback
 *     session has yet emitted a tank inside its respawn wait and the
 *     presence-mask group for that wait would otherwise go uncovered here.
 *     test_wire_corpus_capture rewrites the whole file, so a re-capture drops
 *     it), and
 *   - programmatic boundary vectors (every field 0, then every field at its
 *     type maximum), so coverage does not depend on which messages a session
 *     happened to emit.
 *
 * Per fixture vector it asserts: length equals the per-message WIRE_SIZE, the
 * generated unpack consumes the whole vector, and the generated pack reproduces
 * the golden bytes exactly. Per boundary vector it asserts pack returns
 * WIRE_SIZE and unpack(pack(s)) round-trips struct-identical. Once per message
 * it asserts WIRE_SIZE_OF(fields) equals the per-message WIRE_SIZE.
 *
 * It also checks the generated presence-bitmask TankSnapshot codec against a
 * verbatim copy of the pre-migration hand-rolled codec across every group
 * combination, plus the golden fixture and the stub path.
 *
 * No sockets and no file writes: it only reads committed fixtures.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "input_packet.h"            /* snapshot structs + *_WIRE_SIZE */
#include "transport_udp_internal.h"  /* generated pack/unpack prototypes */
#include "wire_codec.h"              /* WIRE_SIZE_OF */
#include "wire_messages.h"           /* the four *_FIELDS lists */
#include "test_harness.h"

#ifndef WB_WIRE_FIXTURE_DIR
#define WB_WIRE_FIXTURE_DIR "tests/fixtures/wire"
#endif

#define WC_BYTES        64
#define WC_MAX_VECTORS  64

/* Set each field to its type maximum, applied to a field list. */
#define WIRE_MAX_U8  0xFFu
#define WIRE_MAX_U16 0xFFFFu
#define WIRE_MAX_U32 0xFFFFFFFFu
#define FIELD_SET_MAX(type, name) s.name = (WIRE_MAX_##type);

/* Parse one hex char; -1 if not a hex digit. */
static int hexVal(int c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

/* Decode one lowercase-hex line into out (<= WC_BYTES). Returns byte count, or
 * -1 on a malformed line. */
static int decodeHexLine(const char *line, uint8_t *out) {
    int n = 0;
    while (line[0] && line[0] != '\n' && line[0] != '\r') {
        int hi, lo;
        if (n >= WC_BYTES) return -1;
        hi = hexVal((unsigned char)line[0]);
        lo = hexVal((unsigned char)line[1]);
        if (hi < 0 || lo < 0) return -1;
        out[n++] = (uint8_t)((hi << 4) | lo);
        line += 2;
    }
    return n;
}

/* Load tests/fixtures/wire/<label>.hex into vecs/lens. Returns the number of
 * vectors, or 0 if the file is absent (a missing fixture is not a failure;
 * boundary vectors still run). */
static int loadFixture(const char *label, uint8_t vecs[][WC_BYTES],
                       size_t *lens, int maxVecs) {
    char path[512];
    char line[256];
    FILE *f;
    int n = 0;
    snprintf(path, sizeof(path), "%s/%s.hex", WB_WIRE_FIXTURE_DIR, label);
    f = fopen(path, "r");
    if (!f) return 0;
    while (n < maxVecs && fgets(line, sizeof(line), f)) {
        int len;
        if (line[0] == '\n' || line[0] == '\r' || line[0] == '\0') continue;
        len = decodeHexLine(line, vecs[n]);
        if (len <= 0) continue;
        lens[n] = (size_t)len;
        n++;
    }
    fclose(f);
    return n;
}

/* Emit a per-message check function. Pack/Unpack are the linked production
 * symbols generated by DEFINE_WIRE_CODEC. */
#define MSG_CHECK_FN(FnName, Struct, Pack, Unpack, LABEL, WSIZE, FIELDS)       \
static int FnName(void) {                                                      \
    uint8_t vecs[WC_MAX_VECTORS][WC_BYTES];                                    \
    size_t  lens[WC_MAX_VECTORS];                                             \
    int n, k;                                                                  \
    UT_ASSERT_MSG(WIRE_SIZE_OF(FIELDS) == (WSIZE),                             \
                  LABEL " (d) WIRE_SIZE_OF mismatch");                         \
    n = loadFixture(LABEL, vecs, lens, WC_MAX_VECTORS);                        \
    for (k = 0; k < n; k++) {                                                  \
        Struct s;                                                             \
        uint8_t gen[WC_BYTES];                                                \
        UT_ASSERT_MSG(lens[k] == (WSIZE), LABEL " fixture wrong length");      \
        memset(&s, 0, sizeof(s));                                             \
        UT_ASSERT_MSG(Unpack(vecs[k], lens[k], &s) == (int)(WSIZE),            \
                      LABEL " generated unpack short read");                   \
        memset(gen, 0, sizeof(gen));                                          \
        UT_ASSERT_MSG(Pack(gen, &s) == (int)(WSIZE),                          \
                      LABEL " generated pack wrong length");                   \
        UT_ASSERT_MSG(memcmp(gen, vecs[k], (WSIZE)) == 0,                      \
                      LABEL " generated pack != golden");                      \
    }                                                                          \
    {                                                                          \
        Struct s, su;                                                         \
        uint8_t g[WC_BYTES];                                                  \
        int pass;                                                             \
        for (pass = 0; pass < 2; pass++) {                                    \
            memset(&s, 0, sizeof(s));                                         \
            if (pass == 1) { FIELDS(FIELD_SET_MAX) }                          \
            memset(g, 0, sizeof(g));                                          \
            UT_ASSERT_MSG(Pack(g, &s) == (int)(WSIZE),                        \
                          LABEL " boundary pack wrong length");               \
            memset(&su, 0, sizeof(su));                                       \
            UT_ASSERT_MSG(Unpack(g, (WSIZE), &su) == (int)(WSIZE),            \
                          LABEL " boundary unpack short read");               \
            UT_ASSERT_MSG(memcmp(&s, &su, sizeof(s)) == 0,                    \
                          LABEL " boundary round-trip differ");              \
        }                                                                      \
    }                                                                          \
    return 0;                                                                  \
}

MSG_CHECK_FN(check_shell, ShellSnapshot, packShellSnapshot, unpackShellSnapshot,
             "shell_snapshot", SHELL_SNAPSHOT_WIRE_SIZE, SHELL_SNAPSHOT_FIELDS)
MSG_CHECK_FN(check_tk, TkExplosionSnapshot, packTkExplosionSnapshot,
             unpackTkExplosionSnapshot, "tk_explosion_snapshot",
             TK_EXPLOSION_SNAPSHOT_WIRE_SIZE, TK_EXPLOSION_SNAPSHOT_FIELDS)
MSG_CHECK_FN(check_base, BaseSnapshot, packBaseSnapshot, unpackBaseSnapshot,
             "base_snapshot", BASE_SNAPSHOT_WIRE_SIZE, BASE_SNAPSHOT_FIELDS)
MSG_CHECK_FN(check_pill, PillSnapshot, packPillSnapshot, unpackPillSnapshot,
             "pill_snapshot", PILL_SNAPSHOT_WIRE_SIZE, PILL_SNAPSHOT_FIELDS)

/* ---- TankSnapshot: differential check against a pre-migration oracle -------
 *
 * packTankRef / unpackTankRef are the hand-rolled presence-bitmask codec taken
 * from transport_udp_common.c as it stood before the masked codec replaced it
 * (the corpus tap removed), and hand-maintained since against the field list.
 * They are the reference the generated packTankSnapshot / unpackTankSnapshot
 * must match byte-for-byte and struct-for-struct. */
static int packTankRef(uint8_t *buf, const TankSnapshot *s) {
    uint16_t mask = 0;
    int pos;

    buf[0] = s->playerNum;
    if (s->playerNum & TANK_SNAPSHOT_HIDDEN_FLAG) {
        return 1;
    }

    if (s->armour || s->shells || s->mines || s->trees || s->gunsightLen) {
        mask |= TANK_PRESENT_OWNER_RES;
    }
    if (s->reload)    mask |= TANK_PRESENT_RELOAD;
    if (s->deathWait) mask |= TANK_PRESENT_DEATHWAIT;
    if (s->lgmFrame || s->lgmMX || s->lgmMY || s->lgmPX || s->lgmPY) {
        mask |= TANK_PRESENT_LGM;
    }
    if (s->firstLeft || s->firstRight) mask |= TANK_PRESENT_TURNRAMP;
    if (s->pingMs)      mask |= TANK_PRESENT_PING;
    if (s->clientFlags) mask |= TANK_PRESENT_FLAGS;
    if (s->hiddenFlags) mask |= TANK_PRESENT_HIDDEN;
    if (s->modSpeed || s->modAccel || s->modTurn ||
        s->modReload || s->modDealt || s->modTaken) {
        mask |= TANK_PRESENT_MODS;
    }

    packU16(buf + 1, mask);
    packU16(buf + 3, s->worldX);
    packU16(buf + 5, s->worldY);
    packU16(buf + 7, s->angle);
    packU16(buf + 9, s->speed);
    buf[11] = s->tankStatus;
    pos = 12;

    if (mask & TANK_PRESENT_OWNER_RES) {
        buf[pos++] = s->armour;
        buf[pos++] = s->shells;
        buf[pos++] = s->mines;
        buf[pos++] = s->trees;
        buf[pos++] = s->gunsightLen;
    }
    if (mask & TANK_PRESENT_RELOAD)    buf[pos++] = s->reload;
    if (mask & TANK_PRESENT_DEATHWAIT) {
        packU16(buf + pos, s->deathWait);
        pos += 2;
    }
    if (mask & TANK_PRESENT_LGM) {
        buf[pos++] = s->lgmFrame;
        buf[pos++] = s->lgmMX;
        buf[pos++] = s->lgmMY;
        buf[pos++] = s->lgmPX;
        buf[pos++] = s->lgmPY;
    }
    if (mask & TANK_PRESENT_TURNRAMP) {
        buf[pos++] = s->firstLeft;
        buf[pos++] = s->firstRight;
    }
    if (mask & TANK_PRESENT_PING) {
        packU16(buf + pos, s->pingMs);
        pos += 2;
    }
    if (mask & TANK_PRESENT_FLAGS)  buf[pos++] = s->clientFlags;
    if (mask & TANK_PRESENT_HIDDEN) buf[pos++] = s->hiddenFlags;
    if (mask & TANK_PRESENT_MODS) {
        buf[pos++] = s->modSpeed;
        buf[pos++] = s->modAccel;
        buf[pos++] = s->modTurn;
        buf[pos++] = s->modReload;
        buf[pos++] = s->modDealt;
        buf[pos++] = s->modTaken;
    }
    return pos;
}

static int unpackTankRef(const uint8_t *buf, size_t avail, TankSnapshot *s) {
    uint16_t mask;
    size_t pos;

    memset(s, 0, sizeof(*s));
    if (avail < 1) return 0;
    s->playerNum = buf[0];
    if (s->playerNum & TANK_SNAPSHOT_HIDDEN_FLAG) {
        return 1;
    }

    if (avail < 12) return 0;
    mask = unpackU16(buf + 1);
    s->worldX = unpackU16(buf + 3);
    s->worldY = unpackU16(buf + 5);
    s->angle = unpackU16(buf + 7);
    s->speed = unpackU16(buf + 9);
    s->tankStatus = buf[11];
    pos = 12;

    if (mask & TANK_PRESENT_OWNER_RES) {
        if (avail < pos + 5) return 0;
        s->armour = buf[pos++];
        s->shells = buf[pos++];
        s->mines = buf[pos++];
        s->trees = buf[pos++];
        s->gunsightLen = buf[pos++];
    }
    if (mask & TANK_PRESENT_RELOAD) {
        if (avail < pos + 1) return 0;
        s->reload = buf[pos++];
    }
    if (mask & TANK_PRESENT_DEATHWAIT) {
        if (avail < pos + 2) return 0;
        s->deathWait = unpackU16(buf + pos);
        pos += 2;
    }
    if (mask & TANK_PRESENT_LGM) {
        if (avail < pos + 5) return 0;
        s->lgmFrame = buf[pos++];
        s->lgmMX = buf[pos++];
        s->lgmMY = buf[pos++];
        s->lgmPX = buf[pos++];
        s->lgmPY = buf[pos++];
    }
    if (mask & TANK_PRESENT_TURNRAMP) {
        if (avail < pos + 2) return 0;
        s->firstLeft = buf[pos++];
        s->firstRight = buf[pos++];
    }
    if (mask & TANK_PRESENT_PING) {
        if (avail < pos + 2) return 0;
        s->pingMs = unpackU16(buf + pos);
        pos += 2;
    }
    if (mask & TANK_PRESENT_FLAGS) {
        if (avail < pos + 1) return 0;
        s->clientFlags = buf[pos++];
    }
    if (mask & TANK_PRESENT_HIDDEN) {
        if (avail < pos + 1) return 0;
        s->hiddenFlags = buf[pos++];
    }
    if (mask & TANK_PRESENT_MODS) {
        if (avail < pos + 6) return 0;
        s->modSpeed = buf[pos++];
        s->modAccel = buf[pos++];
        s->modTurn = buf[pos++];
        s->modReload = buf[pos++];
        s->modDealt = buf[pos++];
        s->modTaken = buf[pos++];
    }
    return (int)pos;
}

/* Zero the fields of every group absent from `combo`, keyed on the field list,
 * so a filled tank reduces to exactly the entry `combo` describes. */
#define TANK_CLR_F(type, name)
#define TANK_CLR_FMASK()
#define TANK_CLR_FGROUP(bit, type, name)  if (!(combo & (bit))) s.name = 0;

/* Fill every data field with a distinct non-zero value (pass 0, exposes
 * intra-group reorders) or the type maximum (pass 1). playerNum keeps the
 * 0x80 stub bit clear so this is a full entry, not a stub. */
static void fillTank(TankSnapshot *s, int pass) {
    memset(s, 0, sizeof(*s));
    if (pass == 0) {
        s->playerNum = 0x11;
        s->worldX = 0x1234; s->worldY = 0x5678;
        s->angle = 0x9abc;  s->speed = 0x0def;
        s->tankStatus = 0x21;
        s->armour = 0x31; s->shells = 0x32; s->mines = 0x33;
        s->trees = 0x34;  s->gunsightLen = 0x35;
        s->reload = 0x41;
        s->deathWait = 0x5152;   /* past a byte: the group carries two */
        s->lgmFrame = 0x61; s->lgmMX = 0x62; s->lgmMY = 0x63;
        s->lgmPX = 0x64;    s->lgmPY = 0x65;
        s->firstLeft = 0x71; s->firstRight = 0x72;
        s->pingMs = 0x8081;
        s->clientFlags = 0x91;
        s->hiddenFlags = 0xA1;
        s->modSpeed = 0xB1; s->modAccel = 0xB2; s->modTurn = 0xB3;
        s->modReload = 0xB4; s->modDealt = 0xB5; s->modTaken = 0xB6;
    } else {
        s->playerNum = 0x7F;
        s->worldX = 0xFFFF; s->worldY = 0xFFFF;
        s->angle = 0xFFFF;  s->speed = 0xFFFF;
        s->tankStatus = 0xFF;
        s->armour = 0xFF; s->shells = 0xFF; s->mines = 0xFF;
        s->trees = 0xFF;  s->gunsightLen = 0xFF;
        s->reload = 0xFF;
        s->deathWait = 0xFFFF;
        s->lgmFrame = 0xFF; s->lgmMX = 0xFF; s->lgmMY = 0xFF;
        s->lgmPX = 0xFF;    s->lgmPY = 0xFF;
        s->firstLeft = 0xFF; s->firstRight = 0xFF;
        s->pingMs = 0xFFFF;
        s->clientFlags = 0xFF;
        s->hiddenFlags = 0xFF;
        s->modSpeed = 0xFF; s->modAccel = 0xFF; s->modTurn = 0xFF;
        s->modReload = 0xFF; s->modDealt = 0xFF; s->modTaken = 0xFF;
    }
}

static int check_tank(void) {
    uint8_t vecs[WC_MAX_VECTORS][WC_BYTES];
    size_t  lens[WC_MAX_VECTORS];
    int n, k, combo, pass;

    UT_ASSERT_MSG(WIRE_MASKED_SIZE_OF(TANK_SNAPSHOT_FIELDS) ==
                      TANK_SNAPSHOT_WIRE_SIZE,
                  "tank_snapshot (size) WIRE_MASKED_SIZE_OF mismatch");

    /* (golden) generated unpack matches the oracle and re-packs the fixture. */
    n = loadFixture("tank_snapshot", vecs, lens, WC_MAX_VECTORS);
    for (k = 0; k < n; k++) {
        TankSnapshot s, r;
        uint8_t gen[WC_BYTES];
        memset(&s, 0, sizeof(s));
        memset(&r, 0, sizeof(r));
        UT_ASSERT_MSG(unpackTankSnapshot(vecs[k], lens[k], &s) == (int)lens[k],
                      "tank_snapshot golden unpack short read");
        UT_ASSERT_MSG(unpackTankRef(vecs[k], lens[k], &r) == (int)lens[k],
                      "tank_snapshot golden oracle unpack short read");
        UT_ASSERT_MSG(memcmp(&s, &r, sizeof(s)) == 0,
                      "tank_snapshot golden generated vs oracle struct differ");
        memset(gen, 0, sizeof(gen));
        UT_ASSERT_MSG(packTankSnapshot(gen, &s) == (int)lens[k],
                      "tank_snapshot golden pack wrong length");
        UT_ASSERT_MSG(memcmp(gen, vecs[k], lens[k]) == 0,
                      "tank_snapshot golden pack != fixture");
    }

    /* (exhaustive group combos) all 512 group subsets, two value patterns. */
    for (pass = 0; pass < 2; pass++) {
        TankSnapshot filled;
        fillTank(&filled, pass);
        for (combo = 0; combo < 512; combo++) {
            TankSnapshot s, sg, sr;
            uint8_t g[WC_BYTES], r[WC_BYTES];
            int ng, nr, ug, ur;
            s = filled;
            TANK_SNAPSHOT_FIELDS(TANK_CLR_F, TANK_CLR_FMASK, TANK_CLR_FGROUP)
            memset(g, 0, sizeof(g));
            memset(r, 0, sizeof(r));
            ng = packTankSnapshot(g, &s);
            nr = packTankRef(r, &s);
            UT_ASSERT_MSG(ng == nr, "tank_snapshot combo pack length differ");
            UT_ASSERT_MSG(memcmp(g, r, (size_t)ng) == 0,
                          "tank_snapshot combo pack bytes differ");
            memset(&sg, 0, sizeof(sg));
            memset(&sr, 0, sizeof(sr));
            ug = unpackTankSnapshot(g, (size_t)ng, &sg);
            ur = unpackTankRef(r, (size_t)nr, &sr);
            UT_ASSERT_MSG(ug == ur, "tank_snapshot combo unpack length differ");
            UT_ASSERT_MSG(memcmp(&sg, &sr, sizeof(sg)) == 0,
                          "tank_snapshot combo unpack struct differ");
        }
    }

    /* (stub) hidden-flag entry is 1 byte; everything else decodes to 0. */
    {
        TankSnapshot s, out, outr, expect;
        uint8_t g[WC_BYTES], r[WC_BYTES];
        memset(&s, 0, sizeof(s));
        s.playerNum = (uint8_t)(0x80 | 0x05);
        memset(g, 0, sizeof(g));
        memset(r, 0, sizeof(r));
        UT_ASSERT_MSG(packTankSnapshot(g, &s) == 1, "tank_snapshot stub pack len");
        UT_ASSERT_MSG(packTankRef(r, &s) == 1, "tank_snapshot stub oracle pack len");
        UT_ASSERT_MSG(g[0] == s.playerNum && r[0] == s.playerNum,
                      "tank_snapshot stub byte");
        memset(&out, 0, sizeof(out));
        memset(&outr, 0, sizeof(outr));
        UT_ASSERT_MSG(unpackTankSnapshot(g, 1, &out) == 1,
                      "tank_snapshot stub unpack len");
        UT_ASSERT_MSG(unpackTankRef(r, 1, &outr) == 1,
                      "tank_snapshot stub oracle unpack len");
        memset(&expect, 0, sizeof(expect));
        expect.playerNum = s.playerNum;
        UT_ASSERT_MSG(memcmp(&out, &expect, sizeof(out)) == 0,
                      "tank_snapshot stub decoded non-zero beyond playerNum");
        UT_ASSERT_MSG(memcmp(&out, &outr, sizeof(out)) == 0,
                      "tank_snapshot stub generated vs oracle differ");
    }
    return 0;
}

int run_wire_corpus(void) {
    if (check_shell() != 0) return 1;
    if (check_tk() != 0) return 1;
    if (check_base() != 0) return 1;
    if (check_pill() != 0) return 1;
    if (check_tank() != 0) return 1;
    return 0;
}
