/*
 * Pins packetTypeName: the type->name debug mapping must be stable. The
 * production lookup in transport_udp_common.c is generated from a
 * PACKET_NAME_TABLE X-macro; this test keeps an independent copy of that
 * list and asserts every PACKET_* maps to exactly its string, so an
 * accidental edit to the production table is caught here. An undefined
 * type id must fall through to "UNKNOWN".
 */
#include <string.h>

#include "transport_udp_internal.h"  /* packetTypeName */
#include "netpacks.h"                /* PACKET_* type ids */
#include "test_harness.h"

/* Independent oracle — keep in sync with PACKET_NAME_TABLE in
 * transport_udp_common.c. */
#define PACKET_NAME_TABLE(X) \
    X(PACKET_INPUT, "INPUT") \
    X(PACKET_JOIN_REQUEST, "JOIN_REQUEST") \
    X(PACKET_CHAT_MESSAGE, "CHAT_MESSAGE") \
    X(PACKET_PING, "PING") \
    X(PACKET_MAP_ACK, "MAP_ACK") \
    X(PACKET_QUIT, "QUIT") \
    X(PACKET_STATE_SNAPSHOT, "STATE_SNAPSHOT") \
    X(PACKET_JOIN_ACCEPT, "JOIN_ACCEPT") \
    X(PACKET_JOIN_REJECT, "JOIN_REJECT") \
    X(PACKET_PLAYER_JOINED, "PLAYER_JOINED") \
    X(PACKET_PLAYER_LEFT, "PLAYER_LEFT") \
    X(PACKET_CHAT_BROADCAST, "CHAT_BROADCAST") \
    X(PACKET_FULL_STATE, "FULL_STATE") \
    X(PACKET_MAP_DELTA, "MAP_DELTA") \
    X(PACKET_BASE_STATE, "BASE_STATE") \
    X(PACKET_PILL_STATE, "PILL_STATE") \
    X(PACKET_PONG, "PONG") \
    X(PACKET_GAME_EVENT, "GAME_EVENT") \
    X(PACKET_MAP_DOWNLOAD, "MAP_DOWNLOAD") \
    X(PACKET_MAP_RESYNC_REQUEST, "MAP_RESYNC_REQUEST") \
    X(PACKET_PLAYER_LIST, "PLAYER_LIST") \
    X(PACKET_NAME_CHANGE, "NAME_CHANGE") \
    X(PACKET_ALLIANCE_REQUEST, "ALLIANCE_REQUEST") \
    X(PACKET_ALLIANCE_ACCEPT, "ALLIANCE_ACCEPT") \
    X(PACKET_ALLIANCE_LEAVE, "ALLIANCE_LEAVE") \
    X(PACKET_ALLIANCE_UPDATE, "ALLIANCE_UPDATE") \
    X(PACKET_LOCK_TOGGLE, "LOCK_TOGGLE") \
    X(PACKET_SERVER_SHUTDOWN, "SERVER_SHUTDOWN") \
    X(PACKET_LOBBY_TEAM_SET, "LOBBY_TEAM_SET") \
    X(PACKET_LOBBY_READY, "LOBBY_READY") \
    X(PACKET_LOBBY_ADD_BOT, "LOBBY_ADD_BOT") \
    X(PACKET_LOBBY_REMOVE_BOT, "LOBBY_REMOVE_BOT") \
    X(PACKET_LOBBY_UPDATE, "LOBBY_UPDATE") \
    X(PACKET_LOBBY_SETTINGS, "LOBBY_SETTINGS") \
    X(PACKET_LOBBY_SET_SETTING, "LOBBY_SET_SETTING") \
    X(PACKET_LOBBY_SETTING_CHG, "LOBBY_SETTING_CHG") \
    X(PACKET_LOBBY_OPEN_HOST, "LOBBY_OPEN_HOST") \
    X(PACKET_LOBBY_OPEN_HOST_CHG, "LOBBY_OPEN_HOST_CHG") \
    X(PACKET_LOBBY_TEAM_META, "LOBBY_TEAM_META") \
    X(PACKET_LOBBY_TEAM_META_CHG, "LOBBY_TEAM_META_CHG") \
    X(PACKET_LOBBY_TEAM_CLEAR, "LOBBY_TEAM_CLEAR") \
    X(PACKET_LOBBY_BOT_CONFIG, "LOBBY_BOT_CONFIG") \
    X(PACKET_LOBBY_BOT_CONFIG_CHG, "LOBBY_BOT_CONFIG_CHG") \
    X(PACKET_LOBBY_KICK, "LOBBY_KICK") \
    X(PACKET_KICKED, "KICKED") \
    X(PACKET_LOBBY_SET_BOT_BRAIN, "LOBBY_SET_BOT_BRAIN") \
    X(PACKET_LOBBY_BOT_BRAIN_CHG, "LOBBY_BOT_BRAIN_CHG") \
    X(PACKET_LOBBY_BRAIN_LIST, "LOBBY_BRAIN_LIST") \
    X(PACKET_LOBBY_SET_MAP, "LOBBY_SET_MAP") \
    X(PACKET_LOBBY_SET_PASSWORD, "LOBBY_SET_PASSWORD") \
    X(PACKET_LOBBY_MAP_LIST_REQ, "LOBBY_MAP_LIST_REQ") \
    X(PACKET_LOBBY_MAP_LIST_RSP, "LOBBY_MAP_LIST_RSP") \
    X(PACKET_LOBBY_MAP_SEARCH_REQ, "LOBBY_MAP_SEARCH_REQ") \
    X(PACKET_LOBBY_MAP_SEARCH_RSP, "LOBBY_MAP_SEARCH_RSP") \
    X(PACKET_LOBBY_MAP_UPLOAD_BEGIN, "LOBBY_MAP_UPLOAD_BEGIN") \
    X(PACKET_LOBBY_MAP_UPLOAD_CHUNK, "LOBBY_MAP_UPLOAD_CHUNK") \
    X(PACKET_LOBBY_MAP_UPLOAD_ACK, "LOBBY_MAP_UPLOAD_ACK") \
    X(PACKET_LOBBY_MAP_UPLOAD_DONE, "LOBBY_MAP_UPLOAD_DONE") \
    X(PACKET_LOBBY_MAP_USE_LOCAL, "LOBBY_MAP_USE_LOCAL") \
    X(PACKET_LOBBY_MAP_USE_LOCAL_NACK, "LOBBY_MAP_USE_LOCAL_NACK") \
    X(PACKET_LOBBY_MAP_PREVIEW_REQ, "LOBBY_MAP_PREVIEW_REQ") \
    X(PACKET_LOBBY_MAP_PREVIEW_ERR, "LOBBY_MAP_PREVIEW_ERR") \
    X(PACKET_LOBBY_PREVIEW_CANCEL, "LOBBY_PREVIEW_CANCEL") \
    X(PACKET_LOBBY_PREVIEW_COMMIT, "LOBBY_PREVIEW_COMMIT") \
    X(PACKET_LOBBY_PREVIEW_RANDOM, "LOBBY_PREVIEW_RANDOM") \
    X(PACKET_LOBBY_CLAIM_START, "LOBBY_CLAIM_START") \
    X(PACKET_COUNTDOWN, "COUNTDOWN") \
    X(PACKET_GAME_START, "GAME_START") \
    X(PACKET_GAME_OVER, "GAME_OVER") \
    X(PACKET_LOBBY_MAP_CHANGE, "LOBBY_MAP_CHANGE") \
    X(PACKET_WBN_REAUTH, "WBN_REAUTH") \
    X(PACKET_WBN_REKEY, "WBN_REKEY") \
    X(PACKET_BALANCE_REQUEST, "BALANCE_REQUEST") \
    X(PACKET_BALANCE_PROPOSAL, "BALANCE_PROPOSAL") \
    X(PACKET_BALANCE_APPLY, "BALANCE_APPLY") \
    X(PACKET_BALANCE_DISMISS, "BALANCE_DISMISS") \
    X(PACKET_MAP_SKIP_VOTE, "MAP_SKIP_VOTE") \
    X(PACKET_MAP_SKIP_STATE, "MAP_SKIP_STATE") \
    X(PACKET_GAME_VOTE_TOGGLE, "GAME_VOTE_TOGGLE") \
    X(PACKET_GAME_VOTE_STATE, "GAME_VOTE_STATE") \
    X(PACKET_PUNCH_REQUEST, "PUNCH_REQUEST") \
    X(PACKET_PUNCH_NOTIFY, "PUNCH_NOTIFY") \
    X(PACKET_PUNCH_REQUEST_ACK, "PUNCH_REQUEST_ACK") \
    X(PACKET_PUNCH_PROBE_REQUEST, "PUNCH_PROBE_REQUEST") \
    X(PACKET_PUNCH_PROBE_REPLY, "PUNCH_PROBE_REPLY") \
    X(PACKET_CONTROL_TICK, "CONTROL_TICK") \
    X(PACKET_CONTROL_ACK, "CONTROL_ACK") \
    X(PACKET_COMMAND_TICK, "COMMAND_TICK") \
    X(PACKET_COMMAND_ACK, "COMMAND_ACK") \
    X(PACKET_COMMAND_REJECTED, "COMMAND_REJECTED") \
    X(PACKET_BALANCE_FAILED, "BALANCE_FAILED")

int run_packet_type_names(void) {
    /* Every mapped type returns its exact name. */
#define X(sym, str) \
    UT_ASSERT_MSG(strcmp(packetTypeName(sym), (str)) == 0, \
                  "packetTypeName(" #sym ") mismatch");
    PACKET_NAME_TABLE(X)
#undef X

    /* 250 is not a defined PACKET_* (ids top out at 204), so it resolves to
     * the default arm. */
    UT_ASSERT_MSG(strcmp(packetTypeName(250), "UNKNOWN") == 0,
                  "unmapped packet type should be UNKNOWN");
    return 0;
}
