/*
 * Golden regression coverage for the generated flat-leaf-snapshot codecs.
 *
 * For each flat leaf message (Shell / TkExplosion / Base / Pill) this checks the
 * linked production pack/unpack pair from transport_udp_common.c, generated by
 * DEFINE_WIRE_CODEC over the field lists in wire_messages.h, against two sources
 * of vectors:
 *
 *   - committed golden fixtures in tests/fixtures/wire/<label>.hex (captured
 *     from a real loopback session by test_wire_corpus_capture), and
 *   - programmatic boundary vectors (every field 0, then every field at its
 *     type maximum), so coverage does not depend on which messages a session
 *     happened to emit.
 *
 * Per fixture vector it asserts: length equals the per-message WIRE_SIZE, the
 * generated unpack consumes the whole vector, and the generated pack reproduces
 * the golden bytes exactly. Per boundary vector it asserts pack returns
 * WIRE_SIZE and unpack(pack(s)) round-trips struct-identical. Once per message
 * it asserts WIRE_SIZE_OF(fields) equals the per-message WIRE_SIZE.
 *
 * No sockets and no file writes: it only reads committed fixtures.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "input_packet.h"            /* snapshot structs + *_WIRE_SIZE */
#include "transport_udp_internal.h"  /* generated pack/unpack prototypes */
#include "wire_codec.h"              /* WIRE_SIZE_OF */
#include "wire_messages.h"           /* the four *_FIELDS lists */
#include "test_harness.h"

#ifndef WB_WIRE_FIXTURE_DIR
#define WB_WIRE_FIXTURE_DIR "tests/fixtures/wire"
#endif

#define WC_BYTES        64
#define WC_MAX_VECTORS  64

/* Set each field to its type maximum, applied to a field list. */
#define WIRE_MAX_U8  0xFFu
#define WIRE_MAX_U16 0xFFFFu
#define WIRE_MAX_U32 0xFFFFFFFFu
#define FIELD_SET_MAX(type, name) s.name = (WIRE_MAX_##type);

/* Parse one hex char; -1 if not a hex digit. */
static int hexVal(int c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

/* Decode one lowercase-hex line into out (<= WC_BYTES). Returns byte count, or
 * -1 on a malformed line. */
static int decodeHexLine(const char *line, uint8_t *out) {
    int n = 0;
    while (line[0] && line[0] != '\n' && line[0] != '\r') {
        int hi, lo;
        if (n >= WC_BYTES) return -1;
        hi = hexVal((unsigned char)line[0]);
        lo = hexVal((unsigned char)line[1]);
        if (hi < 0 || lo < 0) return -1;
        out[n++] = (uint8_t)((hi << 4) | lo);
        line += 2;
    }
    return n;
}

/* Load tests/fixtures/wire/<label>.hex into vecs/lens. Returns the number of
 * vectors, or 0 if the file is absent (a missing fixture is not a failure;
 * boundary vectors still run). */
static int loadFixture(const char *label, uint8_t vecs[][WC_BYTES],
                       size_t *lens, int maxVecs) {
    char path[512];
    char line[256];
    FILE *f;
    int n = 0;
    snprintf(path, sizeof(path), "%s/%s.hex", WB_WIRE_FIXTURE_DIR, label);
    f = fopen(path, "r");
    if (!f) return 0;
    while (n < maxVecs && fgets(line, sizeof(line), f)) {
        int len;
        if (line[0] == '\n' || line[0] == '\r' || line[0] == '\0') continue;
        len = decodeHexLine(line, vecs[n]);
        if (len <= 0) continue;
        lens[n] = (size_t)len;
        n++;
    }
    fclose(f);
    return n;
}

/* Emit a per-message check function. Pack/Unpack are the linked production
 * symbols generated by DEFINE_WIRE_CODEC. */
#define MSG_CHECK_FN(FnName, Struct, Pack, Unpack, LABEL, WSIZE, FIELDS)       \
static int FnName(void) {                                                      \
    uint8_t vecs[WC_MAX_VECTORS][WC_BYTES];                                    \
    size_t  lens[WC_MAX_VECTORS];                                             \
    int n, k;                                                                  \
    UT_ASSERT_MSG(WIRE_SIZE_OF(FIELDS) == (WSIZE),                             \
                  LABEL " (d) WIRE_SIZE_OF mismatch");                         \
    n = loadFixture(LABEL, vecs, lens, WC_MAX_VECTORS);                        \
    for (k = 0; k < n; k++) {                                                  \
        Struct s;                                                             \
        uint8_t gen[WC_BYTES];                                                \
        UT_ASSERT_MSG(lens[k] == (WSIZE), LABEL " fixture wrong length");      \
        memset(&s, 0, sizeof(s));                                             \
        UT_ASSERT_MSG(Unpack(vecs[k], lens[k], &s) == (int)(WSIZE),            \
                      LABEL " generated unpack short read");                   \
        memset(gen, 0, sizeof(gen));                                          \
        UT_ASSERT_MSG(Pack(gen, &s) == (int)(WSIZE),                          \
                      LABEL " generated pack wrong length");                   \
        UT_ASSERT_MSG(memcmp(gen, vecs[k], (WSIZE)) == 0,                      \
                      LABEL " generated pack != golden");                      \
    }                                                                          \
    {                                                                          \
        Struct s, su;                                                         \
        uint8_t g[WC_BYTES];                                                  \
        int pass;                                                             \
        for (pass = 0; pass < 2; pass++) {                                    \
            memset(&s, 0, sizeof(s));                                         \
            if (pass == 1) { FIELDS(FIELD_SET_MAX) }                          \
            memset(g, 0, sizeof(g));                                          \
            UT_ASSERT_MSG(Pack(g, &s) == (int)(WSIZE),                        \
                          LABEL " boundary pack wrong length");               \
            memset(&su, 0, sizeof(su));                                       \
            UT_ASSERT_MSG(Unpack(g, (WSIZE), &su) == (int)(WSIZE),            \
                          LABEL " boundary unpack short read");               \
            UT_ASSERT_MSG(memcmp(&s, &su, sizeof(s)) == 0,                    \
                          LABEL " boundary round-trip differ");              \
        }                                                                      \
    }                                                                          \
    return 0;                                                                  \
}

MSG_CHECK_FN(check_shell, ShellSnapshot, packShellSnapshot, unpackShellSnapshot,
             "shell_snapshot", SHELL_SNAPSHOT_WIRE_SIZE, SHELL_SNAPSHOT_FIELDS)
MSG_CHECK_FN(check_tk, TkExplosionSnapshot, packTkExplosionSnapshot,
             unpackTkExplosionSnapshot, "tk_explosion_snapshot",
             TK_EXPLOSION_SNAPSHOT_WIRE_SIZE, TK_EXPLOSION_SNAPSHOT_FIELDS)
MSG_CHECK_FN(check_base, BaseSnapshot, packBaseSnapshot, unpackBaseSnapshot,
             "base_snapshot", BASE_SNAPSHOT_WIRE_SIZE, BASE_SNAPSHOT_FIELDS)
MSG_CHECK_FN(check_pill, PillSnapshot, packPillSnapshot, unpackPillSnapshot,
             "pill_snapshot", PILL_SNAPSHOT_WIRE_SIZE, PILL_SNAPSHOT_FIELDS)

int run_wire_corpus(void) {
    if (check_shell() != 0) return 1;
    if (check_tk() != 0) return 1;
    if (check_base() != 0) return 1;
    if (check_pill() != 0) return 1;
    return 0;
}
