/*
 * WinBoloUnitTests entry point. Dispatches one named test per
 * invocation so each CTest entry maps to a single test case.
 *
 *   WinBoloUnitTests --test <name>      run a single test
 *   WinBoloUnitTests --list             print test names
 *   WinBoloUnitTests                    run every test in sequence,
 *                                      bar the fixture writers
 */
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <SDL3/SDL.h>

#include "global.h"
#include "test_harness.h"

#include "everard_map.h"
#include "game_sim.h"
#include "sim_rules.h"
#include "server_sim.h"
#include "server_sim_lifecycle.h"

typedef struct {
    const char *name;
    int (*fn)(void);
} UnitTestEntry;

/* Tests that rewrite a committed fixture. Running one is how the fixture is
 * meant to be regenerated, so they stay dispatchable by name, but the
 * run-everything path below skips them — otherwise invoking the binary bare
 * silently rewrites tests/fixtures and leaves the tree dirty. CMake leaves
 * these out of _unit_test_names for the same reason; this list is what keeps
 * the two from disagreeing. */
static const char *const s_fixtureWriters[] = {
    "wire_corpus_capture",
    "wbv_v2_capture",
    "wbv_summary_capture",
    "spectator_seed_capture",
};

static bool isFixtureWriter(const char *name) {
    size_t i;
    for (i = 0; i < sizeof(s_fixtureWriters) / sizeof(s_fixtureWriters[0]); i++) {
        if (strcmp(name, s_fixtureWriters[i]) == 0) {
            return true;
        }
    }
    return false;
}

static const UnitTestEntry s_tests[] = {
    { "transport_local_passive_threads", run_transport_local_passive_threads },
    { "sp_subscriber_delivery",          run_sp_subscriber_delivery          },
    { "active_sim_armed_on_lobby_tick",  run_active_sim_armed_on_lobby_tick  },
    { "active_sim_cleared_on_cross_thread_destroy",
      run_active_sim_cleared_on_cross_thread_destroy },
    { "active_local_input_to_shot",      run_active_local_input_to_shot      },
    { "sp_shoot_through_timer",          run_sp_shoot_through_timer          },
    { "prefs_document_roundtrip",        run_prefs_document_roundtrip        },
    { "prefs_keys_roundtrip",            run_prefs_keys_roundtrip            },
    { "prefs_doc_roundtrip",             run_prefs_doc_roundtrip             },
    { "prefs_doc_defaults",              run_prefs_doc_defaults              },
    { "prefs_doc_special_chars",         run_prefs_doc_special_chars         },
    { "prefs_doc_unknown_preserved",     run_prefs_doc_unknown_preserved     },
    { "prefs_doc_save_atomic",           run_prefs_doc_save_atomic           },
    { "prefs_api_roundtrip",             run_prefs_api_roundtrip             },
    { "prefs_api_defaults",              run_prefs_api_defaults              },
    { "prefs_api_corrupt_backup",        run_prefs_api_corrupt_backup        },
    { "prefs_api_debounce",              run_prefs_api_debounce              },
    { "prefs_api_shutdown_flush",        run_prefs_api_shutdown_flush        },
    { "prefs_api_upload_excludes_local", run_prefs_api_upload_excludes_local },
    { "prefs_api_sync_dirty",            run_prefs_api_sync_dirty            },
    { "prefs_api_device_identity",       run_prefs_api_device_identity       },
    { "prefs_api_adopt_server",          run_prefs_api_adopt_server          },
    { "prefs_api_mark_synced",           run_prefs_api_mark_synced           },
    { "join_running_phase_not_lobby",    run_join_running_phase_not_lobby    },
    { "lobby_settings_codec_and_apply",  run_lobby_settings_codec_and_apply  },
    { "lobby_team_meta_codec_and_apply", run_lobby_team_meta_codec_and_apply },
    { "lobby_bot_config_codec_and_apply",run_lobby_bot_config_codec_and_apply},
    { "lobby_bot_brain_codec_and_apply", run_lobby_bot_brain_codec_and_apply },
    { "lobby_brain_list_codec_and_apply",run_lobby_brain_list_codec_and_apply},
    { "lobby_sync_complete_codec_roundtrip", run_lobby_sync_complete_codec_roundtrip },
    { "lobby_rating_posted_codec_roundtrip", run_lobby_rating_posted_codec_roundtrip },
    { "command_codec_roundtrip_variants",run_command_codec_roundtrip_variants},
    { "command_codec_lobby_claim_start", run_command_codec_lobby_claim_start },
    { "command_codec_rating_posted",     run_command_codec_rating_posted     },
    { "command_codec_view_state",        run_command_codec_view_state        },
    { "command_codec_view_cycle",        run_command_codec_view_cycle        },
    { "command_codec_ping",              run_command_codec_ping              },
    { "lobby_claim_start_host_swaps_occupied",
                                         run_lobby_claim_start_host_swaps_occupied },
    { "lobby_claim_start_host_swap_into_none",
                                         run_lobby_claim_start_host_swap_into_none },
    { "lobby_claim_start_host_assign_onto_own",
                                         run_lobby_claim_start_host_assign_onto_own },
    { "lobby_claim_start_non_host_occupied_rejected",
                                         run_lobby_claim_start_non_host_occupied_rejected },
    { "lobby_claim_start_non_host_other_slot_rejected",
                                         run_lobby_claim_start_non_host_other_slot_rejected },
    { "lobby_claim_start_self_free_and_release",
                                         run_lobby_claim_start_self_free_and_release },
    { "lobby_claim_start_validation",    run_lobby_claim_start_validation },
    { "player_mute_mask_roundtrip",      run_player_mute_mask_roundtrip      },
    { "command_codec_cmdseq_slot",       run_command_codec_cmdseq_slot       },
    { "command_codec_bounds_checks",     run_command_codec_bounds_checks     },
    { "command_rejected_parks_name_codes",        run_command_rejected_parks_name_codes        },
    { "command_rejected_ignores_other_slot",      run_command_rejected_ignores_other_slot      },
    { "command_rejected_clear_resets_both_fields",run_command_rejected_clear_resets_both_fields},
    { "live_stats_kill_credits_killer_and_victim", run_live_stats_kill_credits_killer_and_victim },
    { "live_stats_suicide_counts_death_only",      run_live_stats_suicide_counts_death_only      },
    { "live_stats_lgm_loss_splits_victim_and_killer", run_live_stats_lgm_loss_splits_victim_and_killer },
    { "live_stats_captures_credit_new_owner",      run_live_stats_captures_credit_new_owner      },
    { "live_stats_out_of_range_slot_ignored",      run_live_stats_out_of_range_slot_ignored      },
    { "live_stats_cleared_on_running_phase",       run_live_stats_cleared_on_running_phase       },
    { "shell_death_codec_roundtrip",              run_shell_death_codec_roundtrip              },
    { "shell_death_culls_matching_predicted_shell",run_shell_death_culls_matching_predicted_shell},
    { "shell_death_rejected_culls_without_impact",run_shell_death_rejected_culls_without_impact},
    { "lobby_add_bot_rejects_empty_brain_path",   run_lobby_add_bot_rejects_empty_brain_path   },
    { "lobby_add_bot_rejects_ai_none",            run_lobby_add_bot_rejects_ai_none            },
    { "lobby_add_bot_rejects_not_in_lobby",       run_lobby_add_bot_rejects_not_in_lobby       },
    { "lobby_add_bot_rejects_non_host_sender",    run_lobby_add_bot_rejects_non_host_sender    },
    { "lobby_bot_count_counts_only_connected_bots", run_lobby_bot_count_counts_only_connected_bots },
    { "lobby_maxbots_cap_boundary",               run_lobby_maxbots_cap_boundary               },
    { "lobby_add_bot_rejects_when_at_maxbots",    run_lobby_add_bot_rejects_when_at_maxbots    },
    { "transfer_host_promotes_target",             run_transfer_host_promotes_target             },
    { "transfer_host_rejects_non_host_sender",     run_transfer_host_rejects_non_host_sender     },
    { "transfer_host_openhost_does_not_grant",     run_transfer_host_openhost_does_not_grant     },
    { "transfer_host_rejects_self",                run_transfer_host_rejects_self                },
    { "transfer_host_rejects_unconnected",         run_transfer_host_rejects_unconnected         },
    { "transfer_host_rejects_bot_target",          run_transfer_host_rejects_bot_target          },
    { "command_queue_first_submit_drains",        run_command_queue_first_submit_drains        },
    { "command_queue_second_submit_does_not_drain", run_command_queue_second_submit_does_not_drain },
    { "command_queue_ack_drains_pending_tail",    run_command_queue_ack_drains_pending_tail    },
    { "command_queue_ack_clearing_queue_skips_drain", run_command_queue_ack_clearing_queue_skips_drain },
    { "game_vote_state_codec_back_to_lobby",     run_game_vote_state_codec_back_to_lobby     },
    { "game_vote_state_codec_surrender_passed",  run_game_vote_state_codec_surrender_passed  },
    { "game_vote_state_decoder_rejects_short",   run_game_vote_state_decoder_rejects_short   },
    { "vote_surrender_rejects_unassigned_caller",   run_vote_surrender_rejects_unassigned_caller   },
    { "vote_surrender_starts_for_real_team_caller", run_vote_surrender_starts_for_real_team_caller },
    { "vote_surrender_rejects_three_active_teams",  run_vote_surrender_rejects_three_active_teams  },
    { "vote_surrender_state_withheld_from_other_team",  run_vote_surrender_state_withheld_from_other_team  },
    { "vote_surrender_newswire_hidden_from_other_team", run_vote_surrender_newswire_hidden_from_other_team },
    { "vote_surrender_newswire_shown_to_own_team",      run_vote_surrender_newswire_shown_to_own_team      },
    { "vote_back_to_lobby_newswire_stays_public",       run_vote_back_to_lobby_newswire_stays_public       },
    { "vote_surrender_may_answer_rule",                 run_vote_surrender_may_answer_rule                 },
    { "base_win_ends_round_immediately",                run_base_win_ends_round_immediately                },
    { "base_win_dead_base_blocks_the_win",              run_base_win_dead_base_blocks_the_win              },
    { "base_win_fires_when_dead_base_regenerates",      run_base_win_fires_when_dead_base_regenerates      },
    { "base_win_quitonwin_with_lobby_returns_to_lobby", run_base_win_quitonwin_with_lobby_returns_to_lobby },
    { "base_win_nolobby_quitonwin_is_instant",          run_base_win_nolobby_quitonwin_is_instant          },
    { "base_win_reports_the_winner",                    run_base_win_reports_the_winner                    },
    { "manual_vote_countdown_survives_lost_base",       run_manual_vote_countdown_survives_lost_base       },
    { "surrender_credits_the_opposing_team",            run_surrender_credits_the_opposing_team            },
    { "win_during_manual_countdown_resolves_as_vote",   run_win_during_manual_countdown_resolves_as_vote   },
    { "abandoned_round_reports_nothing",                run_abandoned_round_reports_nothing                },
    { "round_stats_zeroed_on_fresh_sim",            run_round_stats_zeroed_on_fresh_sim            },
    { "round_stats_kill_basic",                     run_round_stats_kill_basic                     },
    { "round_stats_drown_not_suicide",              run_round_stats_drown_not_suicide              },
    { "round_stats_suicide_shell",                  run_round_stats_suicide_shell                  },
    { "round_stats_mine_death",                     run_round_stats_mine_death                     },
    { "round_stats_trees_wasted_and_pills_dropped", run_round_stats_trees_wasted_and_pills_dropped },
    { "round_stats_capture_steal",                  run_round_stats_capture_steal                  },
    { "round_stats_base_capture_steal",             run_round_stats_base_capture_steal             },
    { "round_stats_lgm",                            run_round_stats_lgm                            },
    { "round_stats_lifecycle_reset",                run_round_stats_lifecycle_reset                },
    { "round_stats_reset_clears_notables",          run_round_stats_reset_clears_notables          },
    { "round_stats_notables_ordered",               run_round_stats_notables_ordered               },
    { "round_stats_leaver_dropped",                 run_round_stats_leaver_dropped                 },
    { "round_stats_attribution_callbacks",          run_round_stats_attribution_callbacks          },
    { "round_stats_direct_damage",                  run_round_stats_direct_damage                  },
    { "round_stats_mine_owner_api",                 run_round_stats_mine_owner_api                 },
    { "round_stats_mine_damage",                    run_round_stats_mine_damage                    },
    { "round_stats_leaver_clears_mines",            run_round_stats_leaver_clears_mines            },
    { "mine_kill_publishes_event",                  run_mine_kill_publishes_event                  },
    { "mine_kill_on_boat_publishes_event",          run_mine_kill_on_boat_publishes_event          },
    { "mine_kill_own_mine_names_self",              run_mine_kill_own_mine_names_self              },
    { "awards_basic_winners",                       run_awards_basic_winners                       },
    { "awards_tiebreak",                            run_awards_tiebreak                            },
    { "awards_omission",                            run_awards_omission                            },
    { "awards_floors",                              run_awards_floors                              },
    { "awards_include_bots",                        run_awards_include_bots                        },
    { "awards_subset_basic",                        run_awards_subset_basic                        },
    { "awards_subset_deterministic",                run_awards_subset_deterministic                },
    { "round_stats_codec_roundtrip",                run_round_stats_codec_roundtrip                },
    { "round_stats_codec_rejects_bad_key",          run_round_stats_codec_rejects_bad_key          },
    { "round_stats_codec_worstcase",                run_round_stats_codec_worstcase                },
    { "round_stats_build_summary",                  run_round_stats_build_summary                  },
    { "round_stats_summary_highlights",             run_round_stats_summary_highlights             },
    { "round_stats_client_ingest",                  run_round_stats_client_ingest                  },
    { "round_stats_track_records",                  run_round_stats_track_records                  },
    { "round_stats_track_cap",                      run_round_stats_track_cap                      },
    { "round_stats_derive_equivalence",             run_round_stats_derive_equivalence             },
    { "highlights_cluster_wipe",                    run_highlights_cluster_wipe                    },
    { "highlights_wipe_team_bonus",                 run_highlights_wipe_team_bonus                 },
    { "highlights_objective_steal",                 run_highlights_objective_steal                 },
    { "highlights_award_anchor",                    run_highlights_award_anchor                    },
    { "highlights_selection",                       run_highlights_selection                       },
    { "highlights_lead_in",                         run_highlights_lead_in                         },
    { "highlights_empty",                           run_highlights_empty                           },
    { "territory_shift_basic",                      run_territory_shift_basic                      },
    { "territory_shift_bounded",                    run_territory_shift_bounded                    },
    { "highlights_turning_point",                   run_highlights_turning_point                   },
    { "territory_recent_damage",                    run_territory_recent_damage                    },
    { "highlights_front_collapse",                  run_highlights_front_collapse                  },
    { "highlights_award_anchor_density",            run_highlights_award_anchor_density            },
    { "highlights_time_spread",                     run_highlights_time_spread                     },
    { "highlights_multi_lgm",                       run_highlights_multi_lgm                       },
    { "highlights_fumble",                          run_highlights_fumble                          },
    { "highlights_rare_death",                      run_highlights_rare_death                      },
    { "highlights_award_dedup",                     run_highlights_award_dedup                     },
    { "highlights_pickup_spree",                    run_highlights_pickup_spree                    },
    { "highlights_action_density",                  run_highlights_action_density                  },
    { "lv_stats_clip_time_format",                  run_lv_stats_clip_time_format                  },
    { "attribution_track_schema",                   run_attribution_track_schema                   },
    { "vote_toggle_standalone_no_does_nothing",            run_vote_toggle_standalone_no_does_nothing            },
    { "vote_toggle_invalid_mode_dropped",                  run_vote_toggle_invalid_mode_dropped                  },
    { "vote_toggle_yes_opens_vote",                        run_vote_toggle_yes_opens_vote                        },
    { "vote_toggle_no_during_running_records_answered",    run_vote_toggle_no_during_running_records_answered    },
    { "vote_back_to_lobby_blocked_without_lobby",          run_vote_back_to_lobby_blocked_without_lobby          },
    { "vote_surrender_blocked_without_lobby",              run_vote_surrender_blocked_without_lobby              },
    { "lobby_set_team_clamps_max_tanks",            run_lobby_set_team_clamps_max_tanks            },
    { "lobby_set_team_accepts_max_legal",           run_lobby_set_team_accepts_max_legal           },
    { "lobby_set_team_accepts_unassigned",          run_lobby_set_team_accepts_unassigned          },
    { "lobby_set_team_clamps_above_max",            run_lobby_set_team_clamps_above_max            },
    { "server_text_codec_via_chat_wire",         run_server_text_codec_via_chat_wire         },
    { "md5_rfc1321_vectors",                     run_md5_rfc1321_vectors                     },
    { "md5_streaming_matches_oneshot",           run_md5_streaming_matches_oneshot           },
    { "md5_block_boundaries",                    run_md5_block_boundaries                    },
    { "md5_to_hex",                              run_md5_to_hex                              },
    { "rand_save_restore",                       run_rand_save_restore                       },
    { "pill_armour_intank_roundtrip",            run_pill_armour_intank_roundtrip            },
    { "base_event_classification",               run_base_event_classification               },
    { "ranked_flag_persists_with_one_player",    run_ranked_flag_persists_with_one_player    },
    { "ranked_shape_gate",                       run_ranked_shape_gate                       },
    { "lobby_lock_bit_lookup",                   run_lobby_lock_bit_lookup                   },
    { "lobby_lock_rejects_settings",             run_lobby_lock_rejects_settings             },
    { "lobby_lock_mask_roundtrip",               run_lobby_lock_mask_roundtrip               },
    { "view_policy_defaults",                    run_view_policy_defaults                    },
    { "view_policy_apply_validates",             run_view_policy_apply_validates             },
    { "view_policy_lock_bits",                   run_view_policy_lock_bits                   },
    { "view_policy_lobby_reset",                 run_view_policy_lobby_reset                 },
    { "classic_mode_defaults",                   run_classic_mode_defaults                   },
    { "classic_mode_forces_views",               run_classic_mode_forces_views               },
    { "classic_mode_lock_bit",                   run_classic_mode_lock_bit                   },
    { "classic_mode_lock_implied",               run_classic_mode_lock_implied               },
    { "classic_mode_lock_blocks_dispatch",       run_classic_mode_lock_blocks_dispatch       },
    { "classic_mode_lobby_reset",                run_classic_mode_lobby_reset                },
    { "allies_in_trees_defaults",                run_allies_in_trees_defaults                },
    { "allies_in_trees_classic_mode",            run_allies_in_trees_classic_mode            },
    { "info_packet_view_policy_layout",          run_info_packet_view_policy_layout          },
    { "info_packet_view_policy_length_tier",     run_info_packet_view_policy_length_tier     },
    { "upload_cap_enforced",                     run_upload_cap_enforced                     },
    { "map_field_clamps_evil",                   run_map_field_clamps_evil                   },
    { "map_field_clamps_passthrough",            run_map_field_clamps_passthrough            },
    { "map_field_clamps_angry_start",            run_map_field_clamps_angry_start            },
    { "map_field_clamps_no_sim",                 run_map_field_clamps_no_sim                 },
    { "map_reload_rollback",                     run_map_reload_rollback                     },
    { "map_read_memory_matches_file",            run_map_read_memory_matches_file            },
    { "map_read_memory_handbuilt",               run_map_read_memory_handbuilt               },
    { "map_convert_file_to_compressed",          run_map_convert_file_to_compressed          },
    { "map_read_memory_rejects_garbage",         run_map_read_memory_rejects_garbage         },
    { "upload_busy_predicate",                   run_upload_busy_predicate                   },
    { "upload_filename_safe",                    run_upload_filename_safe                    },
    { "lobby_time_minutes_valid",                run_lobby_time_minutes_valid                },
    { "lobby_bot_name_rejects_reserved_prefix",  run_lobby_bot_name_rejects_reserved_prefix  },
    { "lobby_bot_name_rejects_disallowed_char",  run_lobby_bot_name_rejects_disallowed_char  },
    { "lobby_bot_name_rejects_collision",        run_lobby_bot_name_rejects_collision        },
    { "lobby_bot_name_skip_does_not_bypass_validator_prefix",  run_lobby_bot_name_skip_does_not_bypass_validator_prefix  },
    { "lobby_bot_name_skip_does_not_bypass_validator_control", run_lobby_bot_name_skip_does_not_bypass_validator_control },
    { "lobby_bot_name_skip_excludes_self_from_uniqueness",     run_lobby_bot_name_skip_excludes_self_from_uniqueness     },
    { "lobby_bot_name_accepts_clean_unique",     run_lobby_bot_name_accepts_clean_unique     },
    { "bot_pool_builtin_defaults",               run_bot_pool_builtin_defaults               },
    { "bot_pool_install_and_clamp",              run_bot_pool_install_and_clamp              },
    { "bot_pool_install_dedup_and_drop",         run_bot_pool_install_dedup_and_drop         },
    { "bot_pool_reset_restores_builtin",         run_bot_pool_reset_restores_builtin         },
    { "bot_pool_pick_unique_and_overflow",       run_bot_pool_pick_unique_and_overflow       },
    { "bot_pool_json_load_roundtrip",            run_bot_pool_json_load_roundtrip            },
    { "bot_pool_json_missing_file_keeps_active", run_bot_pool_json_missing_file_keeps_active },
    { "bot_pool_wire_roundtrip",                 run_bot_pool_wire_roundtrip                 },
    { "bot_pool_wire_builtin_roundtrip",         run_bot_pool_wire_builtin_roundtrip         },
    { "bot_pool_wire_rejects_garbage",           run_bot_pool_wire_rejects_garbage           },
    { "proxy_meta_parse_roundtrip",              run_proxy_meta_parse_roundtrip              },
    { "proxy_meta_parse_truncation_safe",        run_proxy_meta_parse_truncation_safe        },
    { "proxy_meta_parse_oversized_name",         run_proxy_meta_parse_oversized_name         },
    { "proxy_meta_parse_prefs_clamps",           run_proxy_meta_parse_prefs_clamps           },
    { "tick_core_active_local_no_double_step",   run_tick_core_active_local_no_double_step   },
    { "tick_core_passive_local_pumps_keys_half", run_tick_core_passive_local_pumps_keys_half },
    { "tick_core_lobby_preserves_parity",        run_tick_core_lobby_preserves_parity        },
    { "transport_ticks_server_lifecycle",        run_transport_ticks_server_lifecycle        },
    { "await_join_connected_immediate",          run_await_join_connected_immediate          },
    { "await_join_lobby_latch",                  run_await_join_lobby_latch                  },
    { "await_join_timeout_and_error",            run_await_join_timeout_and_error            },
    { "bot_pool_wire_chunk_transport",           run_bot_pool_wire_chunk_transport           },
    { "lobby_map_list_chunked",                  run_lobby_map_list_chunked                  },
    { "lobby_map_search_chunked",                run_lobby_map_search_chunked                },
    { "wbn_bearer_state",                        run_wbn_bearer_state                        },
    { "wbn_rekey_codec",                         run_wbn_rekey_codec                         },
    { "wbn_news_parse",                          run_wbn_news_parse                          },
    { "wbn_news_free_during_fetch",              run_wbn_news_free_during_fetch              },
    { "wbn_country_cache",                       run_wbn_country_cache                       },
    { "wbn_prefs_parse_get",                     run_wbn_prefs_parse_get                     },
    { "wbn_prefs_parse_updatedat",               run_wbn_prefs_parse_updatedat               },
    { "wbn_prefs_decide",                        run_wbn_prefs_decide                        },
    { "wbn_prefs_build_put_body",                run_wbn_prefs_build_put_body                },
    { "wbn_serverlist_parse",                    run_wbn_serverlist_parse                    },
    { "wbn_serverlist_players",                  run_wbn_serverlist_players                  },
    { "wbn_serverlist_motd",                     run_wbn_serverlist_motd                     },
    { "wbn_serverlist_malformed",                run_wbn_serverlist_malformed                },
    { "wbn_map_parse",                           run_wbn_map_parse                           },
    { "brain_crash_log_writes_file",             run_brain_crash_log_writes_file             },
    { "brain_crash_log_falls_back_to_luaptr",    run_brain_crash_log_falls_back_to_luaptr    },
    { "brain_inbox_push_peek_fifo",              run_brain_inbox_push_peek_fifo              },
    { "brain_inbox_overflow_drops_oldest",       run_brain_inbox_overflow_drops_oldest       },
    { "brain_inbox_legacy_drain_fifo",           run_brain_inbox_legacy_drain_fifo           },
    { "brain_inbox_clear_resets",                run_brain_inbox_clear_resets                },
    { "brain_list_scan_path_resolves",           run_brain_list_scan_path_resolves           },
    { "bolo_rand_golden_sequence",               run_bolo_rand_golden_sequence               },
    { "pf_dijkstra_no_solid_corner_cut",         run_pf_dijkstra_no_solid_corner_cut         },
    { "pf_astar_no_solid_corner_cut",            run_pf_astar_no_solid_corner_cut            },
    { "pf_costto_no_solid_corner_cut",           run_pf_costto_no_solid_corner_cut           },
    { "net_impair",                              run_net_impair                              },
    { "channel_mux",                             run_channel_mux                             },
    { "spectator_ring",                          run_spectator_ring                          },
    { "spectator_ring_nolog",                    run_spectator_ring_nolog                    },
    { "spectator_replay",                        run_spectator_replay                        },
    { "spectator_config",                        run_spectator_config                        },
    { "spectator_join",                          run_spectator_join                          },
    { "spectator_roster_publish",                run_spectator_roster_publish                },
    { "spectator_slot_codec",                    run_spectator_slot_codec                    },
    { "spectator_chat_codec",                    run_spectator_chat_codec                    },
    { "stats_seed_codec",                        run_stats_seed_codec                        },
    { "spectator_chat_routing",                  run_spectator_chat_routing                  },
    { "spectator_chat_log",                      run_spectator_chat_log                      },
    { "spectator_chat_catchup",                  run_spectator_chat_catchup                  },
    { "spectator_connect",                       run_spectator_connect                       },
    { "spectator_client_lobby_intake",           run_spectator_client_lobby_intake           },
    { "spectator_command_reject",                run_spectator_command_reject                },
    { "spectator_lobby_readonly",                run_spectator_lobby_readonly                },
    { "spectator_capture",                       run_spectator_capture                       },
    { "spectator_log",                           run_spectator_log                           },
    { "spectator_seed",                          run_spectator_seed                          },
    { "spectator_lobby_subscribe",               run_spectator_lobby_subscribe               },
    { "spectator_control_filter",                run_spectator_control_filter                },
    { "spectator_subscriber_capacity",           run_spectator_subscriber_capacity           },
    { "spectator_roster_to_spectators",          run_spectator_roster_to_spectators          },
    { "spectator_lobby_cutover",                 run_spectator_lobby_cutover                 },
    { "loopback_spectator_lobby",                run_loopback_spectator_lobby                },
    { "bulk_transfer",                           run_bulk_transfer                           },
    { "round_log_header_roundtrip",              run_round_log_header_roundtrip              },
    { "round_log_sink_rejection_realigns",       run_round_log_sink_rejection_realigns       },
    { "round_log_refused_when_unavailable",      run_round_log_refused_when_unavailable      },
    { "overflow_guards",                         run_overflow_guards                         },
    { "channel_reset_codec_roundtrip",           run_channel_reset_codec_roundtrip           },
    { "channel_reset_two_slot_baselines",        run_channel_reset_two_slot_baselines        },
    { "countdown_abort_publishes_phase",         run_countdown_abort_publishes_phase         },
    { "lobby_auto_unready_clears_humans_keeps_bots",
                                                 run_lobby_auto_unready_clears_humans_keeps_bots },
    { "mapdir_root_fallback",                    run_mapdir_root_fallback                    },
    { "bot_chat_send_to_human_lands_in_human_inbox",
                                                 run_bot_chat_send_to_human_lands_in_human_inbox },
    { "bot_chat_send_to_other_bot_lands_in_recipient_inbox",
                                                 run_bot_chat_send_to_other_bot_lands_in_recipient_inbox },
    { "bot_chat_receive_from_human_lands_in_bot_inbox",
                                                 run_bot_chat_receive_from_human_lands_in_bot_inbox },
    { "bot_chat_receive_from_other_bot_via_broadcast",
                                                 run_bot_chat_receive_from_other_bot_via_broadcast },
    { "internal_msg_reaches_allied_bot",         run_internal_msg_reaches_allied_bot         },
    { "internal_msg_skips_sender_self",          run_internal_msg_skips_sender_self          },
    { "internal_msg_skips_non_allied_bot",       run_internal_msg_skips_non_allied_bot       },
    { "internal_msg_skips_inactive_bot_slot",    run_internal_msg_skips_inactive_bot_slot    },
    { "internal_msg_handles_oversized_body",     run_internal_msg_handles_oversized_body     },
    { "internal_msg_null_inputs_are_noop",       run_internal_msg_null_inputs_are_noop       },
    { "alliance_request_flags_addressed",        run_alliance_request_flags_addressed        },
    { "alliance_request_ignores_other_slot",     run_alliance_request_ignores_other_slot     },
    { "phase_lobby_sets_inlobby",                run_phase_lobby_sets_inlobby                },
    { "phase_gameover_resets_in_game",           run_phase_gameover_resets_in_game           },
    { "player_join_appends_lobby_chat",          run_player_join_appends_lobby_chat          },
    { "player_join_self_does_not_announce",      run_player_join_self_does_not_announce      },
    { "player_leave_appends_lobby_chat",         run_player_leave_appends_lobby_chat         },
    { "lobby_settings_clears_balance_proposal",  run_lobby_settings_clears_balance_proposal  },
    { "reset_round_state_preserves_identity",    run_reset_round_state_preserves_identity    },
    { "start_game_preserves_client_flags",       run_start_game_preserves_client_flags       },
    { "return_to_lobby_drops_wbn_keeps_identity", run_return_to_lobby_drops_wbn_keeps_identity },
    { "wbn_lobby_update_deferred_during_rotation", run_wbn_lobby_update_deferred_during_rotation },
    { "wbn_lobby_update_sends_when_not_rotating",  run_wbn_lobby_update_sends_when_not_rotating  },
    { "maprotate_restarts_round_and_rearms",       run_maprotate_restarts_round_and_rearms       },
    { "maprotate_defers_wbn_update_until_key_rotated", run_maprotate_defers_wbn_update_until_key_rotated },
    { "maprotate_gameover_is_not_terminal",        run_maprotate_gameover_is_not_terminal        },
    { "maprotate_boot_does_not_rotate_while_empty", run_maprotate_boot_does_not_rotate_while_empty },
    { "maprotate_vote_return_is_not_terminal",     run_maprotate_vote_return_is_not_terminal     },
    { "wbn_join_keyed_on_reauth",                  run_wbn_join_keyed_on_reauth                  },
    { "wbn_join_anonymous_on_grace",               run_wbn_join_anonymous_on_grace               },
    { "wbn_join_idempotent_reauth_no_double",      run_wbn_join_idempotent_reauth_no_double      },
    { "wbn_join_disconnect_drops",                 run_wbn_join_disconnect_drops                 },
    { "wbn_join_rearm_per_session",                run_wbn_join_rearm_per_session                },
    { "wbn_join_rekey_target_gate",                run_wbn_join_rekey_target_gate                },
    { "join_collision_unverified_no_auth_rejects", run_join_collision_unverified_no_auth_rejects },
    { "join_collision_unverified_will_auth_admits", run_join_collision_unverified_will_auth_admits },
    { "join_collision_verified_rejects_will_auth", run_join_collision_verified_rejects_will_auth },
    { "join_collision_verified_flag_irrelevant",   run_join_collision_verified_flag_irrelevant   },
    { "claim_resolve_free_promotes",               run_claim_resolve_free_promotes               },
    { "claim_resolve_unverified_preempts",         run_claim_resolve_unverified_preempts         },
    { "claim_resolve_verified_keeps_temp",         run_claim_resolve_verified_keeps_temp         },
    { "claim_resolve_free_ignores_holder_flag",    run_claim_resolve_free_ignores_holder_flag    },
    { "remove_player_clears_slot",                 run_remove_player_clears_slot                 },
    { "return_to_lobby_clears_phantom_slot",       run_return_to_lobby_clears_phantom_slot       },
    { "last_human_leave_returns_to_lobby",         run_last_human_leave_returns_to_lobby         },
    { "empty_return_to_lobby_removes_bots_and_unlocks", run_empty_return_to_lobby_removes_bots_and_unlocks },
    { "humanless_round_does_not_autoend",          run_humanless_round_does_not_autoend          },
    { "host_departs_promotes_lowest_human",        run_host_departs_promotes_lowest_human        },
    { "nonhost_departs_keeps_host",                run_nonhost_departs_keeps_host                },
    { "host_reassign_skips_bots",                  run_host_reassign_skips_bots                  },
    { "lobby_reset_clears_host_slot",              run_lobby_reset_clears_host_slot              },
    { "autolock_lobby_stays_open",                 run_autolock_lobby_stays_open                 },
    { "autolock_locks_on_start_wire",              run_autolock_locks_on_start_wire              },
    { "autolock_locks_on_start_inplace",           run_autolock_locks_on_start_inplace           },
    { "autolock_join_blocked_after_start",         run_autolock_join_blocked_after_start         },
    { "no_autolock_stays_open_on_start",           run_no_autolock_stays_open_on_start           },
    { "autolock_released_on_return_to_lobby",      run_autolock_released_on_return_to_lobby      },
    { "log_roundtrip_basic",                     run_log_roundtrip_basic                     },
    { "log_roundtrip_snapshot_keeps_chain_synced",
                                                 run_log_roundtrip_snapshot_keeps_chain_synced },
    { "log_roundtrip_lobby_snapshot_is_empty_world",
                                                 run_log_roundtrip_lobby_snapshot_is_empty_world },
    { "log_roundtrip_lobby_mode_drops_world_events",
                                                 run_log_roundtrip_lobby_mode_drops_world_events },
    { "log_roundtrip_ping",                      run_log_roundtrip_ping                      },
    { "log_roundtrip_snapshot_tank_stocks",      run_log_roundtrip_snapshot_tank_stocks      },
    { "log_roundtrip_tank_stock_record",         run_log_roundtrip_tank_stock_record         },
    { "replay_roundtrip_world",                  run_replay_roundtrip_world                  },
    { "replay_roundtrip_base_migrate",           run_replay_roundtrip_base_migrate           },
    { "replay_roundtrip_pill_health",            run_replay_roundtrip_pill_health            },
    { "lv_tank_stocks_from_snapshot",            run_lv_tank_stocks_from_snapshot            },
    { "lv_tank_stocks_snapshot_without_tail",    run_lv_tank_stocks_snapshot_without_tail    },
    { "lv_tank_stocks_from_record",              run_lv_tank_stocks_from_record              },
    { "lv_hostile_item_counts",                  run_lv_hostile_item_counts                  },
    { "lv_hostile_entity_remove_index",          run_lv_hostile_entity_remove_index          },
    { "lv_hostile_server_text_slot",             run_lv_hostile_server_text_slot             },
    { "lv_hostile_modifiers_length",             run_lv_hostile_modifiers_length             },
    { "wbv_reader_v1",                           run_wbv_reader_v1                           },
    { "wbv_reader_v2",                           run_wbv_reader_v2                           },
    { "attribution_reader_roundtrip",            run_attribution_reader_roundtrip            },
    { "attribution_reader_rejects_bad",          run_attribution_reader_rejects_bad          },
    { "attribution_reader_clamps_slotcount",     run_attribution_reader_clamps_slotcount     },
    { "attribution_reader_old_wbv",              run_attribution_reader_old_wbv              },
    { "lv_walk_base_anchor_lobby_log",           run_lv_walk_base_anchor_lobby_log           },
    { "lv_walk_base_anchor_opening_snapshot",    run_lv_walk_base_anchor_opening_snapshot    },
    { "lv_walk_base_anchor_ordinal",             run_lv_walk_base_anchor_ordinal             },
    { "lv_hide_lobby_window_mapping",            run_lv_hide_lobby_window_mapping            },
    { "lv_hide_lobby_no_lobby_fallback",         run_lv_hide_lobby_no_lobby_fallback         },
    { "lv_hide_lobby_no_marker_anchor",          run_lv_hide_lobby_no_marker_anchor          },
    { "lv_hide_lobby_periodic_snapshot",         run_lv_hide_lobby_periodic_snapshot         },
    { "lv_logged_name_from_join_event",          run_lv_logged_name_from_join_event          },
    { "lv_game_settings_from_walk",              run_lv_game_settings_from_walk              },
    { "lv_game_settings_absent",                 run_lv_game_settings_absent                 },
    { "wbv_v2_capture",                          run_wbv_v2_capture                          },
    { "wbv_fixture_summaries",                   run_wbv_fixture_summaries                   },
    { "wbv_summary_capture",                     run_wbv_summary_capture                     },
    { "spectator_seed_capture",                  run_spectator_seed_capture                  },
    { "blocks_stream",                           run_blocks_stream                           },
    { "stream_load",                             run_stream_load                             },
    { "stream_pump",                             run_stream_pump                             },
    { "spec_seed_load",                          run_spec_seed_load                          },
    { "spec_seed_load_real",                     run_spec_seed_load_real                     },
    { "spec_record_pump",                        run_spec_record_pump                        },
    { "spectator_seed_integration",              run_spectator_seed_integration              },
    { "spec_seed_decode_info",                   run_spec_seed_decode_info                   },
    { "log_path_empty_uses_autobase",            run_log_path_empty_uses_autobase            },
    { "log_path_explicit_file_verbatim",         run_log_path_explicit_file_verbatim         },
    { "log_path_explicit_file_keeps_single_wbv", run_log_path_explicit_file_keeps_single_wbv },
    { "log_path_directory_autonames_inside",     run_log_path_directory_autonames_inside     },
    { "log_path_directory_trailing_slash_no_double",
                                                 run_log_path_directory_trailing_slash_no_double },
    { "log_path_directory_arg_appends_wbv",      run_log_path_directory_arg_appends_wbv      },
    { "alliance_reset_codec_roundtrip",          run_alliance_reset_codec_roundtrip          },
    { "alliance_reset_decoder_rejects_short",    run_alliance_reset_decoder_rejects_short    },
    { "alliance_reset_reapply_publishes_one_event",
                                                 run_alliance_reset_reapply_publishes_one_event },
    { "alliance_reset_apply_rebuilds_alliances", run_alliance_reset_apply_rebuilds_alliances },
    { "alliance_reset_bots_synced_after_inplace_start",
                                                 run_alliance_reset_bots_synced_after_inplace_start },
    { "alliance_reset_bots_synced_after_countdown_start",
                                                 run_alliance_reset_bots_synced_after_countdown_start },
    { "treegrow_never_plants_on_deep_sea",       run_treegrow_never_plants_on_deep_sea       },
    { "treegrow_reset_clears_stale_target",      run_treegrow_reset_clears_stale_target      },
    { "pill_repair_tops_up_from_arrival_armour", run_pill_repair_tops_up_from_arrival_armour },
    { "pill_repair_short_load_spends_what_it_has", run_pill_repair_short_load_spends_what_it_has },
    { "pill_repair_full_load_covers_a_dead_pill", run_pill_repair_full_load_covers_a_dead_pill },
    { "entity_removed_pill_is_gone_from_gameplay", run_entity_removed_pill_is_gone_from_gameplay },
    { "entity_removed_base_is_gone_from_gameplay", run_entity_removed_base_is_gone_from_gameplay },
    { "entity_removed_start_is_never_chosen",    run_entity_removed_start_is_never_chosen    },
    { "entity_tournament_removed_start_is_never_chosen", run_entity_tournament_removed_start_is_never_chosen },
    { "entity_tournament_neutral_share_counts_live_bases", run_entity_tournament_neutral_share_counts_live_bases },
    { "entity_add_reuses_lowest_removed_slot",   run_entity_add_reuses_lowest_removed_slot   },
    { "entity_add_refused_when_full",            run_entity_add_refused_when_full            },
    { "entity_remove_refuses_already_removed",   run_entity_remove_refuses_already_removed   },
    { "entity_remove_keeps_indices_above",       run_entity_remove_keeps_indices_above       },
    { "entity_blob_load_marks_every_item_live", run_entity_blob_load_marks_every_item_live },
    { "entity_event_codec_roundtrip",            run_entity_event_codec_roundtrip            },
    { "entity_event_client_adds_at_fresh_index", run_entity_event_client_adds_at_fresh_index },
    { "entity_event_client_add_reuses_removed_slot", run_entity_event_client_add_reuses_removed_slot },
    { "entity_event_client_remove_keeps_the_slot", run_entity_event_client_remove_keeps_the_slot },
    { "entity_event_client_add_lands_on_the_server_index", run_entity_event_client_add_lands_on_the_server_index },
    { "entity_event_removed_index_sends_no_delta", run_entity_event_removed_index_sends_no_delta },
    { "entity_event_wire_corpus_fixture",        run_entity_event_wire_corpus_fixture        },
    { "entity_event_client_refuses_out_of_range_index",
      run_entity_event_client_refuses_out_of_range_index                                     },
    { "entity_sync_codec_roundtrip",             run_entity_sync_codec_roundtrip             },
    { "entity_sync_client_clears_the_holes",     run_entity_sync_client_clears_the_holes     },
    { "entity_sync_client_restores_the_live",    run_entity_sync_client_restores_the_live    },
    { "entity_sync_mask_above_the_count_ignored", run_entity_sync_mask_above_the_count_ignored },
    { "entity_sync_loopback_join",               run_entity_sync_loopback_join               },
    { "entity_sync_wire_corpus_fixture",         run_entity_sync_wire_corpus_fixture         },
    { "entity_record_round_trip_per_kind",       run_entity_record_round_trip_per_kind       },
    { "entity_record_viewer_across_a_snapshot",  run_entity_record_viewer_across_a_snapshot  },
    { "entity_record_removed_and_restored_pill_replays",
                                                 run_entity_record_removed_and_restored_pill_replays },
    { "entity_record_brain_rect_skips_a_removed_pill",
                                                 run_entity_record_brain_rect_skips_a_removed_pill },
    { "entity_record_lobby_add_republishes_counts",
                                                 run_entity_record_lobby_add_republishes_counts },
    { "entity_record_lobby_removal_replays",     run_entity_record_lobby_removal_replays     },
    { "entity_record_seek_lands_on_the_right_liveness",
                                                 run_entity_record_seek_lands_on_the_right_liveness },
    { "starts_pick_cluster_nearest_teammate",    run_starts_pick_cluster_nearest_teammate    },
    { "starts_pick_farthest_when_solo",          run_starts_pick_farthest_when_solo          },
    { "starts_pick_none_when_all_taken",         run_starts_pick_none_when_all_taken         },
    { "starts_batch_reserved_lands_exact",       run_starts_batch_reserved_lands_exact       },
    { "starts_batch_unreserved_avoids_reserved", run_starts_batch_unreserved_avoids_reserved },
    { "starts_batch_stale_reservation_falls_through",
                                                 run_starts_batch_stale_reservation_falls_through },
    { "starts_batch_duplicate_honors_first",     run_starts_batch_duplicate_honors_first     },
    { "starts_batch_null_reservations_place_normally",
                                                 run_starts_batch_null_reservations_place_normally },
    { "starts_batch_solo_random_seed",           run_starts_batch_solo_random_seed           },
    { "starts_batch_teams_cluster_and_separate", run_starts_batch_teams_cluster_and_separate },
    { "starts_batch_team_anchor_jitter_varies",  run_starts_batch_team_anchor_jitter_varies  },
    { "starts_open_ideal_friendly_pill_eligible",
                                                 run_starts_open_ideal_friendly_pill_eligible },
    { "starts_open_ideal_removed_pill_ignored",   run_starts_open_ideal_removed_pill_ignored  },
    { "starts_open_removed_start_never_chosen",   run_starts_open_removed_start_never_chosen  },
    { "start_side_mask_sectors",                 run_start_side_mask_sectors                 },
    { "start_side_mask_degenerate_bbox",         run_start_side_mask_degenerate_bbox         },
    { "start_side_eligible_closed_mask",         run_start_side_eligible_closed_mask         },
    { "lobby_side_axis_two_team_pair",           run_lobby_side_axis_two_team_pair           },
    { "lobby_side_axis_pair_classification",     run_lobby_side_axis_pair_classification     },
    { "lobby_side_axis_click_targets",           run_lobby_side_axis_click_targets           },
    { "lobby_start_shared_prefix_len",           run_lobby_start_shared_prefix_len           },
    { "lobby_start_shared_prefix_label",         run_lobby_start_shared_prefix_label         },
    { "lobby_start_shared_name_label",           run_lobby_start_shared_name_label           },
    { "lobby_start_shared_owner_fold",           run_lobby_start_shared_owner_fold           },
    { "starts_scatter_avoids_existing_tanks",    run_starts_scatter_avoids_existing_tanks    },
    { "starts_scatter_falls_back_when_crowded",  run_starts_scatter_falls_back_when_crowded  },
    { "starts_side_team_stays_on_its_side",      run_starts_side_team_stays_on_its_side      },
    { "starts_side_overflow_rides_own_side",     run_starts_side_overflow_rides_own_side     },
    { "starts_side_never_crosses_when_opposite_free",
                                                 run_starts_side_never_crosses_when_opposite_free },
    { "starts_side_any_matches_legacy",          run_starts_side_any_matches_legacy          },
    { "starts_side_reservation_beats_side",      run_starts_side_reservation_beats_side      },
    { "starts_side_empty_side_falls_back",       run_starts_side_empty_side_falls_back       },
    { "starts_side_quota_capped_by_eligible",    run_starts_side_quota_capped_by_eligible    },
    { "starts_side_any_team_kept_off_chosen_side",
                                                 run_starts_side_any_team_kept_off_chosen_side },
    { "lobby_team_side_clamps_and_rejects_non_host",
                                                 run_lobby_team_side_clamps_and_rejects_non_host },
    { "lobby_side_change_repicks_everyone",      run_lobby_side_change_repicks_everyone      },
    { "lobby_unassign_and_team_side_claims",     run_lobby_unassign_and_team_side_claims     },
    { "lobby_map_change_releases_off_side",      run_lobby_map_change_releases_off_side      },
    { "lobby_non_host_off_side_claim_rejected",  run_lobby_non_host_off_side_claim_rejected  },
    { "lobby_any_team_claim_kept_off_chosen_side", run_lobby_any_team_claim_kept_off_chosen_side },
    { "starts_side_end_to_end_four_v_twelve",    run_starts_side_end_to_end_four_v_twelve    },
    { "input_redundancy",                        run_input_redundancy                        },
    { "edge_send_predicate",                     run_edge_send_predicate                     },
    { "bases_closest_for_player",                run_bases_closest_for_player                },
    { "base_stock_visibility",                   run_base_stock_visibility                   },
    { "base_half_tick_per_sim_sequence",         run_base_half_tick_per_sim_sequence         },
    { "base_half_tick_other_sim_does_not_disturb", run_base_half_tick_other_sim_does_not_disturb },
    { "base_armour_fog_of_war",                  run_base_armour_fog_of_war                  },
    { "base_armour_reveal_in_range",             run_base_armour_reveal_in_range             },
    { "base_death_prediction_replay_tick",       run_base_death_prediction_replay_tick       },
    { "base_death_prediction_authority",         run_base_death_prediction_authority         },
    { "tank_damage_exact_armour_survives",       run_tank_damage_exact_armour_survives       },
    { "tank_damage_overkill_destroys",           run_tank_damage_overkill_destroys           },
    { "tank_damage_partial_survives",            run_tank_damage_partial_survives            },
    { "tank_destroyed_snapshot_round_trip",      run_tank_destroyed_snapshot_round_trip      },
    { "tank_status_wire_bits",                   run_tank_status_wire_bits                   },
    { "tank_status_wire_start_find_round_trip",  run_tank_status_wire_start_find_round_trip  },
    { "two_clients_full_sync_independent",       run_two_clients_full_sync_independent       },
    { "voice_flags_snapshot_masking",            run_voice_flags_snapshot_masking            },
    { "voice_talking_codec",                     run_voice_talking_codec                     },
    { "sim_rules_codec_roundtrip",               run_sim_rules_codec_roundtrip               },
    { "sim_rules_codec_golden",                  run_sim_rules_codec_golden                  },
    { "voice_talking_stops_in_countdown",        run_voice_talking_stops_in_countdown        },
    { "voice_talking_clears_on_leave",           run_voice_talking_clears_on_leave           },
    { "fx_viewport_cull",                        run_fx_viewport_cull                        },
    { "viewport_floor",                          run_viewport_floor                          },
    { "sound_event_codec",                       run_sound_event_codec                       },
    { "sound_delivery_builder",                  run_sound_delivery_builder                  },
    { "sound_payload_shape",                     run_sound_payload_shape                     },
    { "view_rects_default_baseline",             run_view_rects_default_baseline             },
    { "view_rects_always_base_ally",             run_view_rects_always_base_ally             },
    { "view_rects_off",                          run_view_rects_off                          },
    { "view_rects_decay",                        run_view_rects_decay                        },
    { "view_rects_dead_player",                  run_view_rects_dead_player                  },
    { "view_pill_pos_current",                   run_view_pill_pos_current                   },
    { "view_pill_pos_reveal",                    run_view_pill_pos_reveal                    },
    { "view_pill_update_event_fogged",           run_view_pill_update_event_fogged           },
    { "view_pill_pos_bot_advantage",             run_view_pill_pos_bot_advantage             },
    { "tree_hide_enemy",                         run_tree_hide_enemy                         },
    { "tree_hide_ally_option",                   run_tree_hide_ally_option                   },
    { "lgm_visibility_tank_in_trees",            run_lgm_visibility_tank_in_trees            },
    { "lgm_visibility_tank_visible",             run_lgm_visibility_tank_visible             },
    { "view_state_key_grants_rect",              run_view_state_key_grants_rect              },
    { "view_state_bad_claims_degrade",           run_view_state_bad_claims_degrade           },
    { "view_state_invalidation",                 run_view_state_invalidation                 },
    { "view_state_lifecycle",                    run_view_state_lifecycle                    },
    { "view_cycle_pick_order",                   run_view_cycle_pick_order                   },
    { "view_cycle_pick_policy",                  run_view_cycle_pick_policy                  },
    { "view_cycle_pick_direction",               run_view_cycle_pick_direction               },
    { "view_target_codec",                       run_view_target_codec                       },
    { "view_target_apply",                       run_view_target_apply                       },
    { "view_cycle_bases",                        run_view_cycle_bases                        },
    { "view_cycle_base_direction",               run_view_cycle_base_direction               },
    { "view_cycle_allies",                       run_view_cycle_allies                       },
    { "view_cycle_ally_direction",               run_view_cycle_ally_direction               },
    { "view_cycle_exits",                        run_view_cycle_exits                        },
    { "view_cycle_decay_skip",                   run_view_cycle_decay_skip                   },
    { "view_cycle_eligible_mask",                run_view_cycle_eligible_mask                },
    { "view_cycle_ally_stub",                    run_view_cycle_ally_stub                    },
    { "view_cycle_stale_pill",                   run_view_cycle_stale_pill                   },
    { "pill_pos_current_lookups",                run_pill_pos_current_lookups                },
    { "pill_pos_current_num_split",              run_pill_pos_current_num_split              },
    { "pill_pos_current_duplicate_square",       run_pill_pos_current_duplicate_square       },
    { "pill_pos_current_snapshot_apply",         run_pill_pos_current_snapshot_apply         },
    { "pill_pos_current_server_unchanged",       run_pill_pos_current_server_unchanged       },
    { "pill_pos_current_moved_state",            run_pill_pos_current_moved_state            },
    { "pill_pos_current_carry_cycle",            run_pill_pos_current_carry_cycle            },
    { "viewport_calc_square_pure",               run_viewport_calc_square_pure               },
    { "viewport_calc_pill_square_moved",         run_viewport_calc_pill_square_moved         },
    { "overview_regions",                        run_overview_regions                        },
    { "overview_reveal",                         run_overview_reveal                         },
    { "overview_freeze_no_leak",                 run_overview_freeze_no_leak                 },
    { "overview_pill_capture",                   run_overview_pill_capture                   },
    { "overview_reset",                          run_overview_reset                          },
    { "overview_decay_mirror",                   run_overview_decay_mirror                   },
    { "overview_decay_view_exit",                run_overview_decay_view_exit                },
    { "overview_policy_baseline",                run_overview_policy_baseline                },
    { "overview_policy_categories",              run_overview_policy_categories              },
    { "overview_policy_decay",                   run_overview_policy_decay                   },
    { "overview_loopback",                       run_overview_loopback                       },
    { "overview_camera",                         run_overview_camera                         },
    { "overview_scroll",                         run_overview_scroll                         },
    { "overview_fog",                            run_overview_fog                            },
    { "overview_hud_layout",                     run_overview_hud_layout                     },
    { "overview_dead_tank",                      run_overview_dead_tank                      },
    { "overview_entities",                       run_overview_entities                       },
    { "overview_removed_item_has_no_region",     run_overview_removed_item_has_no_region     },
    { "overview_gunsight",                       run_overview_gunsight                       },
    { "tank_pos_dead",                           run_tank_pos_dead                           },
    { "overview_snapshot_mirror",                run_overview_snapshot_mirror                },
    { "overview_snapshot_isolation",             run_overview_snapshot_isolation             },
    { "overview_snapshot_filter",                run_overview_snapshot_filter                },
    { "overview_snapshot_generation",            run_overview_snapshot_generation            },
    { "overview_snapshot_removed_item_has_no_label", run_overview_snapshot_removed_item_has_no_label },
    { "mapview_sprite_classic",                  run_mapview_sprite_classic                  },
    { "mapview_sprite_ladder",                   run_mapview_sprite_ladder                   },
    { "mapview_sprite_shell_tip",                run_mapview_sprite_shell_tip                },
    { "mapview_sprite_lgm_snap",                 run_mapview_sprite_lgm_snap                 },
    { "mapview_overlay_gunsight",                run_mapview_overlay_gunsight                },
    { "mapview_overlay_tank_label",              run_mapview_overlay_tank_label              },
    { "mapview_overlay_cursor",                  run_mapview_overlay_cursor                  },
    { "mapview_overlay_item_labels",             run_mapview_overlay_item_labels             },
    { "stall_advances_processed_tick",           run_stall_advances_processed_tick           },
    { "stall_mine_late_lays_once",               run_stall_mine_late_lays_once               },
    { "stall_mine_duplicate_not_relaid",         run_stall_mine_duplicate_not_relaid         },
    { "stall_fire_not_harvested",                run_stall_fire_not_harvested                },
    { "stall_never_fires",                       run_stall_never_fires                       },
    { "stall_brief_trough_no_advance",           run_stall_brief_trough_no_advance           },
    { "stall_long_dry_advances",                 run_stall_long_dry_advances                 },
    { "input_catchup",                           run_input_catchup                           },
    { "catchup_ignores_redundant_duplicates",    run_catchup_ignores_redundant_duplicates    },
    { "build_harvest_stale",                     run_build_harvest_stale                     },
    { "build_harvest_valid",                     run_build_harvest_valid                     },
    { "build_harvest_busy_queues",               run_build_harvest_busy_queues               },
    { "lgm_request_valid",                       run_lgm_request_valid                       },
    { "lgm_request_quiet",                       run_lgm_request_quiet                       },
    { "jitter_buffer_grow",                      run_jitter_buffer_grow                      },
    { "shell_projection",                        run_shell_projection                        },
    { "screen_bullets_build",                    run_screen_bullets_build                    },
    { "ping_smoother",                           run_ping_smoother                           },
    { "client_timing",                           run_client_timing                           },
    { "interp_render",                           run_interp_render                           },
    { "interp_respawn_no_death_flash",           run_interp_respawn_no_death_flash           },
    { "sim_rules_classic_defaults",              run_sim_rules_classic_defaults              },
    { "sim_rules_validate_ranges",               run_sim_rules_validate_ranges               },
    { "sim_rules_copies_follow",                 run_sim_rules_copies_follow                 },
    { "sim_rules_terrain_caps_follow",           run_sim_rules_terrain_caps_follow           },
    { "sim_rules_river_cap_moves_drowning",      run_sim_rules_river_cap_moves_drowning      },
    { "sim_rules_base_regen_seed_follows",       run_sim_rules_base_regen_seed_follows       },
    { "sim_rules_terrain_life_follows",          run_sim_rules_terrain_life_follows          },
    { "sim_rules_base_empties_without_wrapping", run_sim_rules_base_empties_without_wrapping },
    { "sim_rules_pill_empties_without_wrapping", run_sim_rules_pill_empties_without_wrapping },
    { "sim_rules_pairs",                         run_sim_rules_pairs                         },
    { "sim_rules_capture_threshold_moves",       run_sim_rules_capture_threshold_moves       },
    { "sim_rules_builder_cost_follows",          run_sim_rules_builder_cost_follows          },
    { "sim_rules_are_classic",                   run_sim_rules_are_classic                   },
    { "sim_rules_obs_refuses_non_classic",       run_sim_rules_obs_refuses_non_classic       },
    { "sim_rules_shell_flight_follows",          run_sim_rules_shell_flight_follows          },
    { "sim_rules_brain_shot_follows",            run_sim_rules_brain_shot_follows            },
    { "sim_rules_worldsim_pill_follows",         run_sim_rules_worldsim_pill_follows         },
    { "sim_rules_boat_speed_follows",            run_sim_rules_boat_speed_follows            },
    { "snapshot_compaction",                     run_snapshot_compaction                     },
    { "error_smoothing",                         run_error_smoothing                         },
    { "loopback_join",                           run_loopback_join                           },
    { "loopback_join_loss",                      run_loopback_join_loss                      },
    { "loopback_lobby_running_loss",             run_loopback_lobby_running_loss             },
    { "loopback_quiet_lobby_control_loss",       run_loopback_quiet_lobby_control_loss       },
    { "loopback_command_liveness",               run_loopback_command_liveness               },
    { "loopback_channel",                        run_loopback_channel                        },
    { "lock_channel",                            run_lock_channel                            },
    { "loopback_map_preview",                    run_loopback_map_preview                    },
    { "loopback_map_upload",                     run_loopback_map_upload                     },
    { "loopback_download_join",                  run_loopback_download_join                  },
    { "loopback_download_midgame",               run_loopback_download_midgame               },
    { "loopback_resync",                         run_loopback_resync                         },
    { "loopback_map_change_clean",               run_loopback_map_change_clean               },
    { "loopback_map_change_loss",                run_loopback_map_change_loss                },
    { "loopback_join_accept_loss",               run_loopback_join_accept_loss               },
    { "loopback_join_accept_loss_midgame",       run_loopback_join_accept_loss_midgame       },
    { "gate1_viewtick_loopback",                 run_gate1_viewtick_loopback                 },
    { "gate1_host_noop",                         run_gate1_host_noop                         },
    { "interp_jitter_e2e",                       run_interp_jitter_e2e                       },
    { "join_version_gate",                       run_join_version_gate                       },
    { "join_rate_limit",                         run_join_rate_limit                         },
    { "cookie_handshake",                        run_cookie_handshake                        },
    { "map_amp_gate",                            run_map_amp_gate                            },
    { "map_reask_throttle",                            run_map_reask_throttle                            },
    { "map_resync_cut_and_deliver_once",         run_map_resync_cut_and_deliver_once         },
    { "map_resync_duplicate_request_no_recut",   run_map_resync_duplicate_request_no_recut   },
    { "map_resync_send_gate_holds",              run_map_resync_send_gate_holds              },
    { "map_resync_stale_gen_rejected",           run_map_resync_stale_gen_rejected           },
    { "map_compress_roundtrip_stock",            run_map_compress_roundtrip_stock            },
    { "map_compress_capacity_refuses",           run_map_compress_capacity_refuses           },
    { "map_compress_incompressible",           run_map_compress_incompressible           },
    { "map_compress_roundtrip_mutated",          run_map_compress_roundtrip_mutated          },
    { "map_compress_rejects_null_handles",       run_map_compress_rejects_null_handles       },
    { "map_checksum_ignores_mines",              run_map_checksum_ignores_mines              },
    { "map_resync_base_crater_converges",        run_map_resync_base_crater_converges        },
    { "map_shadow_tracks_real",                  run_map_shadow_tracks_real                  },
    { "map_shadow_crc_matches",                  run_map_shadow_crc_matches                  },
    { "map_shadow_blob_identical",               run_map_shadow_blob_identical               },
    { "map_shadow_seed_lifecycle",               run_map_shadow_seed_lifecycle               },
    { "map_shadow_cull_withholds",               run_map_shadow_cull_withholds               },
    { "map_shadow_sweep_converges",              run_map_shadow_sweep_converges              },
    { "map_shadow_sweep_bounds",                 run_map_shadow_sweep_bounds                 },
    { "map_shadow_round_start_capture",          run_map_shadow_round_start_capture          },
    { "map_shadow_join_seeds_round_start",       run_map_shadow_join_seeds_round_start       },
    { "map_shadow_round_start_fallback",         run_map_shadow_round_start_fallback         },
    { "pill_shadow_tracks_real",                 run_pill_shadow_tracks_real                 },
    { "pill_shadow_crc_matches",                 run_pill_shadow_crc_matches                 },
    { "pill_shadow_blob_identical",              run_pill_shadow_blob_identical              },
    { "pill_shadow_fullsync_move_matches",       run_pill_shadow_fullsync_move_matches       },
    { "pill_shadow_withheld_crc_matches",        run_pill_shadow_withheld_crc_matches        },
    { "loopback_map_cull",                       run_loopback_map_cull                       },
    { "loopback_map_cull_resync",                run_loopback_map_cull_resync                },
    { "sound_delivery_wire_cull",                run_sound_delivery_wire_cull                },
    { "sound_tier_playback",                     run_sound_tier_playback                     },
    { "view_ally_loopback",                      run_view_ally_loopback                      },
    { "resync_finalize_corrupt_keeps_gen",       run_resync_finalize_corrupt_keeps_gen       },
    { "resync_finalize_valid_advances_gen",      run_resync_finalize_valid_advances_gen      },
    { "install_compressed_map_rejects_garbage",  run_install_compressed_map_rejects_garbage  },
    { "resync_debounce_threshold",               run_resync_debounce_threshold               },
    { "conn_migration_rehome",                   run_conn_migration_rehome                   },
    { "conn_migration_e2e",                      run_conn_migration_e2e                      },
    { "viewtick_rewind",                         run_viewtick_rewind                         },
    { "viewtick_displayed_tick",                 run_viewtick_displayed_tick                 },
    { "wire_corpus",                             run_wire_corpus                             },
    { "wire_corpus_capture",                     run_wire_corpus_capture                     },
    { "packet_type_names",                       run_packet_type_names                       },
    { "ping_binding_encode_decode",              run_ping_binding_encode_decode              },
    { "ping_binding_match",                      run_ping_binding_match                      },
    { "ping_binding_direct",                     run_ping_binding_direct                     },
    { "ping_binding_format",                     run_ping_binding_format                     },
    { "ping_pie_slices",                         run_ping_pie_slices                         },
    { "ping_edge_sides",                         run_ping_edge_sides                         },
    { "ping_edge_corner",                        run_ping_edge_corner                        },
    { "ping_rect_inset",                         run_ping_rect_inset                         },
    { "ping_event_wire",                         run_ping_event_wire                         },
    { "ping_dispatch_accepts_and_builds_event",  run_ping_dispatch_accepts_and_builds_event  },
    { "ping_dispatch_rejects_lobby",             run_ping_dispatch_rejects_lobby             },
    { "ping_dispatch_rejects_empty_slot_and_out_of_range",
                                                 run_ping_dispatch_rejects_empty_slot_and_out_of_range },
    { "ping_dispatch_map_range_bound",           run_ping_dispatch_map_range_bound           },
    { "ping_dispatch_rejects_bad_kind",          run_ping_dispatch_rejects_bad_kind          },
    { "ping_dispatch_rate_limit",                run_ping_dispatch_rate_limit                },
    { "ping_dispatch_new_round_clears_rate_limit",
                                                 run_ping_dispatch_new_round_clears_rate_limit },
    { "ping_reaches_team_only",                  run_ping_reaches_team_only                  },
    { "ping_network",                            run_ping_network                            },
    { "lang_name_table",                         run_lang_name_table                         },
    { "screencalc_river_road_counts_as_water",   run_screencalc_river_road_counts_as_water   },
    { "screencalc_river_arms_of_road_centred_cross",
                                                 run_screencalc_river_arms_of_road_centred_cross },
    { "screencalc_river_copies_agree",           run_screencalc_river_copies_agree           },
    { "mdns_discovery",                          run_mdns_discovery                          },
    { "client_type_matches_platform",            run_client_type_matches_platform            },
    { "client_type_name_round_trips",            run_client_type_name_round_trips            },
    { "map_load_clamps_base_fields",             run_map_load_clamps_base_fields             },
    { "map_load_clamps_pill_fields",             run_map_load_clamps_pill_fields             },
    { "map_load_clamps_start_dir",               run_map_load_clamps_start_dir               },
    { "client_slot_reassign_carries_tank_and_lgm",
                                                 run_client_slot_reassign_carries_tank_and_lgm },
    { "client_slot_reassign_same_slot_is_stable",
                                                 run_client_slot_reassign_same_slot_is_stable },
    { "client_slot_reassign_back_to_zero",       run_client_slot_reassign_back_to_zero       },
    { "players_oob_index_safe",                  run_players_oob_index_safe                  },
    { "control_oob_player_dropped",              run_control_oob_player_dropped              },
    { "control_overflow_defers_disconnect",      run_control_overflow_defers_disconnect      },
    { "shells_survive_cleared_lgm_slot",         run_shells_survive_cleared_lgm_slot         },
    { "ping_kick_defers_teardown",               run_ping_kick_defers_teardown               },
    { "ping_kick_clears_strikes_on_disconnect",  run_ping_kick_clears_strikes_on_disconnect  },
    { "tkexp_lgm_pairing",                       run_tkexp_lgm_pairing                       },
    { "input_gate_taxonomy",                     run_input_gate_taxonomy                     },
    { "key_claims",                              run_key_claims                              },
    { "addrparse_host_only",                     run_addrparse_host_only                     },
    { "addrparse_host_port",                     run_addrparse_host_port                     },
    { "addrparse_scheme",                        run_addrparse_scheme                        },
    { "addrparse_trailing_path",                 run_addrparse_trailing_path                 },
    { "addrparse_whitespace",                    run_addrparse_whitespace                    },
    { "addrparse_port_bounds",                   run_addrparse_port_bounds                   },
    { "addrparse_bad_port",                      run_addrparse_bad_port                      },
    { "addrparse_empty",                         run_addrparse_empty                         },
    { "voice_core_roundtrip",                    run_voice_core_roundtrip                    },
    { "voice_device_resolve",                    run_voice_device_resolve                    },
    { "voice_peak",                              run_voice_peak                              },
    { "voice_segment_roundtrip",                 run_voice_segment_roundtrip                 },
    { "voice_segment_rejects_malformed",         run_voice_segment_rejects_malformed         },
    { "voice_jitter_ordering_and_plc",           run_voice_jitter_ordering_and_plc           },
    { "voice_jitter_undecodable_run",            run_voice_jitter_undecodable_run            },
    { "voice_jitter_under_loss",                 run_voice_jitter_under_loss                 },
    { "voice_flood_cap_enforced",                run_voice_flood_cap_enforced                },
    { "voice_talker_select_ranks_recent",        run_voice_talker_select_ranks_recent        },
    { "voice_talker_select_bounds",              run_voice_talker_select_bounds              },
    { "skin_source_dir_and_zip",                 run_skin_source_dir_and_zip                 },
    { "skin_active_vs_requested",                run_skin_active_vs_requested                },
    { "skin_workshop_id_roundtrip",              run_skin_workshop_id_roundtrip              },
    { "skin_density_scan",                       run_skin_density_scan                       },
    { "sheet_bleed_edges",                       run_sheet_bleed_edges                       },
    { "sheet_no_key_under_alpha",                run_sheet_no_key_under_alpha                },
    { "bmp_sheet_no_key_under_alpha",            run_bmp_sheet_no_key_under_alpha            },
    { "sprite_atlas_isolated",                   run_sprite_atlas_isolated                   },
    { "sprite_atlas_lookup",                     run_sprite_atlas_lookup                     },
    { "sprite_atlas_packed_sheet_unsafe",        run_sprite_atlas_packed_sheet_unsafe        },
    { "sound_variant_pool_names",                run_sound_variant_pool_names                },
    { "sound_variant_load_compaction",           run_sound_variant_load_compaction           },
    { "pascal_string_lengths",                   run_pascal_string_lengths                   },
    { "pascal_string_viewer_copy_agrees",        run_pascal_string_viewer_copy_agrees        },
    { "pascal_string_roundtrip",                 run_pascal_string_roundtrip                 },
    { "console_lock_unlock",                     run_console_lock_unlock                     },
    { "console_info_and_status",                 run_console_info_and_status                 },
    { "console_savemap_path",                    run_console_savemap_path                    },
    { "console_unknown_command_is_inert",        run_console_unknown_command_is_inert        },
    { "console_say_keeps_case",                  run_console_say_keeps_case                  },
    { "console_kick_and_host",                   run_console_kick_and_host                   },
    { "console_kick_host_without_newline",       run_console_kick_host_without_newline       },
    { "console_read_reports_eof",                run_console_read_reports_eof                },
    { "console_read_timeout_then_eof",           run_console_read_timeout_then_eof           },
    { "tank_mod_speed_caps_on_road",             run_tank_mod_speed_caps_on_road             },
    { "tank_mod_speed_river_still_moves",        run_tank_mod_speed_river_still_moves        },
    { "tank_mod_accel_doubles_ticks_to_cap",     run_tank_mod_accel_doubles_ticks_to_cap     },
    { "tank_mod_accel_doubles_ticks_to_brake",   run_tank_mod_accel_doubles_ticks_to_brake   },
    { "tank_mod_accel_halves_autoslow",          run_tank_mod_accel_halves_autoslow          },
    { "tank_mod_turn_halves_circle_ticks",       run_tank_mod_turn_halves_circle_ticks       },
    { "tank_mod_reload_fires_twice_as_often",    run_tank_mod_reload_fires_twice_as_often    },
    { "tank_mod_dealt_kills_in_half_the_hits",   run_tank_mod_dealt_kills_in_half_the_hits   },
    { "tank_mod_taken_takes_more_hits",          run_tank_mod_taken_takes_more_hits          },
    { "tank_mod_mine_damage_scales_with_layer",  run_tank_mod_mine_damage_scales_with_layer  },
    { "tank_mod_neutral_owner_deals_classic",    run_tank_mod_neutral_owner_deals_classic    },
    { "tank_mod_boat_exit_at_half_speed",        run_tank_mod_boat_exit_at_half_speed        },
    { "tank_mod_pill_leads_half_speed_boat",     run_tank_mod_pill_leads_half_speed_boat     },
    { "tank_mod_predicted_stop_matches_engine",  run_tank_mod_predicted_stop_matches_engine  },
    { "tank_modifiers_op_writes_set",            run_tank_modifiers_op_writes_set            },
    { "tank_modifiers_op_refusals",              run_tank_modifiers_op_refusals              },
    { "tank_modifiers_wire_roundtrip",           run_tank_modifiers_wire_roundtrip           },
    { "tank_modifiers_survive_death",            run_tank_modifiers_survive_death            },
    { "tank_modifiers_cleared_at_create",        run_tank_modifiers_cleared_at_create        },
    { "scenario_op_unknown_type_unsupported",    run_scenario_op_unknown_type_unsupported    },
    { "scenario_op_every_type_unsupported",      run_scenario_op_every_type_unsupported      },
    { "scenario_policy_register_replace_clear",  run_scenario_policy_register_replace_clear  },
    { "scenario_op_refused_in_policy",           run_scenario_op_refused_in_policy           },
    { "scenario_op_refused_in_nested_policy",    run_scenario_op_refused_in_nested_policy    },
    { "scenario_op_refused_during_start",        run_scenario_op_refused_during_start        },
    { "scenario_tick_called_both_branches",      run_scenario_tick_called_both_branches      },
    { "scenario_start_flag_set_during_start",    run_scenario_start_flag_set_during_start    },
    { "scenario_start_guard_blocks_reentry",     run_scenario_start_guard_blocks_reentry     },
    { "scenario_start_flag_cleared_after_start", run_scenario_start_flag_cleared_after_start },
    { "scenario_read_roster_slot",               run_scenario_read_roster_slot               },
    { "scenario_read_pill_info",                 run_scenario_read_pill_info                 },
    { "scenario_read_base_info",                 run_scenario_read_base_info                 },
    { "scenario_read_start_info",                run_scenario_read_start_info                },
    { "scenario_read_tank_info",                 run_scenario_read_tank_info                 },
    { "scenario_read_builder_info",              run_scenario_read_builder_info              },
    { "scenario_read_terrain_buffer",            run_scenario_read_terrain_buffer            },
    { "scenario_read_num_fielded",               run_scenario_read_num_fielded               },
    { "scenario_tank_set_stocks",                run_scenario_tank_set_stocks                },
    { "scenario_tank_kill",                      run_scenario_tank_kill                      },
    { "scenario_tank_teleport",                  run_scenario_tank_teleport                  },
    { "scenario_tank_set_boat",                  run_scenario_tank_set_boat                  },
    { "scenario_tank_give_pill",                 run_scenario_tank_give_pill                 },
    { "scenario_tank_drop_pill",                 run_scenario_tank_drop_pill                 },
    { "scenario_tank_arm_records",               run_scenario_tank_arm_records               },
    { "scenario_lgm_dispatch",                   run_scenario_lgm_dispatch                   },
    { "scenario_lgm_recall",                     run_scenario_lgm_recall                     },
    { "scenario_lgm_kill",                       run_scenario_lgm_kill                       },
    { "scenario_lgm_parachute",                  run_scenario_lgm_parachute                  },
    { "scenario_lgm_set_carried",                run_scenario_lgm_set_carried                },
    { "scenario_lgm_kill_record",                run_scenario_lgm_kill_record                },
    { "scenario_pill_set_owner",                 run_scenario_pill_set_owner                 },
    { "scenario_pill_set_armour",                run_scenario_pill_set_armour                },
    { "scenario_pill_set_speed",                 run_scenario_pill_set_speed                 },
    { "scenario_pill_move",                      run_scenario_pill_move                      },
    { "scenario_base_set_owner",                 run_scenario_base_set_owner                 },
    { "scenario_base_owner_keep_stock",          run_scenario_base_owner_keep_stock          },
    { "scenario_base_set_stock",                 run_scenario_base_set_stock                 },
    { "scenario_pill_base_arm_records",          run_scenario_pill_base_arm_records          },
    { "scenario_entity_add_pill", run_scenario_entity_add_pill },
    { "scenario_entity_remove_pill", run_scenario_entity_remove_pill },
    { "scenario_removed_item_is_no_item", run_scenario_removed_item_is_no_item },
    { "scenario_entity_add_base", run_scenario_entity_add_base },
    { "scenario_entity_remove_base", run_scenario_entity_remove_base },
    { "scenario_entity_add_start", run_scenario_entity_add_start },
    { "scenario_entity_remove_start", run_scenario_entity_remove_start },
    { "scenario_entity_publish", run_scenario_entity_publish },
    { "scenario_entity_add_out_null", run_scenario_entity_add_out_null },
    { "loopback_entity_change",                  run_loopback_entity_change                  },
    { "loopback_sim_rules_change",               run_loopback_sim_rules_change               },
    { "loopback_sim_rules_join",                 run_loopback_sim_rules_join                 },
    { "loopback_sim_rules_reclamp",              run_loopback_sim_rules_reclamp              },
    { "loopback_sim_rules_agree",                run_loopback_sim_rules_agree                },
    { "scenario_map_set_tile",                   run_scenario_map_set_tile                   },
    { "scenario_map_fill_rect",                  run_scenario_map_fill_rect                  },
    { "scenario_map_fill_paced",                 run_scenario_map_fill_paced                 },
    { "scenario_map_fill_no_budget_refused",     run_scenario_map_fill_no_budget_refused     },
    { "scenario_map_fill_dropped_at_round_start",
      run_scenario_map_fill_dropped_at_round_start                                           },
    { "scenario_map_fill_dropped_at_map_swap",
      run_scenario_map_fill_dropped_at_map_swap                                              },
    { "scenario_map_fill_respects_event_buffer",
      run_scenario_map_fill_respects_event_buffer                                            },
    { "scenario_map_place_mine",                 run_scenario_map_place_mine                 },
    { "scenario_map_remove_mine",                run_scenario_map_remove_mine                },
    { "scenario_map_arm_records",                run_scenario_map_arm_records                },
    { "scenario_roster_spawn_refusals",          run_scenario_roster_spawn_refusals          },
    { "scenario_roster_spawn_lands",             run_scenario_roster_spawn_lands             },
    { "scenario_roster_spawn_paced",             run_scenario_roster_spawn_paced             },
    { "scenario_roster_team_during_add",         run_scenario_roster_team_during_add         },
    { "scenario_roster_remove_bot",              run_scenario_roster_remove_bot              },
    { "scenario_roster_set_team",                run_scenario_roster_set_team                },
    { "scenario_lobby_add_bot",                  run_scenario_lobby_add_bot                  },
    { "scenario_lobby_remove_bot",               run_scenario_lobby_remove_bot               },
    { "scenario_lobby_set_team",                 run_scenario_lobby_set_team                 },
    { "scenario_roster_bots_seat_past_the_human_cap",
      run_scenario_roster_bots_seat_past_the_human_cap                                       },
    { "scenario_roster_spawn_named_start",       run_scenario_roster_spawn_named_start       },
    { "scenario_comms_msg_all",                  run_scenario_comms_msg_all                  },
    { "scenario_comms_msg_team",                 run_scenario_comms_msg_team                 },
    { "scenario_comms_msg_player",               run_scenario_comms_msg_player               },
    { "scenario_comms_sound",                    run_scenario_comms_sound                    },
    { "scenario_comms_log",                      run_scenario_comms_log                      },
    { "scenario_comms_arm_records",              run_scenario_comms_arm_records              },
    { "scenario_comms_decoder_dest_player",      run_scenario_comms_decoder_dest_player      },
    { "scenario_comms_apply_non_zero_slot",      run_scenario_comms_apply_non_zero_slot      },
    { "scenario_flow_end_round",                 run_scenario_flow_end_round                 },
    { "scenario_flow_end_round_resolve",         run_scenario_flow_end_round_resolve         },
    { "scenario_flow_end_round_refusals",        run_scenario_flow_end_round_refusals        },
    { "scenario_flow_set_game_time",             run_scenario_flow_set_game_time             },
    { "scenario_flow_set_game_time_refusals",    run_scenario_flow_set_game_time_refusals    },
    { "scenario_flow_arm_records",               run_scenario_flow_arm_records               },
    { "scenario_rule_index_matches_table",       run_scenario_rule_index_matches_table       },
    { "scenario_rule_set",                       run_scenario_rule_set                       },
    { "scenario_rule_set_float",                 run_scenario_rule_set_float                 },
    { "scenario_rule_refusals",                  run_scenario_rule_refusals                  },
    { "scenario_rule_arm_records",               run_scenario_rule_arm_records               },
    { "scenario_rule_clamps_world",              run_scenario_rule_clamps_world              },
    { "scenario_rule_clamp_records",             run_scenario_rule_clamp_records             },
    { "scenario_policy_choose_start",            run_scenario_policy_choose_start            },
    { "scenario_policy_choose_start_out_of_range",
      run_scenario_policy_choose_start_out_of_range                                          },
    { "scenario_policy_allow_base_win",          run_scenario_policy_allow_base_win          },
    { "scenario_policy_allow_extra_teams",       run_scenario_policy_allow_extra_teams       },
    { "scenario_policy_team_set_extra_teams",    run_scenario_policy_team_set_extra_teams    },
    { "scenario_policy_max_players",             run_scenario_policy_max_players             },
    { "scenario_policy_spawn_loadout",           run_scenario_policy_spawn_loadout           },
    { "scenario_policy_can_respawn",             run_scenario_policy_can_respawn             },
    { "scenario_policy_null_is_classic",         run_scenario_policy_null_is_classic         },
    { "scenario_policy_hostile_answers",         run_scenario_policy_hostile_answers         },
    { "scenario_policy_named_start_outranks_choose_start",
      run_scenario_policy_named_start_outranks_choose_start                                  },
    { "scenario_policy_damage_scale",            run_scenario_policy_damage_scale            },
    { "scenario_policy_invulnerable_tank",       run_scenario_policy_invulnerable_tank       },
    { "scenario_policy_protected_builder",       run_scenario_policy_protected_builder       },
    { "scenario_policy_protected_pill",          run_scenario_policy_protected_pill          },
    { "scenario_policy_can_build",               run_scenario_policy_can_build               },
    { "scenario_policy_can_capture",             run_scenario_policy_can_capture             },
    { "scenario_policy_kill_ops_ignore_can_die",
      run_scenario_policy_kill_ops_ignore_can_die                                            },
    { "scenario_policy_combat_null_is_classic",
      run_scenario_policy_combat_null_is_classic                                             },
    { "game_event_channel_base_captured",        run_game_event_channel_base_captured        },
    { "game_event_channel_pill_captured",        run_game_event_channel_pill_captured        },
    { "game_event_channel_lgm_lost",             run_game_event_channel_lgm_lost             },
    { "game_event_channel_control_only_subscriber",
      run_game_event_channel_control_only_subscriber                                         },
    { "game_event_channel_client_emits_nothing",
      run_game_event_channel_client_emits_nothing                                            },
    { "game_event_channel_neutralised",          run_game_event_channel_neutralised          },
    { "game_event_channel_capture_index_base",   run_game_event_channel_capture_index_base   },
    { "game_event_channel_capture_wire_bytes",   run_game_event_channel_capture_wire_bytes   },
    { "game_event_channel_neutralised_no_client_line",
      run_game_event_channel_neutralised_no_client_line                                      },
    { "game_event_channel_capture_attribution",  run_game_event_channel_capture_attribution  },
    { "game_event_channel_subscriber_count",     run_game_event_channel_subscriber_count     },
    { "game_events_tank_spawned",                run_game_events_tank_spawned                },
    { "game_events_lgm_landed",                  run_game_events_lgm_landed                  },
    { "game_events_pill_placed",                 run_game_events_pill_placed                 },
    { "game_events_pill_picked_up",              run_game_events_pill_picked_up              },
    { "game_events_pill_killed",                 run_game_events_pill_killed                 },
    { "game_events_built",                       run_game_events_built                       },
    { "game_events_mine_laid",                   run_game_events_mine_laid                   },
    { "game_events_mine_exploded",               run_game_events_mine_exploded               },
    { "game_events_mine_placed_is_local",        run_game_events_mine_placed_is_local        },
    { "scenario_announce_null_policy_is_classic",
      run_scenario_announce_null_policy_is_classic                                          },
    { "scenario_announce_policy_asked_per_kind",
      run_scenario_announce_policy_asked_per_kind                                           },
    { "scenario_announce_quiet_stamped_on_every_fact",
      run_scenario_announce_quiet_stamped_on_every_fact                                     },
    { "scenario_announce_client_lines_read_the_byte",
      run_scenario_announce_client_lines_read_the_byte                                      },
    { "scenario_announce_wire_bytes",            run_scenario_announce_wire_bytes            },
    { "scenario_announce_pill_line_written_once",
      run_scenario_announce_pill_line_written_once                                          },
    { "scenario_announce_vote_line_held",        run_scenario_announce_vote_line_held        },
    { "scenario_announce_loopback_quiet_draws_no_line",
      run_scenario_announce_loopback_quiet_draws_no_line                                    },
    { "bot_init_table_two_bots_keep_own",        run_bot_init_table_two_bots_keep_own        },
    { "bot_init_table_empty_when_none",          run_bot_init_table_empty_when_none          },
    { "bot_init_arg_text_to_table",              run_bot_init_arg_text_to_table              },
#ifdef WB_NETDEBUG
    { "netdebug_commanded_vs_executed",          run_netdebug_commanded_vs_executed          },
    { "netdebug_overshoot_under_loss",           run_netdebug_overshoot_under_loss           },
    { "netdebug_mine_once_under_loss",           run_netdebug_mine_once_under_loss           },
    { "netdebug_error_offset_clamped",           run_netdebug_error_offset_clamped           },
#endif
};
#define NUM_TESTS ((int)(sizeof(s_tests) / sizeof(s_tests[0])))

/* Defined in test_stubs.c — every binary that links ClientSim needs to
 * own this symbol because the engine reads it from menu-aware paths. */
extern bool isInMenu;

GameSim *ut_rules_only_sim(void) {
    static GameSim gs;
    static bool filled = false;
    if (!filled) {
        simRulesClassic(&gs.rules);
        filled = true;
    }
    return &gs;
}

ServerSim *ut_make_running_sim(const char *player_name) {
    BYTE emap[6000] = E_MAP;
    ServerSim *sim = serverSimCreateCompressed(emap, 5097,
                                               "Everard Island",
                                               gameOpen, false, 0, -1);
    if (sim == NULL) {
        return NULL;
    }
    serverSimSetLobbyEnabled(sim, false);
    serverSimStartGame(sim);
    serverSimAddPlayer(sim, 0, player_name, false);
    return sim;
}

static int run_one(const char *name) {
    int i;
    for (i = 0; i < NUM_TESTS; i++) {
        if (strcmp(s_tests[i].name, name) == 0) {
            fprintf(stderr, "RUN  %s\n", s_tests[i].name);
            int rc = s_tests[i].fn();
            fprintf(stderr, "%s %s\n", rc == 0 ? "PASS" : "FAIL",
                    s_tests[i].name);
            return rc;
        }
    }
    fprintf(stderr, "unknown test: %s\n", name);
    return 2;
}

int main(int argc, char **argv) {
    /* This binary calls neither wb_log_init nor SDL_SetLogPriorities of its
     * own, so every custom log category sits at its default of ERROR and a
     * WB_LOG_WARN — the line a dropped or refused path leaves — prints
     * nothing. Opening the categories at WARN makes those visible when a case
     * fails. It relaxes no assertion and changes no code under test. */
    SDL_SetLogPriorities(SDL_LOG_PRIORITY_WARN);

    /* SDL_Init(0) brings up the SDL3 runtime so SDL_CreateMutex /
     * SDL_CreateThread are usable from the unit tests without
     * dragging in any subsystem-specific init. */
    if (!SDL_Init(0)) {
        fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 3;
    }
    (void)isInMenu;

    if (argc == 2 && strcmp(argv[1], "--list") == 0) {
        int i;
        for (i = 0; i < NUM_TESTS; i++) {
            printf("%s\n", s_tests[i].name);
        }
        SDL_Quit();
        return 0;
    }

    if (argc >= 3 && strcmp(argv[1], "--test") == 0) {
        int rc = run_one(argv[2]);
        SDL_Quit();
        return rc;
    }

    /* Default: run them all in sequence, bar the fixture writers. */
    int fail = 0;
    int i;
    for (i = 0; i < NUM_TESTS; i++) {
        if (isFixtureWriter(s_tests[i].name)) {
            printf("SKIP %s (regenerates a committed fixture)\n", s_tests[i].name);
            continue;
        }
        if (run_one(s_tests[i].name) != 0) {
            fail = 1;
        }
    }
    SDL_Quit();
    return fail;
}
